### ISSUE TITLE
Give backups file a more meaningful file name

### ISSUE THREAD

**Issue by grrrrr** [mtotschnig/MyExpenses#1001]
I would like to suggest slightly changing the default naming convention of the  created backup file.

### Issue
At the moment,  this is created as `backup.<date/time>.zip`.  The problem with this is it is not immediately clear from the file name what app the backup is for.  This is particularly noticeable when you choose a custom backup folder where all phone apps put there backups (when possible)

### Proposal

I would suggest adding the apps name to the file name.  e.g. 

`myexp-backup-....`

This way they are immediately recognizable as belonging to `My Expenses`  and grouped together in file listings.

**Comment by mtotschnig** [comment]
Prefix can be configured in Settings.
![image](https://user-images.githubusercontent.com/1485456/233854389-6803b10f-b485-466a-9ac0-571c74f08cea.png)
