### ISSUE TITLE
Balance account with transfer to closed account raises exception

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1019]
### Scenario
User create a transfer between two accounts.
Then clears the transfer in one of the accounts
Then closes the other account.
Then calls Balance account.

This triggers a SQLITE_CONSTRAINT_TRIGGER warning.

### Resolution
It is not clear if we should check for transfers that refer to closed accounts, and then show error message, or just allow the Balance to be executed, since it would not modify the transfer peer in the closed account. But if we decide to do so, we would also need to allow to clear transfers that are in the same situation, which is at the moment blocked.

**Comment by sivaraam** [comment]
I just stumbled across this bug while trying to balance an account. It is very much possible that the account has a transfer to a closed account. Could anything be done to enable balancing even if there is a transfer to a closed account ?

**Comment by mtotschnig** [comment]
@sivaraam Thanks for bringing this to my attention again. In 3.6.5, it will be possible to clear and reconcile transfers to closed accounts.
