### ISSUE TITLE
Feature Request: Highlight/jump to current day when grouping is set to day

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#1021]
This feature would be useful if there are a lot of future transactions, navigating to the current day may take a while.

Collapsing all future transactions may also be an option (only showing total balance, all the other info would be too much clutter when collapsed imo)

**Comment by mtotschnig** [comment]
In the Settings, there is an option "Upon app start, scroll transaction list to current date" that should do exactly that, if I am not missing something.

**Comment by alex9099** [comment]
That feature helps a lot, not quite what i meant (as in, if you go up to the "future" then finding today may be a bit cumbersome), but does the job just fine, so i'm closing :+1:
