### ISSUE TITLE
Debt management improvements

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1023]
This is a container allowing to group the following tickets for the roadmap vote:

### Open
- #927
- #926
- #1133 
- #1134

### Resolved
- #1022
- #947 
- #939 
- #1130 
- #938 
- #1131
- #1132

**Comment by niranjanpr23** [comment]
Please group these issues #938 and #926 to this debt improvement

**Comment by niranjanpr23** [comment]
Provide an option to add debt transactions as debt template

**Comment by mtotschnig** [comment]
@niranjanpr23 You mean that you should be able to select a debt when setting up a template, so that all instances will be linked to that debt. Correct?

**Comment by niranjanpr23** [comment]
Yes and whichever person we choosen it be for that persons debt

**Comment by mtotschnig** [comment]
I am packaging #1022 and #1130 for version 3.5.1 and will pick some of the other improvements for version 3.5.2.

**Comment by mtotschnig** [comment]
> Yes and whichever person we choosen it be for that persons debt

@niranjanpr23 Thanks for bringing the idea up (#1131). Do you suggest that, when I select a person for a template, that a debt should be automatically selected, if there is one defined for this person? I think, there should not be a difference between how debts work for templates or transactions. For transaction, it is possible to select a debt linked to a different (#880)

**Comment by mtotschnig** [comment]
Another important issue: #1132

**Comment by mtotschnig** [comment]
And #1133  and #1134

**Comment by mtotschnig** [comment]
The remaining tasks have been added to the Roadmap vote individually, so that interest in them can be assessed.
