### ISSUE TITLE
Budgeting 3.0: Allocations are not shown, when budget uses filter

### ISSUE THREAD

**Issue by allista** [mtotschnig/MyExpenses#1029]
APP_VERSION:3.4.5 (revision 554) 20220907-2213 GITHUB com.google.android.packageinstaller
FIRST_INSTALL_VERSION:535 (DB_SCHEMA 127)
ANDROID_VERSION:12

Just installed the update with the "Budgeting 3.0" and see the following:

- "Monthly" `default` budget with type `Monthly` lost all category allocations:
    - they are all zero
    - when I try to set one, it is still displayed as zero.
- "Yearly" budget now also has type `Monthly`, and it shows the `Monthly` allocations.
    - Thus, `Yearly` allocations are lost.
- I cannot change the type of neither the "Monthly", nor the "Yearly" budgets.

_Fortunately, I have auto-backup turned on_

**Comment by mtotschnig** [comment]
Would you be willing to share a backup from before the upgrade, deleting all the transactions and just keeping the budgets?

**Comment by allista** [comment]
I'm willing, but this is a bit troublesome: there's a lot of personal information in various tables which need to be cleared from the database. I cannot, for example, just truncate the `accounts`, because budgets refer them. Instead I would have to manually edit each row.
I'll have a go at it in the evening. Maybe I'll run an empty instance on a different device or an emulator...

**Comment by mtotschnig** [comment]
That would be perfect, if you were able to create a minimal example reproducing the issue. On my side, upgrade seemed to work correctly.

**Comment by mtotschnig** [comment]
I just discovered bug #1031. 
Is it possible that you edited the yearly budget? This would explain why it is now monthly?
I am not yet able to explain why on your monthly budget, allocations would have been lost.

**Comment by allista** [comment]
No, I haven't edited the "Yearly" since upgrade.

The allocations on the "Monthly" are not entirely lost, they are displayed in the "Yearly", and the "Monthly" always looks like new.

_I'm still struggling with the emulators_

**Comment by mtotschnig** [comment]
If you are familiar with building the app with Android Studio, you could it deploy it to your phone. The debug version lives in parallel with the release version because it uses a different application Id.

**Comment by allista** [comment]
I've compiled the `r546`, but had no time to experiment with it yet.

But when I tried to fix this by manually editing the DB from a backup, I found out that the filters that budgets use (category, account, etc.) are not there; rather, they are in the xml settings file.

So I started to experiment with this on my prod app and discovered the following:

- If I clear **category filter** from the "Monthly" settings, it starts to show its allocations (which are intact as seen in the `budget_allocations` table)
- If I then clear **account filter** from the "Yearly" it starts to be displayed as a `yearly` and shows its allocations (which are also intact).
- The types of both budgets _are correct_ in the `budgets` table.
- If I set the filters in budgets' settings again, the category allocations are again displayed incorrectly: "Monthly" shows zeroes, "Yearly" shows monthly.

Hope that helps.

**Comment by mtotschnig** [comment]
@allista Thank you for the detailed information. Unfortunately I was not yet able to reproduce the behavior. There is maybe some additional configuration, that I am missing?

**Comment by mtotschnig** [comment]
With version 3.4.5 (revision 554),  can you reproduce the bug with a new budget that would then not have gone through the migration process?

**Comment by allista** [comment]
Was finally able to run dev versions on my phone (no luck with ADV on my ubuntu - always black screen for some reason).

And immediately was able to reproduce the bug. Here are two backups:
- one made with `r546`, containing
    - 2 bank accounts
    - 2 budgets
        - one `monthly`
        - the other `yearly`
        - both with some allocations, filtering by accounts and categories, and "show only categories with allocations" enabled
- the other (later one) made with `r554` immediately after starting it and opening budgets. No setting was changed; budgets were not edited.
    - **both budgets display 0 in all categories**
    - "show only categories with allocations" is **disabled**
    - budgets retain their types, but when I try to edit the "Yearly Budget" its type selector displays `monthly` as per #1031 
    - if I edit the "Monthly Budget", clearing all filters, category allocations are displayed again

[backup-20220915-004602-r546.zip](https://github.com/mtotschnig/MyExpenses/files/9570347/backup-20220915-004602-r546.zip)
[backup-20220915-011036-r554.zip](https://github.com/mtotschnig/MyExpenses/files/9570346/backup-20220915-011036-r554.zip)

**Comment by mtotschnig** [comment]
Got it! Thanks a lot for your help. The source of the problem is that in the query the parameters for the budget and the categories were bound in the wrong order. 
I am sorry I was not able to reproduce earlier, since now it seems pretty obvious.
