### ISSUE TITLE
Merging categories

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1058]
In the past different versions of My Expenses did not trim white space from user's input for category labels, seemingly leading to duplicates. We should provide a tool for cleaning up these duplicates that shows a list of labels that have duplicates, allow to merge those into one category without leading or trailing white space.

**Comment by mtotschnig** [comment]
More generally: It should be possible to merge any categories.

**Comment by thomascrisan** [comment]
I vote for this; it would be useful, particularly when setting up My Expenses or using it with an existing desktop app with preexisting categories that got brought in via an import.
