### ISSUE TITLE
add automatic reoccuring payment?

### ISSUE THREAD

**Issue by formula-spectre** [mtotschnig/MyExpenses#1059]
title. something like "pay N amount of money to foo every {week,day,month}.". same for transfering money from one balance to another. It would be really handy.

**Comment by mtotschnig** [comment]
https://github.com/mtotschnig/MyExpenses/wiki/FAQ:-Templates-and-plans#how-to-create-a-recurring-transaction
Please let me know if this answers your question.

**Comment by formula-spectre** [comment]
yep, thanks!
