### ISSUE TITLE
Visual presentation of state of budget

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1102]
User suggest to provide pie chart representation on budget screen: Show "how the past budgets were completed: planned versus actual expenses and percentage of how much was spent against how much was planned with pie diagram presenting it visually."

**Comment by mtotschnig** [comment]
I am implementing a radar chart (using MpAndroidChart library) in version 3.8.3:
![grafik](https://github.com/mtotschnig/MyExpenses/assets/1485456/677952e0-fbeb-4829-af63-496732fcaa9b)
Based on feedback a different type of chart can be added in future versions.

**Comment by vaks78** [comment]
thank you.  it should be very useful feature

ср, 24 апр. 2024 г., 09:10 Michael Totschnig ***@***.***>:
