### ISSUE TITLE
Missing OK button in the categories editor

### ISSUE THREAD

**Issue by Antiwhore** [mtotschnig/MyExpenses#1105]
Hello again!
I've just installed the app and imported my old transactions from Money Wallet. The import went fine and old categories appeared. The problem is when I try to edit them or add a new one, there's no OK button in the editing window. So I have the category's name, icon and a cancel button. Obviously I can't save the category. Although I managed it once by tapping a random place in the window. So it looks like the button is there, but invisible.

**Comment by mtotschnig** [comment]
Could you attach a screenshot? Is the problem the same both on dark and light theme? Could you send a feedback request from the app's settings?

**Comment by Antiwhore** [comment]
Yes, I tried switching the theme and it was the same. I can't attach a screenshot here, so I'll send a letter to the address from settings and attach it there.

**Comment by mtotschnig** [comment]
After some discussion by email, my conclusion was that the problem is caused by some bug specific to the device (Volla OS), that I reported here: https://github.com/HelloVolla/volla-os-beta-test/issues/91
