### ISSUE TITLE
Polish language version

### ISSUE THREAD

**Issue by ppurs** [mtotschnig/MyExpenses#1115]
After changing the language of the application to Polish, not everything is translated. There are many gaps in the translations in sections like Help (Translations List and Account Management), Settings (several options: 'criterion for future transactions', 'request deinstallation of features and languages', planning settings), information about premium feature and possibility to buy only one feature.

![325959773_483180813987266_4209716631214368345_n](https://user-images.githubusercontent.com/79937466/213244411-cffe5da2-e5a8-4360-83d9-51b4e0b17fb1.jpg)
![326007040_572040514830467_9137783758715660509_n](https://user-images.githubusercontent.com/79937466/213244414-bbcab4a2-be5c-4da6-93c8-0a5739097c21.jpg)
![326069360_574840644163736_1629698179715985900_n](https://user-images.githubusercontent.com/79937466/213244417-60e36944-f8a7-42c1-9b77-cb51e1b480be.jpg)
![326099688_507101188076685_8864048400129003739_n](https://user-images.githubusercontent.com/79937466/213244418-fa416962-4854-4c2c-98ec-880c625da8c8.jpg)
![326112948_2321488871365273_6481970106738190215_n](https://user-images.githubusercontent.com/79937466/213244421-1a0c1a23-3382-4331-8a2c-fe49258bf1f4.jpg)
![326136976_3331490383846337_5440790309014856851_n](https://user-images.githubusercontent.com/79937466/213244427-19e84e72-a536-47df-bef2-fdb9f5df8fd9.jpg)
![326155634_3042011086099253_3155048546920699661_n](https://user-images.githubusercontent.com/79937466/213244430-00c4a45e-eaad-4e6d-9147-b86fa01ea859.jpg)
![326194395_899433254418905_2591666368660572017_n](https://user-images.githubusercontent.com/79937466/213244434-34fe6c13-7c1b-4798-9c98-2dec0f1d3132.jpg)
![326291385_2272696229558024_8929098916035500376_n](https://user-images.githubusercontent.com/79937466/213244437-c347bb10-4e0b-472b-9629-19741f78e595.jpg)
![326332724_1231715710751028_2654573278342510690_n](https://user-images.githubusercontent.com/79937466/213244439-3095e236-093a-462f-a914-b254ce5bdf06.jpg)
![326346168_3450967955150477_7051983317899902512_n](https://user-images.githubusercontent.com/79937466/213244440-fd3e23c7-f555-4249-8086-1d60cb59dbb0.jpg)

**Comment by mtotschnig** [comment]
Updates to the Polish translations are very welcome: https://hosted.weblate.org/languages/pl/my-expenses/
If you are interested in contributing, just register on Weblate, or contact translations@myexpenses.mobi .

**Comment by mtotschnig** [comment]
@ppurs I have a small budget allowing to remunerate translators. Let me know (translations@myexpenses.mobi) in case you are interested.

**Comment by mtotschnig** [comment]
Thanks to user Rcvrvugyvgvb on Weblate, Polish translation is complete again.
