### ISSUE TITLE
Search regression 

### ISSUE THREAD

**Issue by bo-skor** [mtotschnig/MyExpenses#1135]
Hello! Thanks for a great work!

A few releases ago, I noticed a significant regression in search. When you select search by recipient/payer, not only active recipients/payers are displayed, but in general all existing ones, which makes the search meaningless, since it turns out to be more difficult to search for the desired element in the search window than to find it in the table.

I really hope for a speedy fix. Good luck and all the best!

Здравствуйте! Спасибо за отличную работу!

Несколько релизов назад я заметил существенный регресс в поиске. При выборе поиска по получатель/платильщик отображаются не только активные получатели/платильщики, а вообще все существующие, что делает поиск бессмысленным, так как искать нужный элемент в окне поиска оказывается сложнее, чем найти его в таблице.

Очень надеюсь на скорейшее исправление. Удачи и всего самого наилучшего!

**Comment by mtotschnig** [comment]
@bo-skor Thank you for the report. Will add this to the next release.
