### ISSUE TITLE
Different grouping in the list of transactions and distribution

### ISSUE THREAD

**Issue by bo-skor** [mtotschnig/MyExpenses#1136]
Hello! Thanks for the work you've done!

A few releases ago I noticed a strange behavior of the "Distribution(?)" section
In this section, the diagram began to be compiled in accordance with the grouping in the transaction sheet. Thus, if the "day" grouping is used in the transaction sheet, then the chart with this grouping is also shown in the distribution. You had to choose the grouping manually, but a few releases ago this option moved even deeper into the menu, which became completely inconvenient.

In my opinion, the distribution(?) diagram is used to analyze the dynamics of finance over a longer period, so I propose to make it possible for the selected grouping in the distribution to be remembered, or to completely abandon the grouping function in relation to the distribution(?) diagram.

Good luck to you and all the best!
_____________________________________________________________
Здравствуйте! Спасибо за проделанную работу!

Несколько релизов назад заметил странное поведение раздела "Распределение"
В этом разделе диаграмма стала составляться в соответствии с группировкой в листе транзакций. Таким образом, если в листе транзакций используется группировка "день", то в распределении тоже показывается диаграмма с этой группировкой. Приходилось выбирать группировку вручную, однако несколько релизов назад эта опция переместилась еще глубже в меню, что стало совершенно неудобным.

На мой взгляд диаграмма распределения используется для анализа динамики финансов в более длительный период, поэтому предлагаю сделать возможным, чтобы выбранная группировка в распределении запоминалась, либо вообще отказаться от функции группировки, применительно к диаграмме распределения.

Успехов Вам и всего самого наилучшего!

**Comment by mtotschnig** [comment]
Duplicate of #934

**Comment by mtotschnig** [comment]
@bo-skor Thanks for bringing this up again. Will be addressed in next release.
