### ISSUE TITLE
Budgets: Show only categories with assignments does not work

### ISSUE THREAD

**Issue by seiffeli** [mtotschnig/MyExpenses#1145]
Although an amount is assigned to a category within a budget, it is not displayed if the "Show only categories with assignments" checkbox is selected.

[Screenshot.pdf](https://github.com/mtotschnig/MyExpenses/files/10879558/Screenshot.pdf)

**Comment by mtotschnig** [comment]
Thank you very much for the detailed report! I tried to create a similar setup but was not able to reproduce the issue If this is test data, would it be possible for you to share a backup of the database with support@myexpenses.mobi ?
Also could you either share here or via the "Send feedback" from the app's settings, details about version on OS?

**Comment by mtotschnig** [comment]
At the moment, one app instance only handles one database. You would need to install it on a second device, or build the app from source with a different package_id (for example debug build).

**Comment by mtotschnig** [comment]
Could you test if the problem also appears when you create a budget without categories filter ?

**Comment by seiffeli** [comment]
Error remains the same. The only filter set is EUR.

**Comment by mtotschnig** [comment]
and if you create a budget for a single account instead of an aggregate account?

**Comment by mtotschnig** [comment]
And it is always the same category that is visible, and always the same that are not shown? Can you see a pattern, if you try to try different configurations of which categories get allocations?

**Comment by seiffeli** [comment]
Problem fixed since version 3.5.3.2 (revision 611)

**Comment by seiffeli** [comment]
Problem fixed since version 3.5.3.2 (revision 611)
