### ISSUE TITLE
JSON export: Wrong encoding for ":" and "/" in categories

### ISSUE THREAD

**Issue by klx0** [mtotschnig/MyExpenses#1154]
# Issue
In JSON export in `category`, user input `:` is exported as `\\u003A` and `/` is exported as `\\u002F`. When parsing, both sequences are left as is, that is they are not getting decoded into the original user input.

# Solution
User input `:` should be exported as either `:` or `\u003A` (with a single `\`) to get parsed correctly.
User input `/` should be exported as either `/` or `\/` or `\u002F` (with a single `\`) to get parsed correctly.

While I am not aware of `/` having any special semantic meaning in `category`, the issue with `:` is that it is used as the separator for the segments of the category tree, e.g. `My category:Some subcategory:Some subsubcategory` (`:` in the meaning of a separator is exported as `:`, without any encoding). A solution is to export the category tree as an array, e.g. `"category":["My category", "Some subcategory", "Some subsubcategory]`. This removes the need for a character that has a special "separator" meaning. This would be a breaking change for any app that processes the `category` property, though.

# Appendix
I was wondering if there are more problematic cases, so I examined how several special characters are exported in different properties. While it is a little weird that several characters are encoded and others are not, they should all be valid except for the two cases of `:` and `/` in `category`.

| User input | `label` (account) | `category` | `comment` | `methodLabel` | `payee` | `referenceNumber` | `tags` |
|--------|--------|--------|--------|--------|--------|--------|--------|
| `%` | `%` | `%` | `%` | `%` | `%` | `%` | `%` |
| `^` | `^` | `^` | `^` | `^` | `^` | `^` | `^` |
| `~` | `~` | `~` | `~` | `~` | `~` | `~` | `~` |
| `\|` | `\|` | `\|` | `\|` | `\|` | `\|` | `\|` | `\|` |
| `[` | `[` | `[` | `[` | `[` | `[` | `[` | `[` |
| `]` | `]` | `]` | `]` | `]` | `]` | `]` | `]` |
| `<` | `\u003c` | `\u003c` | `\u003c` | `\u003c` | `\u003c` | `\u003c` | `\u003c` |
| `>` | `\u003e` | `\u003e` | `\u003e` | `\u003e` | `\u003e` | `\u003e` | `\u003e` |
| `{` | `{` | `{` | `{` | `{` | `{` | `{` | `{` |
| `}` | `}` | `}` | `}` | `}` | `}` | `}` | `}` |
| `@` | `@` | `@` | `@` | `@` | `@` | `@` | `@` |
| `#` | `#` | `#` | `#` | `#` | `#` | `#` | `#` |
| `&` | `\u0026` | `\u0026` | `\u0026` | `\u0026` | `\u0026` | `\u0026` | `\u0026` |
| `*` | `*` | `*` | `*` | `*` | `*` | `*` | `*` |
| `-` | `-` | `-` | `-` | `-` | `-` | `-` | `-` |
| `+` | `+` | `+` | `+` | `+` | `+` | `+` | `+` |
| `=` | `\u003d` | `\u003d` | `\u003d` | `\u003d` | `\u003d` | `\u003d` | `\u003d` |
| `(` | `(` | `(` | `(` | `(` | `(` | `(` | `(` |
| `)` | `)` | `)` | `)` | `)` | `)` | `)` | `)` |
| `_` | `_` | `_` | `_` | `_` | `_` | `_` | `_` |
| `€` | `€` | `€` | `€` | `€` | `€` | `€` | `€` |
| `"` | `\"` | `\"` | `\"` | `\"` | `\"` | `\"` | `\"` |
| `'` | `\u0027` | `\u0027` | `\u0027` | `\u0027` | `\u0027` | `\u0027` | `\u0027` |
| `:` | `:` | `\\u003A` | `:` | `:` | `:` | `:` | `:` |
| `;` | `;` | `;` | `;` | `;` | `;` | `;` | `;` |
| `/` | `/` | `\\u002F` | `/` | `/` | `/` | `/` | `/` |
| `!` | `!` | `!` | `!` | `!` | `!` | `!` | `!` |
| `,` | `,` | `,` | `,` | `,` | `,` | `,` | `,` |
| `.` | `.` | `.` | `.` | `.` | `.` | `.` | `.` |
| `?` | `?` | `?` | `?` | `?` | `?` | `?` | `?` |

**Comment by mtotschnig** [comment]
The idea of escaping these characters was inherited from the other exporters (QIF, CSV). In QIF, / has also a special meaning. In Json, it makes more sense as you mention to export the path as a list.

**Comment by klx0** [comment]
Schema has been updated at https://github.com/mtotschnig/MyExpenses/wiki/FAQ:-Import-Export/6cff6b4e8239843a9a692c4167d73076294e9865#is-there-a-schema-for-the-json-export
