### ISSUE TITLE
Quickly see accounts that are excluded from totals

### ISSUE THREAD

**Issue by klx0** [mtotschnig/MyExpenses#1168]
Accounts can be excluded from totals by editing the account and select *Exclude from totals* from the overflow menu. 
Unfortunately, the user is unable to quickly see all accounts that are excluded from totals. The user has to switch to the edit screen for each account and review the state of the checkbox in the overflow menu.     This is a tedious work if the user has lots of accounts. 
Suggestion: Show an appropriate icon in the account list for each account that has been excluded from totals.

**Comment by mtotschnig** [comment]
Any suggestion on how the icon should look like?

**Comment by klx0** [comment]
Could it be a sum symbol, as used in the account list for the total account, but with strikethrough formatting? It won't be available as a ready to use icon anywhere I guess, but maybe this could be inserted as pure text instead of an icon, maybe only in front of the account name or the sum. 

Or the sum of such accounts could appear with a strikethrough formatting in the account list.

Another approach: Do you use a specific icon set for the app? I could look through that set if I can find something that seems appropriate to me.

**Comment by mtotschnig** [comment]
The icons uses in the app UI mainly  are from https://fonts.google.com/icons . The category icons mainly are from https://fontawesome.com/ .
The sigma sign is a great idea. It appears in both sets:
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Afunctions%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048
https://fontawesome.com/icons/sigma
I was thinking of using it without strikethrough for the accounts, that are not excluded, and this icon would then just be missing for the excluded ones, but this could be confusing.

**Comment by mtotschnig** [comment]
Coming back to the ideal of indicating the inclusion state instead of the exclusion state. Maybe it would work. The Sigma symbol is already shown on the aggregate account itself. It could also be shown on each account that is not excluded.

**Comment by klx0** [comment]
Interesting idea!
I think, excluding accounts is something that occurs rarely. I believe that most users don't use that feature at all. They would face an extra UI element that doesn't provide use for them. On the other hand, there would be no harm here. Users who don't exclude any accounts would just ignore the extra icon and don't think about it, I guess. If you like to put more logic into it, that extra icons could be hidden unless at least one account has been excluded from totals. But maybe that makes it more confusing.

Or maybe it is just enough to use an imperfect generic icon like https://fonts.google.com/icons?selected=Material+Symbols+Outlined:block:FILL@0;wght@400;GRAD@0;opsz@48 to highlight excluded accounts.

**Comment by mtotschnig** [comment]
After some experimentation, I think the strike-through looks the best:
![grafik](https://user-images.githubusercontent.com/1485456/230726457-6b4a4f7f-6617-44a4-a152-f8ff0d2fd304.png)

**Comment by mtotschnig** [comment]
Additionally: In next version, it will no longer be necessary to invoke the edit command in order to exclude/include an account. Instead, this can be directly done from the account context menu.
![grafik](https://user-images.githubusercontent.com/1485456/230952751-b557af0e-6157-4973-9b2e-420e152d48ff.png)
