### ISSUE TITLE
What exactly is the device limit for a licence key on the F-Droid version?

### ISSUE THREAD

**Issue by tristan-k** [mtotschnig/MyExpenses#1175]
What exatcly is the device limit for the a licence key (contrib or extended) on the F-Droid version? Can I use the license key on more than one device or is it a single user license. In the [FAQ](https://github.com/mtotschnig/MyExpenses/wiki/FAQ:-Distribution) it is only mentioned that there is a limit but not what kind of limit.

**Comment by mtotschnig** [comment]
It's 5 devices. I have added this information to the FAQ entry.
