### ISSUE TITLE
Add expence dialog improvements

### ISSUE THREAD

**Issue by akostadinov** [mtotschnig/MyExpenses#1179]
Presently it takes too much effort to fill-in an expense.

First hurdle is the **Payee**. One has to write a letter to see the auto-complete options. This is very distracting especially when another language is used for the **Notes**. i.e. requires to switch between languages.

So the first improvement is to:
1. Auto-fill payee to be the last payee.
2. Automatically expand the auto-complete options when payee is tapped (or have a special button to show the list).

The next issue is **Notes**. Rarely if ever notes are the same between two items. So the second improvement I request is:
1. do not auto-fill notes
2. **or** if they are auto-filled, then provide a button to clear the field with one tap

This will make filling the form much faster and enjoyable.

Thank you.

**Comment by mtotschnig** [comment]
@akostadinov Sorry for not reacting earlier. Your second point should be covered, because Auto-Fill is configurable in the Settings. You can select which fields are filled. Please let me know, if this resolves your issue, or if I misunderstood your point.

**Comment by akostadinov** [comment]
Hi, yes - I can disable "Notes" from being auto-filled. That's great!

**Comment by mtotschnig** [comment]
As for your 1st point, I think the current behavior is suitable, if you have a high number of payees, but let's leave this open for others to comment, and to take it into consideration, if form is redesigned in the future.

**Comment by akostadinov** [comment]
Why not auto-fill the last one? Especially last one from current device? If payee was autofilled and focus is on amount, I'm sure this would save some 50% of time needed to file an expence in 90% of the cases. Even if you have a family of 5 which is above average, still 5 items in the expanded list is very little.

**Comment by mtotschnig** [comment]
I have the impression that your use case is different from what the payee field is designed for. You mention that the values you register in this field are the members of your family, but normally I suppose that users would use it to register the merchant where they spend money (Payee = a person to whom money is paid or is to be paid), and this is probably a constantly growing list. This might be different in the case of income, where there is probably a shorter list of payers (who you receive money from).

**Comment by akostadinov** [comment]
Ah, crap :roll_eyes: 

ok, that's fine then.

**Comment by mtotschnig** [comment]
@akostadinov Maybe your use case is related to #447 ?

**Comment by akostadinov** [comment]
Yes, it would make sense. Thank you.
