### ISSUE TITLE
Migrate to Material3

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#1193]
- [ ] Themes
- [ ] Chips
- [ ] Buttons
- [ ] DatePicker
- [ ] TimePicker
- [ ] Compose
- [ ] Settings Screen
- [ ] SimpleDialogFragments
- [ ] Colors
- [ ] Calculator
- [ ] Onboarding

**Comment by mtotschnig** [comment]
3.5.7 will be released with Material3 based theme with dynamic color
In future, when [material-components-android](https://github.com/mtotschnig/material-components-android) 1.10 is released, we can also use content-based color for the edit form, which will allow to use the user selected account color as primary ui color for the screen.

**Comment by alex9099** [comment]
Is it possible to have that as an option? 
I find the new design awful and will likely downgrade :(

**Comment by mtotschnig** [comment]
Maintaining multiple themes would come with an important overhead as far it is possible, and in the case of switching between Material 3 and older design systems I am not even sure, if it is technically achievable with realistic effort.
Independent of personal taste, keeping the app in sync with the development of the design system of Android is necessary, otherwise the app would eventually feel outdated. Imagine if, we would still use Holo or the style of Android 1...
I regret that you do not like the Material 3 style. Could you describe the pain points in detail? Maybe some optimizations are possible, providing an opt-out from dynamic colors might also be possible.

**Comment by alex9099** [comment]
Mostly it's just the insanely rounded corners and too big of a spacing between objects. (And I already have display and font size in the minimum and still find stuff way too big)
Colors also seem kinda off, not sure if that would be related with this dynamic color you say. The green seems like a sea green and the red seems almost like magenta.

I totally understand if it's not possible, and I get the technical implications of it

**Comment by Zwybelfisch** [comment]
Like alex, I am experiencing weird colours. I selected sunny yellow and grass green, and both are now sickly looking. I liked the plain white background everywhere, which has changed to a very light pink in some places (e. g. calenders), also I now see  purple buttons. Theres also a discrepancy between the colour I choose in the settings for an account, and the way the colour looks on the account page (Android 9.0.x).

**Comment by mtotschnig** [comment]
@alex9099  @Zwybelfisch Would it be possible for you to provide screenshots of the problems you experience, either here, or to support@myexpenses.mobi ?

**Comment by Zwybelfisch** [comment]
@mtotschnig I'll take a few screenshots. I did play around with the account colours today, so I have no shots of the original colours, but will try to recreate the effect.
