### ISSUE TITLE
recurrent items

### ISSUE THREAD

**Issue by akostadinov** [mtotschnig/MyExpenses#1210]
Hi

It's useful to allow recurrent items, for example subscriptions. Instead of every time to enter them manually, they should repeat until expired or stopped manually.

**Comment by mtotschnig** [comment]
https://github.com/mtotschnig/MyExpenses/wiki/FAQ%3A-Templates-and-plans#how-to-create-a-recurring-transaction

**Comment by akostadinov** [comment]
"Templates and plans" not super intuitive but also there is no label, only button so I guess name doesn't matter :) Works though, thank you.

**Comment by mtotschnig** [comment]
The label is revealed by long tapping on the icon.
