### ISSUE TITLE
Only consider visible accounts when showing total for multiple currencies

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#1212]
The app showing total in multiple currencies when accounts based on different currencies are present. This is a neat feature!

In my case, the purpose of other currency accounts were transient. So, I had closed and hidden the other currency account once its purpose is over. Regardless, the app still shows a other currency total in the "Total" section. This seems a bit of noise.

It would be great if the app only showed such a total when relevant accounts are visible.

I'm using v3.5.8 of the app on a OnePlus Nord running Android 12

**Comment by mtotschnig** [comment]
According to the current logic, visible accounts are included in totals. There is a separate flag that can be set on each account, that allows to exclude from totals. You'd have to temporarily show the hidden accounts, in order to set that flag, via the their context menu.
Currently there is a bug, where the Grand total account is still shown, even if all foreign currency accounts are excluded from totals. This will be fixed in version 3.5.9.

**Comment by sivaraam** [comment]
> You'd have to temporarily show the hidden accounts, in order to set that flag, via their context menu. 

Great. That actually did the trick for me. Thanks! 

Actually just excluding the cash account was sufficient somehow. I didn't have to exclude a foreign currency credit card account.

**Comment by mtotschnig** [comment]
> Actually just excluding the cash account was sufficient somehow. I didn't have to exclude a foreign currency credit card account.

That's an interesting edge case: The current logic only displays the aggregate currency account if there are at least two accounts for the currency, with the rationale that sum(1) is still 1 and hence redundant. But if the 1 account is hidden, but should still be included, then we should actually show the aggregate, so I might fix this. Then you will probably have to exclude that account as well.
Another question: I can explain why the aggregate account for the currency would no longer be shown, but I suppose there is still the "Grand total" account, isn't there?

**Comment by sivaraam** [comment]
> That's an interesting edge case: The current logic only displays the aggregate currency account if there are at least two accounts for the currency, with the rationale that sum(1) is still 1 and hence redundant. But if the 1 account is hidden, but should still be included, then we should actually show the aggregate, so I might fix this. Then you will probably have to exclude that account as well.

Got it 👍🏼 

> Another question: I can explain why the aggregate account for the currency would no longer be shown, but I suppose there is still the "Grand total" account, isn't there?

Yes. The "Grand total" account is still be there and shows transactions from the hidden but unexcluded foreign currency account alongside transactions form my local currency accounts
