### ISSUE TITLE
Date field font is too big

### ISSUE THREAD

**Issue by agalanin** [mtotschnig/MyExpenses#1213]
Since the last update, the font in the date field of the transaction editor has become too large. Now the date is being wrapped and it looks ugly. See attached screenshot:
![20230616_123318](https://github.com/mtotschnig/MyExpenses/assets/2493821/d2a2ea27-d4d4-4a58-b255-068c59fa6ebf)

Version: 3.5.8

**Comment by mtotschnig** [comment]
Thank you for bringing this up. It is not the font size, rather the margin of the button that leaves less space for the date. This is how old vs new compare on a Xiaomi A2 with standard font scale:
![grafik](https://github.com/mtotschnig/MyExpenses/assets/1485456/41decf50-be93-43b1-a027-b91b1cc538e7)
![grafik](https://github.com/mtotschnig/MyExpenses/assets/1485456/6e95a154-531d-40a3-97ad-a063ebe3a505)

**Comment by mtotschnig** [comment]
Two possible solutions: 

- Reduce the distance between text and arrows
- force date format to only use 2 digits for year: 17.06.2023

If both are applied, the date could fit in one line even with higher font scales.

**Comment by agalanin** [comment]
Thanks!
