### ISSUE TITLE
Import, allow to specify account for each lines in file

### ISSUE THREAD

**Issue by Matth7878** [mtotschnig/MyExpenses#1232]
When exporting you can choose all accounts to have one file with a column telling you from which account the entry is. It's super convenient!

Sadly for importing it's not possible since you have to select an account to import in. It would be nice if you could choose multi account and have a column in file imported to specify account.

**Comment by mtotschnig** [comment]
I agree that data exported by the app should be easy to re-import.

**Comment by mtotschnig** [comment]
The complicated part of this story is the handling of transfers. Currently when you export from an aggregate account, transfers are written twice to the file, for both sides of the transfer. When we import the file back, we need to reduce these two lines into one. Alternatively, we can modify the export to only write transfers once.

**Comment by Matth7878** [comment]
Would it be possible to only allow on import transfer for the source account and ignore import for destination account?

To be more flexible this could be done only when there is both line (source and destination account) for a transfer. I mean if there is a single line for a destination account only then it could be allowed. But I don't think it's really necessary.

I don't think it's not a good idea to change the export to only one line -> it would make incomplete backup for one account :⁠-⁠\
In my case I backup operations in an excel file and it would force me to manually duplicate those lines.

**Comment by mtotschnig** [comment]
@Matth7878 Thanks for your input. The QIF import already has the logic for recognizing transfers where both sides are in one file, so I am going to apply this logic for the CSV import. It needs a bit of refactoring, but it is doable.
