### ISSUE TITLE
hide "new balance" on the total account 

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#1240]
New balance option is shown when clicking the total sum account, this does nothing (as expected) and thus shouldn't show up.

As a suggestion, when clicking there, instead of showing the two options (copy to clipboard and new balance) it could straight copy to clipboard (maybe double click to prevent accidental clipboard wiping, but I think that's unlikely)

**Comment by mtotschnig** [comment]
@alex9099 Thanks for bringing this up. For keeping a consistent UX, I will stick with showing the menu also in the case of aggregate account, with only one entry (Copy to clipboard).
