### ISSUE TITLE
budgeting, can't set "aggregate expenses and income" from main view and it's not immediately updated

### ISSUE THREAD

**Issue by adrianinsaval** [mtotschnig/MyExpenses#1241]
despite this setting being global to all budgets one has to enter one specific budget to be able to set this option, besides this after changing this option and going back to the main budgeting view it is not updated to reflect the new setting, it's only updated after getting out and back in to the budgeting view.

Instead this setting should likely be per budget and instantly updated in the main view so it is not confusing

**Comment by mtotschnig** [comment]
@adrianinsaval Thank you for bringing this up. I have been thinking about implementing #212 in order to make to get rid of the need for this aggregate option, which would also solve #1035 . What do you think?

**Comment by mtotschnig** [comment]
With version 3.6.7, the global "aggregate expenses and income" option is gone. Aggregation will now happen based on the type of categories: https://github.com/mtotschnig/MyExpenses/wiki/FAQ%3A-Data#expense-and-income-categories

**Comment by mtotschnig** [comment]
In 3.6.8, the possibility to aggregate neutral categories will be reintroduced, together with 2 fixes to the problems originally documented: it can be set per budget and the budget list (and the widget) will reflect the change.
