### ISSUE TITLE
Option to remember the date for new transactions

### ISSUE THREAD

**Issue by Mpic** [mtotschnig/MyExpenses#1256]
I often add many transactions at once, for a whole month or more.

It would be very useful to have the option to automatically use the last date entered instead of today's date.

**Comment by mtotschnig** [comment]
@Mpic For the use case of entering many (similar) transactions at once, on the Edit screen there is the "Save and new" toggle in the action bar. Could you give it a try?

**Comment by Mpic** [comment]
Oh, nice, thanks !

This solves my problem :-)
