### ISSUE TITLE
Capitalize first letter in notes field

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#1269]
MyExpenses used to capitalize the first letter in the notes section. This seems to not happening anymore after an update (one that came long ago). 

If there's not a problem, could the capitalization of the first letter in the "Notes" field be brought back ? If there's a specific reason for disabling it, could you enlighten me about it? 

I'm using v3.6.3 of the app on a OnePlus Nord running Android 12.

**Comment by mtotschnig** [comment]
@sivaraam Thanks for bringing this up. The capitalization was removed by mistake when #714 was implemented. Will be fixed in 3.6.5.
