### ISSUE TITLE
Saving goals

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#127]
from user:
very useful function is a planning for future expense, with this feature the users could set their "saving goals" (for example a certain amount per month) and the App shows if the goals will be achieved or not and the daily or weekly difference between the goals and the really expense.

**Comment by DSIW** [comment]
I think it should be simpler. In my opinion it isn't important to see which month has which savings. Only the goal and the remaining time is important.

I like the idea to manage budgets. The app [Mint](https://play.google.com/store/apps/details?id=com.mint) has a clean design:

![img](https://lh3.googleusercontent.com/6MfwEjx76_1tzsTIZ9z4RBgyn-vvp-X_9INeFywl2q14yz-qihlR0cQdpz_10uzOvBOn=h310-rw)

**Comment by mtotschnig** [comment]
I opted for separating this ticket and #139 from the Budgeting functionality planned for 3.0 and implement a very simple prototype for 2.9.3: 
![screenshot_1536775695](https://user-images.githubusercontent.com/1485456/45444472-d13d4200-b6c7-11e8-9783-aac5d535fa8a.png)
Comments and suggestions for improvements are welcome.
