### ISSUE TITLE
FinTS/HBCI not possible with ING DiBa ?

### ISSUE THREAD

**Issue by Gaibhne** [mtotschnig/MyExpenses#1283]
All I get is `Fehler beim Ermitteln einer neuen System-ID`, whatever that might mean. I have a regular ING DiBa account, (read) access to which works in other banking software. I have tried both FinTS 3.0 as well as HBCI 2.2 based on comments I fo8und on Google, to no avail. I use `50010517` as Bankleitzahl, the last ten digits of my IBAN for Anmeldename and the same password I use to log in at https://www.ing.de - that is correct, right ?

Many internet resources refer to a new server URL I should be using, but MyExpenses is not offering to let me specify a server URL.

**Comment by mtotschnig** [comment]
@Gaibhne Could you follow all the advice on https://www.willuhn.de/wiki/doku.php?id=support:list:banken:misc:pintan#ing-dibapin_tan ?

**Comment by JonasVgt** [comment]
Hey, I am facing the same issue and have done some of my own experiments. The Error message seems to come from the following response to one of the requests to the bank server:

 `9010:Der gewünschte Geschäftsvorfall wird nicht unterstützt`

Unfortunately, I could not find any documentation on the error. Maybe you have some insights?

> @Gaibhne Could you follow all the advice on https://www.willuhn.de/wiki/doku.php?id=support:list:banken:misc:pintan#ing-dibapin_tan ?

I have tried all of them. They don't seem to help, as I get the same error regardless.

I have also tried to install Hibiscus software and tried to authenticate there. I was getting a very similar error when trying to use FinTs 3.0, but using the following two tips I was able to log in.

> Während der Einrichtung des PIN/TAN-Bankzugangs muss als HBCI-Version „HBCI 2.2“ eingestellt werden. Nachdem der Zugang erfolgreich getestet wurde, kann er auf „FinTS 3.0“ umgestellt werden. Grund: Bei FinTS 3.0 verwendet Hibiscus den PSD2-Modus - den die ING aber nicht unterstützt.

> Ein weiteres Zugangshindernis kann die fehlende Eingabe der Mobilfunknummer zu Sicherheitsverfahren sein (wird direkt nach dem Login auf der Webseite drauf hingewiesen). Diese Nummer muss zwingend angegeben werden, damit der Zugang funktioniert. Wenn es danach immer noch nicht funktioniert, sollte der Onlinebankingzugang in den Einstellungen auf der Webseite einmal gesperrt werden. Danach neu anmelden und den Zugang mit der App wieder freischalten. Dann kann man wie oben beschrieben den Zugang einrichten, muss allerdings trotzdem zweimal auf „Synchronisieren“ klicken!

I will do some more digging later. Hopefully this can be fixed somehow.

PS: These are the debug logs generated after pressing on the `Load accounts` button: [logs.txt](https://github.com/mtotschnig/MyExpenses/files/15093175/logs.txt) (note: I have redacted some stuff with `[--Redacted--]` )

**Comment by mtotschnig** [comment]
@JonasVgt Thanks a lot for debugging. I will look into it shortly.

**Comment by mtotschnig** [comment]
@Gaibhne @JonasVgt Thanks again for reporting and providing valuable information. It turned out to be an oversight on my side. [This report](https://homebanking-hilfe.de/forum/topic.php?t=24104) suggest to use "HBCI 2.2 (HBCI +)" and I did not include this version into the available HBCI-Versions. I was able to verify now that HBCI + works. I will publish shortly release 3.8.4.1 where My Expenses automatically selects the appropriate version for ING DiBa.

**Comment by default-student** [comment]
Amazing!
I just had this issue and now im patiently waiting for the release!

**Comment by JonasVgt** [comment]
Works perfectly now with the latest release. Thank you

**Comment by umrath** [comment]
Wow ich lese, müsste es eigentlich möglich sein, mich bei der ING anzumerken, richtig?
Ich bekomme aber auch die System-ID Meldung.
Ich habe die Bankleitzahl (50010517) von https://www.willuhn.de/wiki/doku.php?id=support:list:banken:misc:pintan#ing-dibapin_tan genutzt.

Was mache ich falsch?
