### ISSUE TITLE
wrong date in export

### ISSUE THREAD

**Issue by pfrancois** [mtotschnig/MyExpenses#1284]
if i try to export transaction whatever it will be on qif, txt or json,
the date is wrong by two way.
firstly the date is  wrong
secondly the date could not exist
one example of JSON is :
```json
{
        "amount": -28.99,
        "category": [
                "loisirs",
                "jeux"
        ],
        "date": "2023-02-38",
        "payee": "Amazon",
        "status": "RECONCILED",
        "uuid": "694de051-c39e-4faf-838c-d4589a4be7b2"
}
```

**Comment by mtotschnig** [comment]
Did you configure the date format and use mm (minutes) instead of MM (month) ?

**Comment by pfrancois** [comment]
yes it was a problem in the config.
not MM but the config should be "y-MM-dd", i have previoulsy "y-MM-DD".
