### ISSUE TITLE
BUG: Swallowed leading decimal point on existing entry edit

### ISSUE THREAD

**Issue by klaviartur** [mtotschnig/MyExpenses#1287]
When editing an existing entry and entering a value below 1 by starting with typing the decimal point (or in my case in Germany: comma) this decimal point is emitted.

Steps:

1. Select existing entry
2. Edit
3. type .5

Expected result: Amount is set to 0.50

Actual result: Amount is set to 5

The tap on the decimal point is not completely ignored as the amount is erased completely, but you have to either explicitly type 0.5 or ..5 to get what you want.

**Comment by klaviartur** [comment]
Can someone confirm, please? Thx

**Comment by mtotschnig** [comment]
Thanks for the report. I can reproduce it, and will try to fix for next release.
