### ISSUE TITLE
BUG: Partial sums reappearing in group header of transaction list

### ISSUE THREAD

**Issue by klaviartur** [mtotschnig/MyExpenses#1294]
Steps to reproduce:

1. Have a populated transaction list
2. activate grouping of transactions (by day, week, month or year)
3. hide partial sums for income / expenses / transfers by tapping on the center of any groups header
4. scroll to get that group off screen
5. scroll back

Expected result: Partial sums are still hidden
Actual result: Partial sums have reappeared

**Comment by mtotschnig** [comment]
@klaviartur Thank for the report. Will fix this for the upcoming version. On a side note: Did you know that you can set the default state of the partial sums in the Settings -> User Interface -> Transaction list -> Advanced -> Show details in group header
