### ISSUE TITLE
Include income transactions into budget calculations again

### ISSUE THREAD

**Issue by allista** [mtotschnig/MyExpenses#1317]
Since introduction of income/expense category attribute all my budgets started to simply ignore all income transactions, even if those are made in an "income+expense" category which is included in the list of categories in the budget.

This  breaks an important functionality which I can't find an alternative to in MyExpenses, namely: I have several budgets that include both income and expense categories, and 0 allocations, effectively showing me the difference between income and expenses for a period. This way I know at a glance how much I saved, say, this February as compared to May, or how much I saved during the whole year so far.

I understand that budgets are not exactly made for this job, but, again, I don't see any alternative.

Was forced to downgrade because of this.

**Comment by allista** [comment]
The difference between this and what the Distribution screen shows is that with budgets I control which categories of both expenses and income to take into account.

**Comment by mtotschnig** [comment]
@allista After receiving feedback similar to yours, I implemented this in version 3.6.8 (#1307), which should be available on F-Droid shortly (with 3.6.8.1 running up). If I am not mistaken, your use case should be covered with this, but leaving this open for you to confirm.

**Comment by Whint1996** [comment]
> I am not mistaken, your use case should be covered with this, but leaving this

Tried to verify the ¨aggregate neutral categories" option for @allista . Unfortunately after enabling the option the app crashes immediately and crashes again anytime Budgeting is opened.

**Comment by mtotschnig** [comment]
@Whint1996 Unfortunately I did not see any crash report that I could link to the scenario you describe. If you are on the F-Droid version could you send me the crash report from the dialog that should open after the crash, or if on the Play Store version, allow Sending of Crash reports from Settings -> Security / Privacy (and potentially communicate the Crashlytics User Id, found in Settings -> Advanced, to support@myexpenses.mobi ?

**Comment by mtotschnig** [comment]
The crash reported by @Whint1996 :  #1327
