### ISSUE TITLE
File Export: ADB pull, adb shell and Syncthing only access 0 byte files after export

### ISSUE THREAD

**Issue by uvok** [mtotschnig/MyExpenses#1321]
Hello,

I encountered the following problem using MyExpenses: After I exported all records with Three-dot-menu > Export and reset, neither adb pull nor Syncthing seem to be able to access the file. That is, when I adb pull /sdcard/MyExpenses, or sync the folder with Syncthing, I end up with 0 byte files on my PC.

I'm not sure if this is a bug in MyExpenses, or probably a limitation of Androids Storage Access Framework.

Steps to reproduce:

- Open MyExpenses database with some records
-  Three-dot-menu > Export and reset
- Choose any file type, if applicable, uncheck  the deletion and do-not-export-exported records options
- Try to adb pull the MyExpenses directory, or sync the directory with Syncthing

Actual Result:

- A 0 byte file on the PC

Expected Result:

- I get the exported file with the correct filesize

Workaround:

- Rename the exported file (Probably some file lock thing?)

Further info:

- even if I adb shell onto the phone, the file has 0 bytes. The file explorer shows the correct size, however

- MyExpenses version: 3.6.7.2 from F-Droid
- Android version: crDroid 9.9 / Android 13

**Comment by mtotschnig** [comment]
I was not able to reproduce this on an Android 13 emulator. I have the impression that it is caused by a problem within crDroid

**Comment by uvok** [comment]
Huh, interesting! Thanks for the hint. I retried it with a Google Pixel running GrapheneOS / Android 13, and adb shell shows the correct size after exporting; adb pull works as well.

I guess I can close this, since this is not related to the app.
