### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [mtotschnig/MyExpenses#1339]
https://hosted.weblate.org/projects/my-expenses/whats-new/#information
says AGPLv3, LGPLv, and LGPLv3
whereas
https://github.com/mtotschnig/MyExpenses/blob/master/Licence.md
says GPLv3

That seems off

it can be changed in
https://hosted.weblate.org/settings/my-expenses/glossary/
https://hosted.weblate.org/settings/my-expenses/website/
https://hosted.weblate.org/settings/my-expenses/whats-new/

**Comment by mtotschnig** [comment]
@comradekingu Thank you for bringing this to my attention. I have updated all Weblate components with GPLv3

**Comment by comradekingu** [comment]
@mtotschnig All good, except it is now "GPLv3-only", when it should probably be "GPLv3-or-later". :)
