### ISSUE TITLE
[Bug] Deposit with budget category doesn't show up in budget category transaction list

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [mtotschnig/MyExpenses#1351]
**Scenario**: A deposit of $300 with assigned category "Fun".

![Screenshot_20231221-192408-977](https://github.com/mtotschnig/MyExpenses/assets/86497467/1f43f09c-29f9-4b42-8a1d-becf394e415f)

---

**What Is Expected**: 

- The net balance (found under column labeled "Available") of the budget category "Fun" should increase by $300.
- This deposit transaction should show up in the pop-up list of transactions specifically for that category.

---

**What actually happens**:

- The net balance does not change. It should be in the green, but is still in the red:

![Screenshot_20231221-184642-628](https://github.com/mtotschnig/MyExpenses/assets/86497467/e2fc00d5-11b8-4afa-919b-27387f58b556)

- The deposit transaction does not show up in the pop-up list of transactions specifically for that category:

![Screenshot_20231221-184921-310](https://github.com/mtotschnig/MyExpenses/assets/86497467/d9e7f1a4-7139-460f-a36e-6114cc058788)

---

**Additional Details**:

- *App Version*: 3.7.0.1, installed from F-Droid
- *OS Version*: Android 11
- *Hardware*: Motorola One 5G Ace

**Comment by mtotschnig** [comment]
So your category Fun seems to be defined as a neutral category, so the way it is counted depends on the option "Aggregate neutral categories". This is explained in the Help dialogue:
"Transactions mapped to income categories are always counted as income, transactions mapped to expense categories are always counted as expense. This option allows you to configure how transactions mapped to neutral categories are counted: By default if they are positive they represent an income, if they are negative an expense. But if this option is activated, they are always included into both the sums of your income and expense."
So, switching on this option, should allow you to achieve the result you expect, if I am not mistaken. Please reopen, if it does not.

**Comment by PrivacyFriendlyMuffins** [comment]
It does indeed achieve the desired result!

**Comment by PrivacyFriendlyMuffins** [comment]
Strange... Is this setting new? I've add income before and I don't recall having this problem until now.
