### ISSUE TITLE
OFX Import and Export

### ISSUE THREAD

**Issue by thomascrisan** [mtotschnig/MyExpenses#1363]
This issue was closed twelve years ago but I hope the issue can be revisited for new reasons.

Several of my financial institutions no longer export to QIF. The current choices are QFX (Quicken), QFO (Quickbooks), and OFX.(Open Financial eXchange).

Would you consider adding OFX now for current compatibility with various financial institutions that are no longer offering QIF export?

I would also settle for QFX but as it is proprietary, I would prefer OFX.

[https://financialdataexchange.org/common/Uploaded%20files/OFX](https://financialdataexchange.org/common/Uploaded%20files/OFX%20files/OFX%20Banking%20Specification%20v2.3.pdf)

**Comment by mtotschnig** [comment]
@thomascrisan #3 was reopened in 2020, so I suggest to continue the discussion there
