### ISSUE TITLE
CSV import: category names with slashes are not understood and are imported as empty

### ISSUE THREAD

**Issue by GreggFr** [mtotschnig/MyExpenses#1368]
When I import csv files, if a line has a categorie or sub-categorie that contain _slashes_ (`/`) in its name, the line is imported **but** _payment method_ and _categorie/sub-categorie_ is leaved as empty.
Lines with no slashes in the categorie or sub-categorie names are imported normally.

The categories exist:
![Screenshot_20240103_122124_My Expenses](https://github.com/mtotschnig/MyExpenses/assets/24435844/9d862783-7ba9-4b8a-818b-2d3592793414)

For exemple, this file
| Date d'opération | Type           | Catégorie              | Sous-catégorie       | Libéllé                    | Montant |
|------------------|----------------|------------------------|----------------------|----------------------------|---------|
| 04/01/2024       | CB | ABTest - Parent | AB / subcat A | Cb card operation 31 12 23 | -4,00   |
| 03/01/2024       | CB | AATest / Parent | AA - subcat A | Cb card operation 30 12 23 | -6,00   |
| 02/01/2024       | CB | ABTest - Parent | AB - subcat B | Cb card operation 29 12 23 | -8,00   |
| 01/01/2024       | CB | AATest / Parent | AA / subcat B | Cb card operation 28 12 23 | -10,00  |

is weel unterstood by the import assistant:
![Screenshot_20240103_122320_My Expenses_b](https://github.com/mtotschnig/MyExpenses/assets/24435844/dcdbfff6-66cd-4a2a-b673-948d917ae5f9)

but is eventually imported like that: 
![Screenshot_20240103_122744_My Expenses_b](https://github.com/mtotschnig/MyExpenses/assets/24435844/166272d9-9326-4dcc-a3a9-8d1d32ea7782)

![Screenshot_20240103_122758_My Expenses_b](https://github.com/mtotschnig/MyExpenses/assets/24435844/c02bc70e-7894-4afe-8f04-3ab70ffe25ab)

![Screenshot_20240103_125357_My Expenses_b](https://github.com/mtotschnig/MyExpenses/assets/24435844/f5708edd-77c1-4ea1-a705-adfd8c37d93c)

Is there a problem in the import process with slashes or something else? 
Thank you for your help.

**Comment by mtotschnig** [comment]
@GreggFr Thank you very much for the report, and sorry for the late reaction. The source of this bug is that the CSV import shares code with the QIF import, and in the QIF format the slash has a special meaning. This will be repaired in next version.
