### ISSUE TITLE
Category synchronization does not remove deleted categories

### ISSUE THREAD

**Issue by Encrypt0r** [mtotschnig/MyExpenses#1373]
If a category is deleted from the 1st device, the export->import categories will not remove it from the 2nd device.
It would be nice to delete every local categories which no longer exists in the imported list.
When it can not be deleted (e.g. it still contains transactions) then please show a list to the user which are these categories that needs manual fix.

**Comment by mtotschnig** [comment]
The category synchronization was designed based on a merging strategy, I think when you want to get rid of all unused categories, then I would suggest that you select all categories and delete them before you import.

**Comment by Encrypt0r** [comment]
I forgot, that this import needs to support merging, too.
I accept your suggestion. You can then close/change this issue into a possible improvement.

The difficulty with your proposal is, that the delete all still leaves empty categories behind. Currently if a main category has at least one children which is mapped to a transaction, then that whole main category remains untouched. It results that none of the empty subcategories will be deleted. So currently I can only be sure that all unused categories are deleted, if I do this "delete all" at every single category level, which is a bit exhausting.

**Comment by mtotschnig** [comment]
@Encrypt0r: I have created a new ticket for recursively deleting unused categories: #1382
