### ISSUE TITLE
Invalid selected folder for backups and exports displays java.lang.object string

### ISSUE THREAD

**Issue by ferpasri** [mtotschnig/MyExpenses#1378]
<img width="601" alt="MyExpenses_Backup_folder" src="https://github.com/mtotschnig/MyExpenses/assets/32359126/7ceb6c4f-f8e9-49a2-8d9e-6b0d26ae9ca0">

The delta iteration from v665 to v671 introduces a bug regarding an invalid selected folder for backups and exports. It displays a `java.lang.object` string instead of the invalid folder.

It seems that it still persists in the v691.

Steps to reproduce:
1. Install a clean APK
2. Skip and get started into the application
3. Select an invalid Android system directory for backups. In my case, I used MyExpenses to create a new folder for backups in the system and intentionally deleted it from the Files manager to provoke this invalid behaviour.
4. Select to create a "Backup" which popup the invalid folder dialog.

**Comment by mtotschnig** [comment]
@ferpasri Thanks for the report!
