### ISSUE TITLE
Multi-transaction edit form

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#138]
using the multi-selection facility of the CAB, it would be nice if users were able to edit properties of several transactions at once like changing payer, account, comment etc.

**Comment by keunes** [comment]
Hi @mtotschnig
I just wanted to create a new issue to request this, but saw that you came up with the idea yourself already. Let's say this is a motivation to implement this ;)

I'd want to use this especially to bulk-edit the status (from unreconciled to cleared), as I once per month check if my edits are the same as in my bank's online administration (and make edits if necessary). Now I have to open transactions one by one to clear them.

**Comment by keunes** [comment]
Any concrete plans?

**Comment by mtotschnig** [comment]
@keunes There is no concrete plan for the moment. As for your use case: Do you know that you can click on the colored rectangle in each row of the transaction list to clear a transaction?

**Comment by keunes** [comment]
Oh wow. Good to know!

**Comment by keunes** [comment]
Your proposal would also cover #241 it seems.
