### ISSUE TITLE
[Feature request]: Recipient

### ISSUE THREAD

**Issue by ccuser44** [mtotschnig/MyExpenses#1391]
A recipient field should be added for the transaction.

This is one of the essential features for accounting apps.

**Comment by mtotschnig** [comment]
As far as I am aware, recipient and payee are synonyms. What would be characteristic of a recipient, that would require it to be entered in addition to a payee?

**Comment by ccuser44** [comment]
> As far as I am aware, recipient and payee are synonyms. What would be characteristic of a recipient, that would require it to be entered in addition to a payee?

Now that I think about it it may nit make sense to differentiate them

**Comment by mtotschnig** [comment]
@ccuser44 If you were using the app in some other language than English, it might also be the case, that the translation for "payee" is not optimal?
