### ISSUE TITLE
Unique constraint error while saving template

### ISSUE THREAD

**Issue by spencerkoo** [mtotschnig/MyExpenses#1404]
I updated a template, and I noticed that it saved without the tags that I had added. I looked at all my templates and noticed many without the tags saved.

I tried to update the template and add the tags, and I get an error:
`Error while saving transaction: UNIQUE constraint failed: transactions_tag.tag_id, transactions_tags.transaction_id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY[1555])`

Seems that this template exists with the same primary key. However, I do not have a duplicate template visible in my template list.

I had prior edited some templates. I tried to delete the templates in question and recreate them, but the same issue occurred with the template either saving without tags or throwing the primary key constraint error.

**Comment by mtotschnig** [comment]
Thank you for the report. This should be repaired in version 3.7.3.2. Cf. #1402
