### ISSUE TITLE
Editing transaction with original amount add comma

### ISSUE THREAD

**Issue by spencerkoo** [mtotschnig/MyExpenses#1405]
When editing a transaction that has an original amount, a comma is added to the original amount field, which causes an error while saving.

Rather than showing the error, it saves with the original amount being removed from the transaction. So you have to edit and add the original amount again.

The use case is that I save the foreign currency transaction, but update the converted amount when I see it on my bank statement.

The fix is to remove the comma from the "original amount" field, but this is especially cumbersome when dealing with currencies that generally have all values over 1000 (e.g. Japanese Yen).

Ideally, no comma would be in the original amount so that the transaction can be easily updated and saved.

**Comment by mtotschnig** [comment]
Similar to #1306 . Equivalent amount is also affected. The problem is not only that the number is formatted with grouping separator, but also that fraction digits are not configured correctly for the appropriate currency.
