### ISSUE TITLE
[Improvement/Roadmap item] filter by tag on distribution

### ISSUE THREAD

**Issue by spencerkoo** [mtotschnig/MyExpenses#1406]
Use case:
- This is common for me to want to look at the distribution with filters... either by tag, date, etc. 

Ask:
- Either:
  - Have the filters in the main transaction view carry and apply on the distribution
  OR
  - Be able to filter the distribution view in a similar way to the transaction view rather than only by expense, income, or aggregating neural categories

**Comment by mtotschnig** [comment]
@spencerkoo If I am not mistaken, this is identical to #502 which is already on the roadmap. Please reopen, if I there is some aspect I am missing.
