### ISSUE TITLE
reaffectation des opérations à une autre date

### ISSUE THREAD

**Issue by acuillefolly** [mtotschnig/MyExpenses#1415]
Bonjour, 
Lors de la réaffectation d'une ou plusieurs entrées d'un compte, on peut actuellement le faire dans une autre catégorie, un autre tiers, un autre mode de paiement ou un compte. 
Serait-il possible de le faire aussi à une date donnée ?
Ex: j'ai 3 opérations à 3 dates différentes (le 3/02 et le 05/02 et le 15/02) et je veux les indiquer comme étant prises en compte au 20/02.
Merci à ceux qui pourraient le faire 
je n'ai pas de compétences d'écriture de code, c'est pour cela que je soumets l'idée :)

**Comment by mtotschnig** [comment]
@acuillefolly Thank you for the suggestion. I'll close this in favor of #1369, where the same idea already came up. I plan to implement it in an upcoming version.
