### ISSUE TITLE
Tags/labels in addition to categories

### ISSUE THREAD

**Issue by Cathryne** [mtotschnig/MyExpenses#142]
Hello! Thanks for this neat app :-) I have just none hurdle before I can really use it as I would like to.

Is there are specific reason why MyExpenses and every other personal finance tool I tried so far provide categories (and hierarchical subcategories) instead of tags/labels like for example GMail does. Hierarchy can still be mapped with nested labels and they offer the IMHO huge advantage of being able to apply several tags to one expense.

Use case example: In addition to generally tracking expenses for food, maybe one wants to break that whole chunk down into nutrition types (dairy, meat, fish etc.) or place of purchase (market vs. mall) or even brands.

Another example: travel expenses occur within different contexts (commuting, leisure time, business travel etc.). Being able to apply specific tags for that not only to these expenses, but also to others that occur in the context of it would IMHO be very helpful.

@mtotschnig I noticed in #85 that you already use a bounty system. If you consider a tag/label feature worthwhile, what would be an appropriate bounty?

<a href="https://www.bountysource.com/issues/1776387-tags-labels-instead-of-categories?utm_source=1776387&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://api.bountysource.com/badge/issue?issue_id=1776387" /></a>

**Comment by klawdhfzasjhaa** [comment]
I would like to have both tags AND categories, not one instead of the other one.

**Comment by sabi0** [comment]
I am not opposed to the idea of tags. But the original suggestion could actually be implemented without them - by using additional custom attributes as suggested in #447

The benefit of attributes over tags is more control. You would not be able to (accidentally) set both "business" and "leisure" values on the same transaction. While with the tags you can.

Nutrition types could be (sub-)sub-categories under Food.
A combination like "transport" and "dairy" makes no sense. And the application could help user avoiding it.

P.S. Tags in addition to categories are implemented in the Wallets application - https://play.google.com/store/apps/details?id=com.romanenko.oleg.wallets

**Comment by mtotschnig** [comment]
To be released in 3.1.0
