### ISSUE TITLE
Keyboard not displayed

### ISSUE THREAD

**Issue by SnejPro** [mtotschnig/MyExpenses#1421]
When I try to load new FinTS activities I can not enter my password because the keyboard is not displayed:

![Screenshot_2024-02-21-09-43-23-75_30ebfaaae7046286c358d6571efbd74b~2.jpg](https://github.com/mtotschnig/MyExpenses/assets/11321022/493cfdd7-7b10-49b6-bf68-a1a4f401aa91)

OnePlus Nord 2 5G
Android 13

**Comment by mtotschnig** [comment]
@SnejPro Thanks for the report. This is fixed in version 3.7.5
