### ISSUE TITLE
Set weekly budget start day

### ISSUE THREAD

**Issue by cptserious** [mtotschnig/MyExpenses#1427]
It would be nice to be able to select the start day for the weekly budget. For instance, start my budget on Saturday and run through Friday.

**Comment by mtotschnig** [comment]
@cptserious Do you know that you can already configure the start of the week in the Settings (User interface -> Grouping periods)? Are you fine with globally setting the week start, or do you have a specific use case, where you would need week start to be different for a budget? The idea of being able to configure the start day per account already came up? Would it work for you if you could set the start day for the account, and the budget would you use the start day of the account that it is configured for?

**Comment by cptserious** [comment]
Setting it globally works just fine. I spent 30 minutes looking to see if there was a request for this specific thing but couldn't find anything. I guess my Google-fu was lacking yesterday. Thank you, @mtotschnig!
