### ISSUE TITLE
FinTS: Can not refresh transactions from Postbank 

### ISSUE THREAD

**Issue by SnejPro** [mtotschnig/MyExpenses#1434]
I have no problem connecting MyExpenses to my bank account (Bank: Fyrst or Deutsche Bank/Postbank) and initially fetching the transactions.
But when I try to fetch new transactions the loading screen stays forever and no new transactions are fetched.

With my Volksbank account everything works perfectly.

**Comment by mtotschnig** [comment]
Thank you for the report. Could you try to activate debug logging (Write debugging information into system log) in the Advanced chapter of the Settings screen, and then share the file Banking-latest.log ?

**Comment by SnejPro** [comment]
> Thank you for the report. Could you try to activate debug logging (Write debugging information into system log) in the Advanced chapter of the Settings screen, and then share the file Banking-latest.log ?

I'm working on it, but I noticed that there are credentials stored in this file. I think this is a major security risk and should be changed. 

I have a possible cause for my problem: Postbank does not publish FinTS for all their BLZs. But their support says that you can choose any other Postbank BLZ for Multibanking/FinTS. Does MyExpenses check if the BLZ in the response from FinTS matches the stored BLZs?
