### ISSUE TITLE
[PROPOSAL]  Add the ability to pay in crypto

### ISSUE THREAD

**Issue by TheFuzzStone** [mtotschnig/MyExpenses#1436]
I like your app and I would love to buy an "Extended Key" and pay with crypto [Monero (XMR)](https://www.getmonero.org/).

If you accept XMR from me as payment, I am ready to pay you anytime.

Thank you.

**Comment by mtotschnig** [comment]
Unfortunately I am not set up to accept Monero. Available options are mentioned here : https://www.myexpenses.mobi/en/#participate

**Comment by TheFuzzStone** [comment]
Unfortunately, I don't have PayPal and never will. If you change your mind, I'm willing to buy the key for 50 USD in XMR.

**Comment by lukeprofits** [comment]
Should accept XMR

**Comment by mtotschnig** [comment]
@TheFuzzStone @lukeprofits I have set up a donation on NOWPayments which allows you to pay in XMR  :
https://nowpayments.io/donation/myexpenses

**Comment by mtotschnig** [comment]
I did change my mind finally, please contact support@myexpenses.mobi, if you are interested in sponsoring the project in XMR.
