### ISSUE TITLE
Tesseract backend error

### ISSUE THREAD

**Issue by laci200270** [mtotschnig/MyExpenses#1438]
When I try to scan a receipt I get the following error:

`E linker  : library "/system/lib64/libjpeg.so" ("/system/lib64/libjpeg.so") needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace: [name="clns-5", ld_library_paths="", default_library_paths="/data/app/~~G--OQ38y1yv0T1jXJzSqSw==/org.totschnig.myexpenses-_Bcl0ZKOT4hWT0LtZecHUg==/lib/arm64:/data/app/~~G--OQ38y1yv0T1jXJzSqSw==/org.totschnig.myexpenses-_Bcl0ZKOT4hWT0LtZecHUg==/base.apk!/lib/arm64-v8a:/data/app/~~G--OQ38y1yv0T1jXJzSqSw==/org.totschnig.myexpenses-_Bcl0ZKOT4hWT0LtZecHUg==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~G--OQ38y1yv0T1jXJzSqSw==/org.totschnig.myexpenses-_Bcl0ZKOT4hWT0LtZecHUg==/split_config.hu.apk!/lib/arm64-v8a:/data/app/~~G--OQ38y1yv0T1jXJzSqSw==/org.totschnig.myexpenses-_Bcl0ZKOT4hWT0LtZecHUg==/split_config.xxhdpi.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/org.totschnig.myexpenses"]
`

Phone: Pixel 6
Android 14, latest patch

**Comment by mtotschnig** [comment]
Thank you for the report. This should be fixed in version 3.7.6.

**Comment by mtotschnig** [comment]
Fixed with 7183618c242f1acf85bb920b77377ec406a0e686

**Comment by mtotschnig** [comment]
Unfortunately this still seems to be a problem immediately after the dynamic feature module is downloaded. But a restart of the app fixed it on my side.
