### ISSUE TITLE
Synchronisation across multiple devices

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#145]
Users should be able to sync data between devices.
Use case A: Steve enters data on his phone, and after syncing with tablet can visualize reports on the bigger screen.
Use case B: Steve and Susi together have a shared bank account, both enter debit and credit on their phones, and can sync the data regularly

From use case B follows that sync should be doable on basis of single accounts, and not necessarily the whole database.

**Comment by qoheniac** [comment]
Are there chances for a reconsideration?

**Comment by mtotschnig** [comment]
When I close an issue without comment, that usually means the ticket has been implemented ;-) If you need help setting it up, please contact support@myexpenses.mobi. If there is anything missing or not working, please comment here, or open a new issue.
