### ISSUE TITLE
Graph data

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#146]
1) Graphical display of distribution per category per day/month/week/year
2) Graphical display of history of totals pers day/month/week/year

**Comment by mtotschnig** [comment]
Implementation of pie chart diagram is finished and will be released as 2.4.1 shortly

**Comment by paulle** [comment]
Thank you. Tested and works ok and looks very good. Only the percentage 
value within the piechart should be bigger/bolder.

Am So, 22. Feb, 2015 um 3:14 schrieb Michael Totschnig 
<notifications@github.com>:

**Comment by mtotschnig** [comment]
You are right about the percentage value. Will be fixed in 2.4.2.

**Comment by paulle** [comment]
When will you release 2.4.2 ?

**Comment by mtotschnig** [comment]
Thank you for your interest 2.4.2 will come with the implementation of #121. I plan for a beta version in seven days and the final release some days later.

**Comment by DSIW** [comment]
> Graphical display of history of totals pers day/month/week/year

Do you mean a cashflow diagram? My suggestion:

![cashflow](https://user-images.githubusercontent.com/744745/35568298-c30afaf2-05c8-11e8-99a0-ca9aecba1a10.png)

**Comment by mtotschnig** [comment]
@DSIW Many thanks for the suggestion. I will adopt it for the first iteration to be included into next version.

**Comment by mtotschnig** [comment]
Implementation of historical cash flow chart has been released on Play Store beta channel. I am closing this ticket. If you have new types of graphs in mind, please open new tickets.

**Comment by DSIW** [comment]
That's great, thanks. I'd like to be part of the beta program, but I couldn't find a button on the Google Play store for that.

**Comment by mtotschnig** [comment]
Please refer to https://groups.google.com/forum/#!topic/my-expenses-testing/RGiWUEWz154 on how to join the beta.

**Comment by DSIW** [comment]
Looks good! :-)
