### ISSUE TITLE
CSV export : allow to choose category separator

### ISSUE THREAD

**Issue by Matth7878** [mtotschnig/MyExpenses#1463]
Issue Separator for category levels in CSV export #1449 changed the separator used for categories.

Please allow to choose which separator to use. Right now it's producing exports files not using the same syntax as previously and stored exports. 🫤
I could manually modify all my previous exports but it would be nice to be able to still use QIF syntax.

**Comment by mtotschnig** [comment]
@Matth7878 Thanks for raising the issue. I am adding this to 3.8.0, currently in preparation.
