### ISSUE TITLE
Import to GnuCash errors with QIF, CSV

### ISSUE THREAD

**Issue by link-leo** [mtotschnig/MyExpenses#1522]
I am having trouble with importing `QIF` files to [GnuCash](https://www.gnucash.org/). I repeatedly get the following error:

> Missing QIF investment action for transaction dated MM/DD/YYYY.

I have attempted to make numerous manual corrections to the `.qif` file per the [guidelines](https://en.wikipedia.org/wiki/Quicken_Interchange_Format) to no avail.

I also note that the `CSV` export (using default options, anyway) is incompatible with a GnuCash import without several intervention steps in GnuCash.

**Comment by mtotschnig** [comment]
GnuCash seems to have a problem with QIF import: https://www.mail-archive.com/gnucash-user@gnucash.org/msg40172.html
With respect to MyExpenses CSV export, could you document what format would work best with GnuCash's CSV import?

**Comment by link-leo** [comment]
> GnuCash seems to have a problem with QIF import: https://www.mail-archive.com/gnucash-user@gnucash.org/msg40172.html

Understood. 👍

> With respect to MyExpenses CSV export, could you document what format would work best with GnuCash's CSV import?

I might not have time *this* week, but I'll try to document a mapping and get it to you.

**Comment by link-leo** [comment]
@mtotschnig I did a small mapping [here](https://itty.bitty.app/#GnuCash%20Mapping.html/data:text/html;format=gz;base64,eJy9V21v20YM/t5fwaUf1gB2ldcN8DQBaV6GAHVXNMGwfTzraOmw051wRy3xhv738fRSy46turBRfYiUI0XyIR+RdPzDze/Xj399vIWcCp28irsbCpm8Ar5iUqQxmS5un0s0HoEs/Gaqa+FzmIqyVCaLo0an0fe06J7DRWKm8W0pNL7TFX6yTx7++yIM19waGs9FofRiAkfvq1RJAdfWeKvxaARTa0RqR1BYY30pUvxl5e2ZdRLdBE7LZ+A3lITXd/W1qvakJOUTOL88KZ9XJTmqLKcJnJ28EBE+01holZkJpGgI3Sbf49RqLUqPrNQ+LdU+D+WB5Gjjcb6WoR0xlkJKrgajZL2zPpjhKGZWLjiWTWXx6l+GdXq+uzE3MZSP01xp+Qb/QXO8jkWkf2fOVkZO4PXNye3F3eWupgMnh6ydvPvp7upiY4lmlsgWE7jcnsEdfL8oTD9HP6+zpxY+teyaWS1XxcwVyzXdWMkdiadxHoi7J6bJXDlPTck2Eq/1Y6xZIfag7bm1NMypi5eciqO2d8RR03/iQM22reSnyZd2w89tbwquIdXC+1+P+hEcLRtQTMtmtjxzqwetYq/NXT/8wX0t36zWNcD7orSOXurxSc9BkK+EENMS2FdCkslVmjLBgxP5jQqrUQw6eSi14oI5YbxISVmz3V2skhuL3vxIUIgyjlSyl+cbQbjdWS31VZmcMjn4tperR1UMuDowro9igRiFv24AHvrUqbJOeIB3dgCUV8VX6FLL4c0HzDi58ngvZ9dsIrNuAX/W8Z+PLrYh6N44cJo/WEK/3dsW8bfVseAWDAVSbuV3w/VAgqoBYAd29wnn6NCkCKYqZkOUnWJh90uoSqly3+9DfBTZQfPI//XGUlSPoG5GnXWE46fmyOrem1rVDQ2KyhPMkOehKwTxR8j7KS8XcWolJuM4qu+gjKcwou28lUSdRBgJlUfXGPKktAaPGlOC0tkyCMZyvIB6fLOdbmF/G0ccwko8vTYFsk1EY0MvQkb667634KssQx/6FYTM9dpXnbl16217UOjBYenQ85fkoR1YITAejJAKHrcM0ocZFPYSQbwdGRJBHiYSU9NvCP2xk/Hm6yhYEI0NwJCfsklqobznpQHmCrXcZIZxTBchfEAe/Rxr+AqeRBvIPeRhS7KcC1MJzUlJHYYahshJuAwJRIPHQ73x1m5baF3mVL0nsBmrj3shxFFHj7hM7g1kaNAJPQLG4BGLeklzCCos1rYKu06Nya9P64CrDHtTw0zmX/0z7n94hJlF) if you're interested, along with some general notes.

**Comment by mtotschnig** [comment]
@link-leo Thanks for sharing!
