### ISSUE TITLE
Present tracking library - OpenTelemetry

### ISSUE THREAD

**Issue by ghost** [mtotschnig/MyExpenses#1523]
this is a placeholder

**Comment by mtotschnig** [comment]
@rathert8 Thank you for bringing up the question. OpenTelemetry is included by the Microsoft Authentication Library, used for the OneDrive synchronization. I'll investigate how to configure it based on user's consent.

**Comment by mtotschnig** [comment]
I received [feedback](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/2129#issuecomment-2218773271), that the MSAL library does not collect any data, it just instruments the code, in a way that would allow the client application to collect information by adding an additional dependency. This is not the case for My Expenses.
