### ISSUE TITLE
Order of fields in transaction summary

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#153]
Current order:
Category, Comment, Payer/Payee

User suggest to put Payer in first place

**Comment by mtotschnig** [comment]
Duplicate of #1217

**Comment by makeasnek** [comment]
> Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/2564517-order-of-fields-in-transaction-summary?utm_campaign=plugin&utm_content=tracker%2F267118&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F267118&utm_medium=issues&utm_source=github).

     

Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues
