### ISSUE TITLE
Transactions are not shown in the distribution screen when select "Income" only

### ISSUE THREAD

**Issue by gefloh** [mtotschnig/MyExpenses#1532]
When picking "Income" only in the distribution screen, no transactions are shown.

Steps:
- Open an account and go into the distribution screen
- In the three dots menu (or the filter icon, depends) set "type" to "Income" only, leave "Expense" unchecked
- Long press any category and select "Show transactions", the dialog which opens is empty for me with a sum of 0 (although there are transactions in this category and the chart e.g. shows the correct sum).

All other combinations of the types (both "Income" and "Expense", only "Expense") work as expected.

Version 3.8.6.1 (revision 744) 20240625-0747, F-Droid.

**Comment by mtotschnig** [comment]
@gefloh Many thanks for the report!
