### ISSUE TITLE
How am I supposed to register credit card transactions?

### ISSUE THREAD

**Issue by raffaem** [mtotschnig/MyExpenses#1536]
I have a credit card that works like this:

You buy stuff with the credit card in month `n`, the bank pays for it.
The 1st day of month `n+1`, the bank will charge your bank account for the expenses of the previous month.

How am I supposed to manage this with MyExpenses?

Currently I have two accounts: the bank account and the credit card account.

I charge the expenses on the credit card account, and the first day of the month I transfer the entire (negative) balance of the credit card account to the bank account (leaving the credit card account with a balance of 0).

By reading [this issue](https://github.com/mtotschnig/MyExpenses/issues/1215), I think this is what am I supposed to do.

Also I don't find anything in the wiki related to credit card management.

Then what is the problem?

The problem is that, for example under "Distribution", for my bank account I see the debit related to the transfer from the credit card account, but:

1. Strange enough, in the "Distribution" for the credit card account, I don't see the corresponding credit related to the transfer to the bank account
2. In any case, I want to "account" the expenses in the month in which they were sustained, not "double accounting" them both in the month in which they were sustained, and in the next month as a transfer. That is, I don't want to see the transfer under "Distribution".
In month `n`, I have spent only the stuff I bought in that month, not also the ones in the previous month.

How can I do that?

And in general, how am I supposed to manage the credit card?

**Comment by mtotschnig** [comment]
I think that you are doing it mostly right. The issue you are facing must be due to how you register the transfer. Because by default transfers are not counted on the distribution screen. So I suppose that you have assigned your transfer to an expense category, which is something that is possible for specific use cases, but in your case it would have the unwanted effect that you describe.

**Comment by raffaem** [comment]
> The issue you are facing must be due to how you register the transfer. Because by default transfers are not counted on the distribution screen.

So sorry about that.

Indeed I was registering two "normal" credit/debit on the two accounts, instead of a single transfer between the credit card account and the bank account account.

Indeed by recognizing a transfer, that's not shown in the distribution screen and that satisfies my needs.
