### ISSUE TITLE
Persistent Plus Button When Opening Settings Page

### ISSUE THREAD

**Issue by Handgrip3585** [mtotschnig/MyExpenses#1544]
When opening the settings page in the app, the plus button used to create a transaction remains visible. This issue has been observed on two different devices (Android 8, Android 10), Both devices are running app version 3.8.7 installed from F-Droid. The problem does not occur in version 3.8.6.1
![Screenshot_20240729_181344](https://github.com/user-attachments/assets/38a61193-5bc4-4d99-999b-2682afd10ed7)

**Comment by mtotschnig** [comment]
@Handgrip3585 Many thanks for the report!
