### ISSUE TITLE
Cross account search

### ISSUE THREAD

**Issue by skr3ch** [mtotschnig/MyExpenses#1549]
I find useful to make possible searching transactions across all the accounts (as account I mean all the "entries" in the left-bar menu). Sometimes I don't remember in which account I saved a transaction. So it needs time so perform a search for each account.

**Comment by mtotschnig** [comment]
@skr3ch Aggregate accounts show all transactions, and allow to search as well. This should achieve exactly what you ask for. Please give it a try.

**Comment by skr3ch** [comment]
Ok I noticed the feature now thanks to you. And is the "summed" (aggregated) account in the bottom of the left bar. Very sorry for the unuseful issue.
