### ISSUE TITLE
Web user interface not accessible with https

### ISSUE THREAD

**Issue by BlacknBlueBerry** [mtotschnig/MyExpenses#1557]
Unfortunately, the web user interface is not accessible via HTTPS. I always get an error message in the browser:

net::ERR_CERT_INVALID
Subject: MyExpenses.Mobi

Issuer: MyExpenses.Mobi

Expires on: 06.10.2024

Current date: 06.09.2024

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIB7zCCAVigAwIBAgIIG5jIM+T+m5MwDQYJKoZIhvcNAQEFBQAwJzELMAkGA1UE
BgwCREUxGDAWBgNVBAoMD015RXhwZW5zZXMuTW9iaTAgFw0yNDA5MDYwOTIyNTla
GA8yMDI0MTAwNjA5MjI1OVowJzELMAkGA1UEBgwCREUxGDAWBgNVBAoMD015RXhw
ZW5zZXMuTW9iaTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAq49IpNXVoDAD
Zy8bAxNSI92Qeh3CSHXQnv9kRjzOWA3HyQlZ61W7xdkkB8DvIowswB4V2Av9s+6X
pqA/B+N7d+8Fr6Dt8smPiYOToCLXYBQOIQXsskOiAnJr1A3JNptDNGjzY4YHqYUL
1DuzdAtC80TdohMGWuvZO7VQNAL3yeMCAwEAAaMiMCAwEwYDVR0lBAwwCgYIKwYB
BQUHAwEwCQYDVR0RBAIwADANBgkqhkiG9w0BAQUFAAOBgQBObwe0q6OhYGUwPy5N
C2GOvYatWHroauThFB6LKSZo+8i040ctY0vVoGOedU2UdMYx2WVIG+6kbX/vxymR
exIounCUXxqpEPP5bPd+b/igUnAE9lA35fQsLXAw1hpr2WtMbzhAQos3f6Yo7XQ6
IGnflh6BSw+NNvJB6gmmwQSCIg==
-----END CERTIFICATE-----

10.0.0.253 usually protects your information through encryption. This time, when Chrome tried to connect to 10.0.0.253, the site returned unusual and incorrect credentials. Either an attacker is trying to impersonate 10.0.0.253 or the connection was interrupted by a Wi-Fi login page. Since Chrome interrupted the connection before exchanging data, your information is still safe.

You can't currently access 10.0.0.253 because the website sent encrypted credentials that Chrome can't process. Network errors and attacks are usually only temporary, so the site will probably work again later.

**Comment by mtotschnig** [comment]
Running on your phone, My Expenses can only use a self signed certificate. Chrome does not have an interface anymore allowing you to trust the certificate. 
https://stackoverflow.com/a/47646463/1199911 mentions that you need to type a bypass sequence now: "thisisunsafe". Just tried it and it seems to work

**Comment by BlacknBlueBerry** [comment]
Wtf. Funny, it works 😅
Thanks!

Michael Totschnig ***@***.***> schrieb am Fr., 6. Sep. 2024,
23:49:
