### ISSUE TITLE
[bug] FinTS stopped working: "Property my.bic wurde nicht gesetzt"

### ISSUE THREAD

**Issue by ennedin** [mtotschnig/MyExpenses#1558]
Probably caused by the last Update (F-droid version 3.8.7.1) the FinTS-connection having been in use stopped working with the alert box saying
`Property my.bic wurde nicht gesetzt`
(aka "Property my.bic was not set")
as seen in the picture.

There was no pending TAN check regarding the manual online banking login as happened before, hindering FinTS over MyExpenses.
Password model change (v1→v2) #1548
seemed to process without error after that; still no FinTS function  though.
![image_7](https://github.com/user-attachments/assets/c552aaa8-38a7-4e6e-a3c5-c6d83fed9468)

**Comment by mtotschnig** [comment]
@ennedin Thanks a lot for the report. I have an idea what might have caused this, and hope to fix it for 3.8.8. In the meantime, if it is not too much overhead for you: Starting from scratch, i.e. delete the bank and add it again, might not be affected by the problem, but I am not 100% sure.

**Comment by ennedin** [comment]
Thank you for your reply and the upcoming fix!
The bank is:
KD-Bank (Dortmund)
