### ISSUE TITLE
Deep category hierarchy (more than two levels)

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#156]

**Comment by klawdhfzasjhaa** [comment]
Adding more specific info should be handled with tags #142 or in the notes field.

**Comment by mtotschnig** [comment]
Note to self: TODOs:

- DB Upgrade
  - Trigger
  - Delete Cascade for Categories
- Search Unmapped
- Aggregate Preference Update to new handling
- Tint / Shade for subcategories
- reconsider #71
