### ISSUE TITLE
[bug] [archive] Incorrect balance after unpack an archive

### ISSUE THREAD

**Issue by sharp-tasting** [mtotschnig/MyExpenses#1563]
https://github.com/user-attachments/assets/8c9353b2-d8fd-4c4d-a044-17515aebe98c

The screen recording is a demo of the bug.
After archiving and unpacking operation, I quit and reopen the app, and it shows a balance without counting the unpacked transaction.

Expected behavior: balance is 3
Actually happened: balance is 2

**Comment by mtotschnig** [comment]
@sharp-tasting Many thanks for the report!

**Comment by mtotschnig** [comment]
The problem will be fixed in release 3.8.9. The corrupted transactions will be fixed during database update.
