### ISSUE TITLE
App crashes reproducible on distribution screen of all expenses

### ISSUE THREAD

**Issue by gefloh** [mtotschnig/MyExpenses#1590]
Steps:

* Go to the list with all expenses ("Gesamtsumme")
* Open the distribution screen ("Verteilung")
* Long press one of the categories in the upper part of the screen
* Choose the option to show all transactions ("Buchungen anzeigen")
* The app crashes then reproducible for me

It crashes only in the all expenses section, not if you choose e.g. a concrete account and go to the distribution there.

App version 3.8.9, Android 15

**Comment by mtotschnig** [comment]
Thank you for the report. This should be fixed in version 3.9.0 (#1576)
