### ISSUE TITLE
Transfers between accounts of different currencies

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#160]

**Comment by Rayati12** [comment]
Hallo,

ich hatte Ihnen schon mal Anfang September geschrieben. Nutze die App wie gewohnt, das neue Design finde ich gelungen (wobei das alte auch gut war). Doch jetzt geht es wieder für mehrere Monate ins Ausland. Es wäre, wie gesagt, toll, wenn ich die andere(n) Währungen besser mit dem EUR hier synchronisieren könnte. 
Eine Möglichkeit wäre beispielsweise, in den "Taschenrechner" (der übrigens nicht funktioniert, wenn ich z.B. "65/0,012407" (Rubel) eingebe) eine beständige (!!!) Zahl eingeben könnte, die den Betrag jeweils multipliziert oder dividierte - je nach Kurs.
Eine andere Möglichkeit wäre, wenn man mehrere Einträge auswählen und gleichzeitig irgendwie bearbeiten könnte.

Viele Grüße,
Rayati

**Comment by mtotschnig** [comment]
@Rayati12 Vielen Dank für den Kommentar. Das Feature wird heute veröffentlicht. https://plus.google.com/+MyexpensesMobi/posts/CpBcd7zFtVS . Lass mich wissen, was du davon hältst.
Vielen Dank für den Hinweis auf den Bug im Taschenrechner.

**Comment by Rayati12** [comment]
Hallo Michael,

viele Dank für das schnelle update und entschuldige, dss ich erst jetzt antworte.
Ich finde, es ist auf jeden Fall eine Bereicherung. Doch was mich noch stört ist die Unmöglichkeit, es mit seinem "inlands-konto" zu verknüpfen. Ich werde sehen, was ich im Ausland ausgegeben habe - aber nicht in einem Gesamtkorpus, sondern als zwei getrennte Konten. Lieber wäre es mir, wenn es mit dem alltäglichen Konto einherginge. Dieses Problem kann man leicht lösen indem dem Taschenrechner zB eine "save-taste" beigefügt wird, bei dem ich den wechselkursmultiplilator eintragen und eben dadurch stets wiederverwenden kann. Ich wette, diese "Funktion" könnte auch in anderen Einsatzgebieten nützen!
Der Punkt mit dem Zahler / Empfänger erscheint mir nicht besonders nützlich. Ich benutze lieber die Kategorie "Einkommen" mit etwaigen Unterkategorien. Dadurch kann ich in der tortenansicht nachschauen, aus welcher art von Arbeit ich das meiste Geld schlage. Insofern ist diese Zeile gar überflüssig - besonders bei Handy mit weniger als 4,5", denn da muss man schon scrollen. Aber vielleicht entgeht mir nur ein tieferer sinn der Funktion, weil ich sie noch nicht ganz durchschaut habe.

Weiter so auf jeden Fall!

Viele Grüße ,
Ernest Krychmar

Von meinem Huawei-Mobiltelefon gesendet

-------- Originalnachricht --------
Betreff: Re: [MyExpenses] Transfers between accounts of different currencies (#160)
Von: Michael Totschnig
An: mtotschnig/MyExpenses
Cc: Rayati12

@Rayati12 Vielen Dank für den Kommentar. Das Feature wird heute veröffentlicht. https://plus.google.com/+MyexpensesMobi/posts/CpBcd7zFtVS . Lass mich wissen, was du davon hältst.
Vielen Dank für den Hinweis auf den Bug im Taschenrechner.

---

**Comment by mtotschnig** [comment]
Hallo Ernest, danke für die interessanten Ideen, bitte berücksichtige, dass Github hier ein Forum für alle Benutzer ist, und daher die Kommunikation hier auf englisch passieren sollte. Gerne kannst du dich mit Vorschlägen auch an support@myexpenses.mobi wenden.
