### ISSUE TITLE
Improve password dialog usability

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#164]
Suggested by user:
-Set an option for a numeric keyboard to type the password (just numeric).
-Rise automatically the password keyboard when te application is started and the password is enable.

**Comment by klawdhfzasjhaa** [comment]
Also related and useful #313 .

**Comment by mtotschnig** [comment]
Since protection by password is now deprecated in favour of the protection by device credentials, I am closing this.
