### ISSUE TITLE
Support different date formats for QIF export

### ISSUE THREAD

**Issue by MisterY** [mtotschnig/MyExpenses#218]
The Quicken version I use requires the following date format:

D04/20'15

This, however, is reported as an invalid date format by the app during export.

**Comment by mtotschnig** [comment]
You need to use M/d''yy . The ' character has a special meaning in Java's date format as escape character, so it must also be escaped.
Will need to add some explanation to the dialog (see #98)

**Comment by MisterY** [comment]
Ah, nice. Thanks!
