### ISSUE TITLE
Make it possible to move categories around

### ISSUE THREAD

**Issue by tasn** [mtotschnig/MyExpenses#251]
I have a few categories I use, but with time, I find some of them were put in the wrong place.

For example, I have "Supermarket -> Food", that I'd like to move to "Food -> Supermarket", as I care about grouping all of my food expenses together, and I don't care about my supermarket expenses being grouped.

At the moment, in order to do that, I'd have to manually go through each expense and change it to the new category. Being able to change the category hierarchy would solve my issues.

Thanks.

**Comment by mtotschnig** [comment]
Many thanks for reminding me of this feature, that already existed in the backlog as #85 for some time. Have changed its priority and will include it into one of 2.6.x. releases.
