### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by jkim-code** [mtotschnig/MyExpenses#252]
Suggesting a new icon for material design implementation.

![iconme](https://cloud.githubusercontent.com/assets/12594372/11170834/c7226b5a-8c23-11e5-8185-862bcdf7bd64.png)

Download ![iconME.svg.png](https://cloud.githubusercontent.com/assets/12594372/11170829/9b2656f6-8c23-11e5-8708-37200fdfc3a8.png) and change '.png' extension into '.svg' to get an original SVG file.

**Released under CC BY-NC-SA.**

**Comment by mtotschnig** [comment]
Many thanks! Sorry for the late reaction. This looks very promising. I am finishing 2.6.0 with Material design currently and did not have time yet to discuss this with my collaborators, but will certainly take this up for 2.6.1 or 2.6.2.

**Comment by mtotschnig** [comment]
Thanks again for your proposal. In the meantime, we won designer Pierluigi Rufo to craft the new material icon. I hope you like it as well.

**Comment by trmendes** [comment]
Nice Icon. I'm using the 2.7.9 version and the icon still a different one. Not as beautiful as this one here.
