### ISSUE TITLE
Doesn't run app after build

### ISSUE THREAD

**Issue by johnparra** [mtotschnig/MyExpenses#255]
Error:(2, 1) A problem occurred evaluating project ':MPAndroidChart:MPChartLib'.
> Failed to apply plugin [id 'android-maven']
   > Plugin with id 'android-maven' not found.

**Comment by mtotschnig** [comment]
Please remove or uncomment the line

apply plugin: 'android-maven'

from MPAndroidChart/MPChartLib/build.gradle

**Comment by johnparra** [comment]
Thanks a lot

John Parra
