### ISSUE TITLE
Configuration of group headers in transaction list

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#257]
Users often do not understand the meaning of the transfer sum (<->).
We could hide it, if there are no transfers in the current account.
We could also provide more contextual help that explains the meaning.

**Comment by rogers1106** [comment]
I would prefer to have all sums hideable. They take a lot of space and are not really necessary (for me). Displaying the current balance would be enough.

**Comment by mtotschnig** [comment]
User suggests to display reconciled total
