### ISSUE TITLE
Allow adding/removing currencies from the app

### ISSUE THREAD

**Issue by xmr-karnal** [mtotschnig/MyExpenses#264]
With a new cryptocurrency springing into existence every other week, the ability to add/remove custom currencies would be welcomed.

I had a quick look at the code and it seems impossible to add new currencies just by editing the database (a strategy that has worked for me in the past with other apps). It would also be necessary to add them to the CurrencyEnum, which wouldn't be possible without building the app by myself (and losing the benefits on having it available from f-droid)

So that's my suggestion, allow the end user to add/remove currencies (and to undo mistakes, an option to restore default currencies) at will.

What do you think?

**Comment by cryptokarnal** [comment]
Unfortunately it wasn't as straightforward to hack as initially assumed, because of java.util.currency.

Just adding BTC("Bitcoin") to CurrencyEnum is not enough, it complains with "BTC is not supported by your OS. Please select a different currency."

**Comment by mtotschnig** [comment]
Many thanks for bringing this up. I definitely plan to add support for custom currencies, maybe by using https://github.com/JavaMoney. For the moment what you could do, is to use XXX (No currency).

**Comment by mtotschnig** [comment]
One other use case in favour of this issue is that currently currencies that are not available in the OS can not be used, e.g New Belarusian ruble in older Android devices.

**Comment by hieu-van** [comment]
And also the upcoming Venezuelan bolívar soberano? :laughing:
