### ISSUE TITLE
Transaction widget (display current account balance, create transaction upon tap)

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#266]
EDIT: title changed to reflect other user's request as noted in [comment](https://github.com/mtotschnig/MyExpenses/issues/266#issuecomment-203119278) below.

Often I need to add a new transaction for my cash account. Currently I first have to open the app (go to the right account) and add the transaction. It would be nice to - just like Wunderlist - have a special widget that can be placed on the homescreen that opens the New Transaction dialog. I can imagine that the account will be opened which is at the top of the menu.
![screenshot_2016-02-10-10-35-56-01](https://cloud.githubusercontent.com/assets/11229646/12972169/022849ae-d0a3-11e5-97ea-9a49925a9d59.jpeg)

**Comment by mtotschnig** [comment]
My Expenses has home screen shortcuts for adding new transactions, transfers, split transactions. You can add them from the app settings.

**Comment by keunes** [comment]
Thanks, I didn't know :)
It doesn't really look awesome, though. It would be nice if it had the ME logo with a plus sign :)

**Comment by mtotschnig** [comment]
I am adding to this ticket a suggestion received by a user for 1x1 Widget, that would only show the current balance of one account, and upon tap open the form for new transactions with this account selected.

**Comment by mtotschnig** [comment]
After some investigation, I am leaning towards the following change for the existing account widget, which should provide the functionality requested in this ticket:

1. Widget is made resizable.
1. Current controls are removed:
    1. The navigation controls on the left should not be needed if the accounts are rendered in a listview, and vertical swipe allows to navigate to next account
    1. Tap on an entry either opens the transaction list or the new transaction form. This is made available as widget configuration.
