### ISSUE TITLE
FR: easy sort of accounts (via long-press)

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#267]
I thought sorting of the accounts wasn't possible, but creating a new account *does* present the user the option to enter a sort key. It would be great if the order of accounts could be changed easily afterwards, simply by long-pressing the account, and moving it up or down the menu.

**Comment by mtotschnig** [comment]
Many thanks for the suggestion. Actually I am preparing a new way of configuring sorting of categories, templates, accounts for the next release, and I nearly overlooked the current sort key.
My idea would be the following: On top of the account list there is a new menu with a sort command that allows to select between sorting by

- title
- count of usages
- last used
- custom

If custom is selected, in the overflow menu of each account, commands Up and Down are added.

What do you think?

**Comment by keunes** [comment]
Hmm. To be honest for me such advanced sorting isn't necessary. I only have 6 accounts, which can easily be sorted manually.

But apart from that I would avoid a new menu at the top of the menu (which actually feels a bit like a russion doll, now I write it here) as it takes up screenspace for a function that probably is only used exceptionally. Exceptionally, because I would expect users to have a rather stable preference and not such a large number of accounts that you would switch sorting frequently (as you would with a dataset). Then I'd rather put this menu at the bottom (next to new account) - which I know isn't really intuitive - or just as an option in the settings.

If long-press sorting is implemented and the current sorting setting is automatic (ie title/usage count/last used), there'd ideally be a snackbar notifying the user that automatic sorting has been switched to 'custom'.

**Comment by keunes** [comment]
Oh, and btw: it would be cool if the 'Account' field options order in the New/Edit Transaction/Transfer/Split dialog would follow global sorting :)

**Comment by mtotschnig** [comment]
Many thanks for your thoughts. I think that moving the new account button up together with the new option in the overflow means to not spend any additional screen estate, and have the options where they make sense. As illustrated in the attached screenshots.
![device-2016-02-11-104256](https://cloud.githubusercontent.com/assets/1485456/12973787/5927b27e-d0af-11e5-8d0f-5ecf385db9ed.png)
![device-2016-02-11-105939](https://cloud.githubusercontent.com/assets/1485456/12973788/59299d00-d0af-11e5-9298-b2a85e4f9a9b.png)
![device-2016-02-11-110233](https://cloud.githubusercontent.com/assets/1485456/12973789/5929fe58-d0af-11e5-8c9a-601694d5595f.png)

**Comment by mtotschnig** [comment]
With respect to the Accounts field in the transaction form, it currently respects the sort order setting (alphabetic, count of usages), but your are right, it ignores the custom sort key. Will be fixed in next release.

**Comment by keunes** [comment]
For me personally it's still 'wasting' space (as in the initial view I see less 'accounts' data, while I'm not helped with the title, nor the other options). But looks neat otherwise :)

Will you also enable long-press for custom sort (at some point in time)? That would make sorting way more intuitive and make the hidden-away 'Custom sort key' option (in new accounts dialog menu) redundant 0:)

**Comment by mtotschnig** [comment]
I am definitely working on removing the "Custom sort key" field, and implement a more intuitive way. But I think long-press and showing a context menu is not necessary, since there already is the overflow menu. Drag an drop would certainly be the most intuitive option, but I think it is too expensive with respect to implementation effort.

**Comment by keunes** [comment]
Yeah, I was thinking of long-press to drag & drop.

> If custom is selected, in the overflow menu of each account, commands Up and Down are added.

If you want to reorder your stuff, it's pretty cumbersome. Imagine having 6 accounts (like me) and wanting to move the last one to the second place. That's going to take 10 taps + scrolling. Maybe an option would be to display the up/down button left from the overflow menu (there's enough space in my case), possibly with a way to hide/display them (e.g. use Google's [sort icon](https://design.google.com/icons/#ic_sort) in two different grey tones as a toggle, placed left from the 'add account' button)

**Comment by keunes** [comment]
Actually, [AntennaPod](https://github.com/AntennaPod/AntennaPod) uses handles to allow the user to reorder the queue, when the queue is unlocked. That's where I got the idea for a toggle to display/hide the options. Maybe (possibly this is a stupid thing to say) some of its code can be re-used to provide something similar.

![ap_handels](https://cloud.githubusercontent.com/assets/11229646/12980020/d160331c-d0da-11e5-984c-b3d505a0f2a2.png)

**Comment by mtotschnig** [comment]
Many thanks for this suggestion. Actually, this solution currently could not be easily adopted for My Expenses, since it is based on the RecylerView, and the account list uses the StickylistHeaders library, which is based on ListView. For the moment, I will stick with the approach based on the Up/Down commands, but keep this in mind, for once the account list might be migrated to RecylcerView.
