### ISSUE TITLE
FR: option 'display current balance only'

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#268]
Currently, a lot of data is displayed per account in the account overview (swipe from left). This makes (in my case) only 2.5 accounts visible (of the 6).
It would be nice to have an option in the settings (under the User interface heading) to dis/enable extensive data. If enabled: display current situation. If off: only display the numbers that in the current situation are below the line.

Maybe it would even be possible to create a setting where the user can select which of the currently displayed data should be shown (e.g. being able to pick only 'Expenses' and 'Current balance').

In any case that would enable me to switch accounts without scrolling (or swiping from the first to the last account).

**Comment by mtotschnig** [comment]
Thank you for the suggestion. Another idea would be that the cards would have an expanded and a collapsed state. And you could expand/collapse them individually or the whole list. What do you think?

**Comment by keunes** [comment]
Yup, sounds nice. Probably even easier. Curious what will be displayed in the collapsed view :)

**Comment by mtotschnig** [comment]
The collapsing account info has been implemented some time ago.
