### ISSUE TITLE
Include a Changelog Link, on the F-Droid Info' Page, 2.6.5.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [mtotschnig/MyExpenses#270]
Include a Changelog Link, on the F-Droid Info' Page.  Now on v. 2.6.5.1, and it's not there.

**Comment by locutis-of-borg-1999** [comment]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 2.6.5.1.

**Comment by mtotschnig** [comment]
Many thanks for the suggestion: I have updated the changelog on http://www.myexpenses.mobi/#versionlist and submitted a pull request to F-Droid for an update of the description with a link to the changelog included
https://gitlab.com/fdroid/fdroiddata/merge_requests/1233
