### ISSUE TITLE
App thinks it's November 2

### ISSUE THREAD

**Issue by ezeenova** [mtotschnig/MyExpenses#271]
When I group my transactions by month, My Expenses just displays the date November 2 at the top of the screen and nothing else, see screenshot.
![myexpensesbug](https://cloud.githubusercontent.com/assets/9629779/13314370/278e5d5c-dba5-11e5-824f-32d6fbe951e1.png)

Similarly, when I group by week it says "Last week (???-???)" with no transaction summary.
![myexpensesbug2](https://cloud.githubusercontent.com/assets/9629779/13314464/930baca6-dba5-11e5-87dc-b8139da56cca.png)

**Comment by mtotschnig** [comment]
Hello, this bug introduced in 2.6.5 should have been fixed with 2.6.5.1. Could you check if you have the latest version?

**Comment by ezeenova** [comment]
I am using 2.6.5.1 from F-droid. Bug is still present.

**Comment by mtotschnig** [comment]
Could you tell me on which Android version and on which device you are seeing this?

**Comment by ezeenova** [comment]
Android version is 4.4.4, device is Samsung Galaxy S2.

**Comment by mtotschnig** [comment]
Could you try to kill the app (remove it from the task list) and start again, and report if you still see the same buggy display?

**Comment by ezeenova** [comment]
That fixed it, thanks!

**Comment by mtotschnig** [comment]
Thanks for your report. There is still a problem because this should not appear in the first place. Do you remember how you did enter the app when the problem appeared: through launcher icon, widget, or anything else?

**Comment by ezeenova** [comment]
Launcher icon. I'm using [KISS launcher](https://github.com/Neamar/KISS), in case that's relevant.
