### ISSUE TITLE
enhance transaction camera options

### ISSUE THREAD

**Issue by ilf** [mtotschnig/MyExpenses#272]
I like the option of adding pictures to individual transactions. I take a picture of the paper bills.
But the camera doesn't seem to respect the orientation: the images are always landscape, even when taken portrait.
Also, I'd love an immediate rotate and/or crop option after taking the image. But I have no idea what the Android Camera API allows you to do.

**Comment by mtotschnig** [comment]
Thanks for bringing that up. The faulty orientation of the images will be fixed in next release. Still need to investigate how to implement rotate/crop.

**Comment by mtotschnig** [comment]
Another interesting enhancement suggested by user is to allow to attach multiple images.

**Comment by ilf** [comment]
Haha, I just rediscovered this. A cropping-option immediately after taking a picture would still be awesome, so would multiple pictures.

**Comment by mtotschnig** [comment]
One more idea: preference setting that allows to compress images by a certain ratio

**Comment by woj-tek** [comment]
Huge +1 for cropping - this would be especially useful in case of receipts which quite often are far from share or even 16:9 proportions.

**Comment by alex9099** [comment]
Remove the roadmap label as it is already solved ;)
@mtotschnig

**Comment by mtotschnig** [comment]
@alex9099 Thanks for the reminder. The script importing issues into the roadmap vote already excluded closed issues. I just had to run it again.
