### ISSUE TITLE
Why does MyExpenses need info about my wifi?

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#273]
There's an update awating for me in the Google Play, by MyExpenses requires extra permissions. What is it used for?

I feel an app that stores *all* my financial transactions shouldn't have access to the internet. Even though it's open source, most users (me included) won't be able to check whether it uploads the data to some (unwanted) place.

**Comment by mtotschnig** [comment]
MyExpenses' distribution on Google Play is ad financed for some time now and thus needs the Internet permission. But Internet permission is also needed for sending crash reports via Acra. The introduction of  the request for permission ACCESS_WIFI_STATE is caused by the inclusion of a new Ad provider (RhythmeOne). You can use MyExpenses without Internet permission if you use its distribution on F-Droid.

**Comment by keunes** [comment]
> ad financed for some time now and thus needs the Internet permission

I was surprised to see the request for wifi since I paid for the premium version. Isn't it possible to somehow exclude the ad system in the premium version?

> You can use MyExpenses without Internet permission if you use its distribution on F-Droid.

Can I use all Google premium functionality if I install the F-Droid version?

**Comment by mtotschnig** [comment]
> isn't it possible to somehow exclude the ad system in the premium version?

The premium version is distributed in the same app. Packaging it as a separate app would make it much more difficult for users to migrate from free to premium. Ideally the new Android permission system introduced in Marshmallow would allow users to grant or revoke Internet permission, but Google decided to not include Internet permission into it.

> Can I use all Google premium functionality if I install the F-Droid version?

The F-Droid version uses a different mechanism for purchase, so it is not transferable. But I send out keys to contributors, so shouldn't be a problem for you ;-)
