### ISSUE TITLE
Standard expenses/revenues

### ISSUE THREAD

**Issue by xavihernandez** [mtotschnig/MyExpenses#276]
Hi, thanks for this usefull application, I have discovered it few weeks ago and it is very good to manage our expenses/revenues.

It would be good to be able to set "standard" expenses/revenues which occur daily, weekly, monthly, etc.
For example salary is a revenue which comes daily, weekly or monthly  and therefore it can be set at each day or an index of day of week or month (eg. 5th day of each month). Another exampe is a rental of a house which is a daily, weekly or monthly event.
Then, every new entry would be a ponctual expense or revenue.

**Comment by mtotschnig** [comment]
Thank you for the feedback. My Expenses also supports recurring payments. From the action bar, select the command "Templates and plans". Create a new template, and click on the "Create plan" button. This will bring you into your calendar app, where you edit the type of recurrence. Please contact support@myexpenses.mobi or comment here again, if you have further questions.

**Comment by xavihernandez** [comment]
Oh ok sorry for tat then. I have tried that already, but may have missed the recurrence feature. I didn't want to create an event in calendar neither ;p. 
Anyways I'll have a try!

**Comment by mtotschnig** [comment]
My Expenses allows you to configure the calendar where the events are stored, and you can simply hide this calendar in your calendar application, so it won't interfere with the rest of your time management.

**Comment by xavihernandez** [comment]
True! Anyways it is ok, thanks for your help :+1:

**Comment by xavihernandez** [comment]
:)
