### ISSUE TITLE
Watch parties'  transactions

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#292]
Looking at the 'parties' list, I see a party called "drink after French class". Obviously that's a (one of the multiple) mistake that I made when filling in the entry form.

It would be nice to be able to use the context menu (which already displays 'edit' and 'delete') to view all transactions of that party. I imagine a view opening similar to the account view; with on the left a vertical bar color-indicating the account that the transaction is on, the account name in the action bar replaced with the party name.

That would make it a whole lot easier to correct abovementioned mistake, and, moreover, add a nice new functionality (e.g. see how much I spend in store X).

**Comment by mtotschnig** [comment]
This is good idea. But instead of taking the account view as the reference, I'd rather start from the distribution screen with parties instead of categories. Thus you would first see the distribution per party, and second you could click on an entry, and the list of transactions would come, as is the case currently in the distribution per category. What do you think?

**Comment by keunes** [comment]
> I'd rather start from the distribution screen with parties instead of categories. Thus you would first see the distribution per party, and second you could click on an entry, and the list of transactions would come

To be honest: nice idea, but I don't think it would be that useful in practice. In supermarkt chain Jumbo I do my groceries, any money I spend on friends concerns presents (or joined dinner) and any money I give to Friends of the Earth is, well... a donation.
I think - at least I'm sure it's the case for my spending pattern - *many of the parties are only linked to one, two or maximum three categories. Distribution view makes total sense for accounts, not so much for parties.*

Adding the distribution view doesn't give much additional information, while making it harder (read: increasing the steps) to see actual transactions.

So instead I would just (few changes compared to first proposal):
- go straight to the party view (base layout & functionality: Total account view) with only that party's transactions
- with the hamburger menu replaced by a back arrow
- [currency] in the action bar replaced by the party's name
- disable 'payer/payee' filter ('cause already applied)
- remove [current balance], [templates & plans icon] and everything in the overview menu (except 'help', like is the case for 'templates & plans')

**Comment by mtotschnig** [comment]
I think you misunderstood my suggestion. I did not mean that you would see how the transactions of one party are distributed to different categories, but how the transactions of one account (which includes the aggregate accounts per currency) are distributed to different parties.
By the way, if I am not mistaken, what you are requesting can already achieved with the Search functionality.

**Comment by keunes** [comment]
how the transactions of one account (which includes the aggregate accounts per currency) are distributed to different parties

Right, that makes a lot more sense ;) That'd be nice to have indeed, as long as it's easy to reach the party's transaction overview.

> if I am not mistaken, what you are requesting can already achieved with the Search functionality.

Yup, but it's not the fastest way as you havd to switch views and search for the correct party (or the most convenient if you have to remember long strings with a bad memmory - as in my case) ;)

**Comment by keunes** [comment]
Your proposal would also cover #241 it seems.

**Comment by mtotschnig** [comment]
Exactly. I was looking for this ticket, and somehow couldn't find it ;-) I consider this as a duplicate then and close it.
