### ISSUE TITLE
Longer status background intended?

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#297]
Dunno if this was an intended change or not with the latest update, but now the status of a transaction shows the background colour to the full width. Personally prefer the old situation (background limited to the text). I think mainly because of the unequal paddings.

![tmp_11217-screenshot_2016-05-30-23-49-33-01-1056715141](https://cloud.githubusercontent.com/assets/11229646/15658942/3102e632-26c3-11e6-91b9-9c00eae16761.jpeg)

**Comment by mtotschnig** [comment]
Many thanks for spotting and reporting.
