### ISSUE TITLE
color eye distracting

### ISSUE THREAD

**Issue by paulle** [mtotschnig/MyExpenses#302]
![expenses](https://cloud.githubusercontent.com/assets/4852079/15818705/1efcbfdc-2bdf-11e6-97e5-f1444a4fa255.png)
Please change this light cyan color to a darker (blue) one. It makes the things hard to read with this background colour.

**Comment by paulle** [comment]
Or please change the cyan to full black, this will give a good contrast to white, green and red.
![1efcbfdc-2bdf-11e6-97e5-f1444a4fa255](https://cloud.githubusercontent.com/assets/4852079/18026527/1d26a730-6c4a-11e6-818e-b94ea90bc9ce.png)

**Comment by paulle** [comment]
Thank you for looking this issue. I know it's only 'cosmetic', but not distracting colours and contrasts make it easier and more fun using your program.

**Comment by paulle** [comment]
What a pity, latest update (2.7.1.2) didn't change the eye distracting color combination.

**Comment by mtotschnig** [comment]
Sorry, 2.7.1.2 is a beta release that gives access to some bug fixes. This issue will be addressed in next production release. If we go for a 2.7.1.3 it will be part of it as well.

**Comment by paulle** [comment]
Thank you for this information.


Am 14.11.2016 um 21:25 schrieb Michael Totschnig:
