### ISSUE TITLE
Enable 'Transaction detail dialog' via 'Show transactions' (from distribution)

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#304]
Sorry for the long title :P
I'm checking the distribution, discover an exorbitant amount in a specific category, check the transactions by long-pressing the category. And indeed there's one transaction that's in the wrong category. It would be nice to be able to tap on that transaction to open the 'Transaction detail dialog' (from which you then can open the edit transaction view). I imagine when closing the detail dialog or editing view one returns to the transactions overview.

Hope it's clear :/

**Comment by mtotschnig** [comment]
I plan to release this with 2.7.1 ASAP, so would be interested if you find time to test it.

**Comment by keunes** [comment]
Works like a charm, thanks! (now I only still have to find that wrong transaction again, haha)
