### ISSUE TITLE
UI Change: Input time and date more straightforward

### ISSUE THREAD

**Issue by paskalito** [mtotschnig/MyExpenses#310]
Currently there are two boxes for that one for date and one for time. And this is perfectly ok when you immedeatly enter your purchases when you made it but it becomes kind of a clicking hassle for all the purchases you didn't/couldn't enter in the app immeadeatly.

for all those purchases i save the recipes and enter them all at once when they eat up too much space in my wallet.
at almost all of these i need to completely input the date and time and they are usually not so close to the current date that it would be reasonable to scroll to the desired date.
luckyli one can cklick on the date and then you can conveniently enter it.
![screenshot_2016-07-06-12-43-44](https://cloud.githubusercontent.com/assets/8012793/16615588/06003a12-4378-11e6-943c-e614ddee1bc5.png)

but a you need to click on it and be they don't go automatically to the next.
so in for the time field i need to click 4 times (just to be able to type in the numbers)

e.g:
![screenshot_2016-07-06-12-50-28](https://cloud.githubusercontent.com/assets/8012793/16615655/78b14768-4378-11e6-89e4-35c907ad0283.png)
![screenshot_2016-07-06-12-50-33](https://cloud.githubusercontent.com/assets/8012793/16615656/7a6fec08-4378-11e6-9761-e94b2b38548c.png)
![screenshot_2016-07-06-12-50-36](https://cloud.githubusercontent.com/assets/8012793/16615657/7bf3bd66-4378-11e6-980b-3a6faeb7fbc5.png)
![screenshot_2016-07-06-12-50-39](https://cloud.githubusercontent.com/assets/8012793/16615658/7d6adf08-4378-11e6-8095-08cabe88158a.png)

so what i ask for is:
1. change the month format to numbers instead of the full name (needed in order for this to be really usefull and it also is standard format on the recipies (at least around here)
2. merge the date and time field into one
3. focus the input field automatically on opening.
4. automatically switch to the next field when first one is filled out (so i can straightly type 1243 and it will have the value 12:43 as time)

thats all and it would greatly improve my workflow. i think this are rather minor changes. but maybe there are complications at least some things like the "focus on opening" should really be easy and every step i actually already helping so even if they're not completet at the same time they would help.
regards paskalito

**Comment by mtotschnig** [comment]
For date and time entry MyExpenses currently uses widgets provided by Android, and implementing them on our own is not feasible with our current resources.
By the way, on newer phones, these widgets look more modern.

**Comment by mtotschnig** [comment]
In recent versions, we use pickers from Material Design Components, so they should provide better usability.
