### ISSUE TITLE
Attach PDF to transaction (in addition to jpeg image)

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#311]
Related: #1093 .

**Comment by Olicop** [comment]
Bonjour,
Je vous propose mettre en place, la possibilité de mettre en document attaché les fichiers pdf, car presque tous nos fournisseurs nous adressent les factures en pdf et on ne peut pas les joindre avec nos écritures sur nos comptes bancaires . 

Cordialement, 

Olivier 

Merci encore pour votre travail.

**Comment by mtotschnig** [comment]
TODOS:

- [ ] Import / Export
- [ ] Backup / Restore
- [ ] Synchronization
