### ISSUE TITLE
Autofill should also update account

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#312]
From user: When you want to add new transaction and select payee from drop-down list everything is automatically filled from previous transaction from same Payee, except Account. Why not to auto-fill account also.

**Comment by mtotschnig** [comment]
Only concern I have is that some users might expect that the account does not change, since they are used that the account sticks to the one that was active when they started entering the transaction.

**Comment by redbaron-gt** [comment]
I understand your concern, but for example I have 5 accounts with same currency and I am grouping with currency and I always have selected Total to show all transactions in this currency. So if I select total there is no account selected so it can be autofilled from previous transaction. Looks like a solution!
