### ISSUE TITLE
Allow unlock with fingerprint

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#313]

**Comment by tristan-k** [comment]
Have a look at [Keepass2Android](https://keepass2android.codeplex.com). They call it quick unlock.

**Comment by ashjas** [comment]
question: Which users will be able to upgrade to version 3.0?
I have purchased extended key. Will this feature come under it?

**Comment by mtotschnig** [comment]
@ashjas Thanks for your question. Our current (not final) plan is to develop fingerprint unlock as part of the Professional Key. As announced on https://plus.google.com/+MyexpensesMobi/posts/Ukn7qzikUCm, with the introduction of this new licence level, we hope to gather the resources needed for dedicating more time to the development, maintenance and support of this and many other new features.

**Comment by mtotschnig** [comment]
I am currently investigating if using the "Confirm Credential"
(https://developer.android.com/about/versions/marshmallow/android-6.0.html#confirm-credential) approach is more useful than implementing a fingerprint based lock mechanism inside the app. Any thoughts?

**Comment by mtotschnig** [comment]
Will shortly be released as 2.8.7. Probably as part of the free version, since implementation was more straightforward than expected.
