### ISSUE TITLE
Add MyExpenses icons to homescreen shortcuts

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#316]
Slightly different (simpler) from #266: please use the MyExpenses new icon as a base and add the appropriate symbols (transfer, transaction, split) to it.
Current situation simply looks ugly and isn't indicative of what it does (maybe I have another app that also offers this functionality).
![screenshot_2016-08-30-14-00-44-01](https://cloud.githubusercontent.com/assets/11229646/18088478/383d62c0-6ebb-11e6-9b0a-eca3546c6b75.jpeg)

The wunderlist 'widget' is a great example:
![022849ae-d0a3-11e5-97ea-9a49925a9d59](https://cloud.githubusercontent.com/assets/11229646/18088517/7505754e-6ebb-11e6-9267-b41cbefa11a0.jpeg)

**Comment by mtotschnig** [comment]
With the implementation of #326, on 7.1 shortcuts are rendered like this:

![image](https://cloud.githubusercontent.com/assets/1485456/24552144/a6857d0a-1625-11e7-963c-1350de5b3e5d.png)
 
If you agree, I'd backport the same design to older devices.

**Comment by keunes** [comment]
> If you agree, I'd backport the same design to older devices.

In the meantime my device updated to Android 6. But yeah, that'd be cool :)
