### ISSUE TITLE
Allow custom date formats

### ISSUE THREAD

**Issue by tasken** [mtotschnig/MyExpenses#333]
Not all languages/countries use the same date format. A simple setting would do. Thanks.

**Comment by mtotschnig** [comment]
My Expenses already uses the date format provided by the user's locale. Could you document how this does not work for you?

**Comment by tasken** [comment]
Hi mtotschnig, thanks for your reply. I'm using english as my system language, but i don't use american date format mm/dd/aaaa. If a setting was provided, My Expenses could use default locale setting, or be configured to a specified value. Regards.

**Comment by SparkyCola** [comment]
Does Android allow you to select another English, I use English Ireland for this reason, it gives me dd/mm/aaaa if your looking for this otherwise you could just check the other English locales.

**Comment by mtotschnig** [comment]
Reopening this, since the transaction list item renderer implemented since #1036, is hardcoded to DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM), and should also be customizable.
