### ISSUE TITLE
Qif import

### ISSUE THREAD

**Issue by lauco74** [mtotschnig/MyExpenses#342]
When we import by qif à filé with a split transaction inside and when thé catégories and subcategories does not exists, only thé first term create thé missing sub/catégories. Thé other stays to (null).

**Comment by mtotschnig** [comment]
I think there has been a similar problem with earlier versions, but I cannot reproduce it with the latest one. Could you check?

**Comment by mtotschnig** [comment]
Missing feedback has me assume this is no longer an issue
