### ISSUE TITLE
Recurring payments don't work.

### ISSUE THREAD

**Issue by amilopowers** [mtotschnig/MyExpenses#352]
I tried several times to make plans and have recurring payments either pay in or out. They sometimes work the first time but mostly they didn't work at all.

Phone: Nexus 5 or Nexus 6P
Android 7.1.1
My Expenses 2.7.6

**Comment by mtotschnig** [comment]
Many thanks for your report. Unfortunately this feature was plagued by a defect for a long time due to a flag missing on the calendar where the plans are stored, which resulted in unreliable expansion of plan instances. I think this is resolved in 2.7.6, but plans created by older versions could still be affected by the problem. Could you verify again with a new plan?

**Comment by amilopowers** [comment]
I think I solved the problem by giving access to contacts. I don't know why but at least it worked.

**Comment by amilopowers** [comment]
Question: can I hide the "MyExpences Calendar" in the cal app?

**Comment by mtotschnig** [comment]
That is quite surprising that access to contacts should have affect on behavior of calendar, but thanks for the report. Could you tell me on which device and which Android version you observed this?
Hiding "My Expenses Calendar" in the cal app should be possible in most calendar app. The Google calendar app allows to deselect calendars in the navigation drawer, which cal app are you referring to?

**Comment by amilopowers** [comment]
Nexus 6P, Android 7.1.1.
I use the default calendar app. I wasn't sure if hiding would influence the app.

**Comment by mtotschnig** [comment]
I would had said, that hiding it should not have any impact, but will check again, and until then reopen.

**Comment by amilopowers** [comment]
Apparently it has one. Plans due to 25th of the month didn't work.

**Comment by mtotschnig** [comment]
Sorry for the late reply. Do the instance that did not work show up when you click on the plan to open the calendar dialog. If yes, they can be applied manually by long tapping on them.
If yes I have to investigate, if either the visibility in the calendar has an influence here, or if there is another reason, that would make the regular alarm that is responsible for check for pending plan instances not work.

**Comment by mtotschnig** [comment]
I do not own a Nexus device, but tested on the 7.1.1 emulator, and there hiding the calendar did not affect the correct working of the plan. My Expenses needs the calendar to be configured as Synced, but it does detect and fix this.

**Comment by mtotschnig** [comment]
There have been improvements on the way recurring instances are handled in the latest versions. Previously the mechanism was based on the id of the instance in the native calendar storage, and I found out that this id is not stable, causing probably many of the reported issues with this feature. I am closing this ticket at the moment. Please reopen if the problem can still be observed on the latest version.
