### ISSUE TITLE
Link of F-Droid no work

### ISSUE THREAD

**Issue by Lunovox** [mtotschnig/MyExpenses#354]
Your app for Android OS in repository of F-Droid is not work.
[My Expenses (Manage finances)](https://f-droid.org/app/org.totschnig.myexpenses)
How I can get an copy of your app to my Android OS?

**Comment by mtotschnig** [comment]
Are you referring to a link from that page? The link to the apk does work for me. But that is not the recommended way of installing the app. You need to install the F-Droid client app (https://f-droid.org/FDroid.apk) and then from within the F-Droid app you search for MyExpenses and install it. 
Do not hesitate to contact support@myexpenses.mobi if you have further questions.

**Comment by Lunovox** [comment]
The truth is I discovered the [F-Droid](https://f-droid.org/FDroid.apk) app was not allowed to install the [My Expenses](https://f-droid.org/app/org.totschnig.myexpenses) app because my repository was outdated.

Thanks for all. =)
