### ISSUE TITLE
Conversion between foreign and home currency

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#362]
This topic is brought up regularly by users, but we do not have a clear plan yet how it should be implemented. The idea is that it should be able to compare transactions of accounts with different currencies, for example in the distribution list it should be possible to have an aggregate across all accounts.
The problem is how to manage transaction rates: per transaction, per account, per time period?

**Comment by trmendes** [comment]
The app I used to use before MyExpenses would do it per account. You would define a main currency and this app was converting the account total expenses to this default currency showing both.

I would like to see a per transaction too so I could know the price I've payed for each item but I think this one would slow down the app :( so it could be something optional to be enabled/disabled in the settings activity.

It would be nice to see the values in the distribution too.

**Comment by keunes** [comment]
I would say: per transaction, but remembered throughout transactions (like a pre-filled setting with every new transaction that updates after every change), and possibly also making the remembering per account.

To explain why, I'll give my use case:
I'm visiting a friend some times that lives in a country with a different currency. When I'm there, I withdraw cash from the ATM, which my bank will credit on my regular account with a specific rate. Now, I just label that money as spent on 'holidays' without any further distinction. Of course we eat, visit stuff and take the bus and tram. Currently, I wouldn't make that differentiation. What I would do, however, if possible, is: add transfer in bank account (to my wallet account) in the foreign currency and in a later point check through online banking what rate the bank applied. Then when I spend money (create transactions in wallet) I will set the relevant currency and the transaction rate is automatically copied from what it last was.

UI
In effect there would be multiple currencies in one account possible, while one is still being the default. This would mean two extra fields are required (currency & rate) in the transaction/transfer/split window. I guess to avoid clutter when it's not needed, a 'holiday' setting could be introduced that shows/hides these fields in these views.

Remembering per account:
I can imagine that other use-cases might require a different set-up, mainly if someone uses multiple accounts. Say that you have a personal and family debit card, both with different banks that use different rates, it'll make less sense to remember one rate, but instead it could be remembered per transaction per account. Yet then if you make a transfer from both bank accounts, I wouldn't know how one would 'average' the two different rates for the spendings from the wallet account, though.

**Comment by woj-tek** [comment]
I would definitely love that feature (I'm currently utilising at least 3 currencies on the daily basis and it's a bit of a headache because my main account is in the different currency then the country I live for the time being).

So currently I defined an account in the currency that the account has and when I add transaction I... need to wait when it gets properly charged in my bank account, to put the actual value.
It would be great to be able to select per-transaction currency, enter paid value and mark the transaction as "to resolve" and then clear it in a couple of days when it's charged in the account, entering actual value charged in the currency of the account.

Also adding an option to make transfer between accounts in different currencies is kinda essential (withdrawing cash in ATM from account in currency A and then having cash in wallet in currency B).

I wouldn't say this would have to be "holiday mode" but it could be enabled in options and only visible when explicitly selected.

**Comment by mtotschnig** [comment]
@woj-tek Transfers between accounts in different currencies are already possible.

**Comment by woj-tek** [comment]
Right, my bad.

To address:
> The problem is how to manage transaction rates: per transaction, per account, per time period?

I would say that saving exchange rate per transaction is a must - those tend to change quite a lot and we need to persist exact record.
It would be helpful to have some current, average rates globally in the application, so for example when I add new transaction (to be resolved) in currency XYZ and my account is in ABC, it would take this current average exchange rate and deduct translated amount in ABC from the account so I would have at least a rough overview. Later on I can "revalidate" those transactions and put the exchange rate that my bank used to charge the card/account.

**Comment by klawdhfzasjhaa** [comment]
Maybe it can be done like in Financisto. You have a currency exchange rate provider and four fields are saved per transaction: amount, currency, original amount, original currency (which are also contains in exported CSV files). I tried it on several vacations and it was very convenient.

**Comment by mtotschnig** [comment]
Based on your suggestions, I am starting on this ticket with the following plan:

1. In Settings user can define home currency
2. Foreign currency accounts can define a default exchange rate with respect to home currency.
3. For every transaction it is possible to define an original amount + currency different from account currency.
4. In foreign currency accounts one can additionally define an equivalent amount in the home currency which overrides the amount that results from applying default exchange rate to account.

Probably I will postpone the downloading of exchange rates from online providers to a second iteration.

**Comment by mtotschnig** [comment]
I am releasing the implementation today on the Beta channel: https://plus.google.com/b/116736113799210525299/+MyexpensesMobi/posts/AYT8u2EQosF
