### ISSUE TITLE
Diferent Currencies

### ISSUE THREAD

**Issue by trmendes** [mtotschnig/MyExpenses#368]
I'm traveling and for each country I visit I create a new account because the currency changes. It would be nice to have the ability to see and set a main currency so my expenses could tell me the value of each transaction and the value I've spent in my main curren for each account. There is an app that do it well and you can use it as an example. It is an open source app too: "Financius - Expense Manager".

There is another nice feature in that app that would be nice to see in My Expenses. It is the way it does the distribution graph. It is just a list with the percentages in front of each category. Simple and no graphics only a nice UI.

**Comment by mtotschnig** [comment]
I close this, since it duplicates #362 . But many thanks for the pointer to Financius. Am checking it out.
