### ISSUE TITLE
UI bug: dropdown-menu-triangle persistant in split screen

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#378]
There is a triangle/arrow of the state dropdown menu that is persistan remains visible if the rest of the notes section is removed in favour of the split parts when number keyboard/pad is active (next to the FAB). See screenshots.
![screenshot_20170509-111028](https://cloud.githubusercontent.com/assets/11229646/25843726/8f028ee2-34a8-11e7-8a00-bc468e33f40a.png)
![screenshot_20170509-111022](https://cloud.githubusercontent.com/assets/11229646/25843727/8f034882-34a8-11e7-9a2c-119330f0d01d.png)

**Comment by mtotschnig** [comment]
Many thanks for the report. Fixed in next release
