### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by roxerqermik** [mtotschnig/MyExpenses#381]
- option to create projects (!)
- option to export distributions to HTML
- saved distributions for specific period, accounts
- generally expanded distributions (more types of charts)
- self-filling previously written comments in notes (in similar way to Google search engine)
- Dropbox synchronization

**Comment by keunes** [comment]
Hi @roxerqermik 
I think, to get any of this implemented, you should separate them into different issues and per item give a bit of background (why do you want it) and your view on implementation. If you do so, it also is possible for others to upvote your ideas (like I would for autocompletion for comments).

If I'm not mistaken (I currently don't have access to my phone), Dropbox synchronisation already exists.

**Comment by mtotschnig** [comment]
Dropbox synchronisation is not yet implemented, but issue defined in #371

**Comment by mtotschnig** [comment]
Issue for projects #151

**Comment by mtotschnig** [comment]
#146 is the issue for discussing enhancements to graphing data
