### ISSUE TITLE
Allow to limit number of local backups.

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#385]
Users request that MyExpenses automatically deletes old backups, only keeping the last n, where n is configurable via Settings.
Open questions: Is it of any value if more  sophisticated plans can be defined, e.g. keep 3 latest backups, and one for each week of the last month, one for the last 6 months?
Do we also need to offer the possibility to delete cloud synced backups together with local ones?

**Comment by klawdhfzasjhaa** [comment]
Advanced backup plans seem a good idea, but for the beginning a simple number of backup to be kept is enough in my opinion.

**Comment by woj-tek** [comment]
For me - advanced delete options are not that important (I would lean and say not at all) but having something basic like "keep only 3 last backups" would be kinda important (I just run into an issue where ccleaner reported that MyExpenses used hundreds of MBs...)

**Comment by niranjanpr** [comment]
Need an another feature of automatically deletes old backups in cloud as well, only keeping the last n, where n is configurable via Settings alongwith the local both having 2 settings separately for number of back-ups.

**Comment by mtotschnig** [comment]
@niranjanpr Version 3.3.9 will provide an implementation of this feature limited to local backups. I have created #968 for deleting backup from cloud and added it to the roadmap vote.
