### ISSUE TITLE
WebDAV Error: "URL doesn't exist on server"

### ISSUE THREAD

**Issue by stratmaster** [mtotschnig/MyExpenses#393]
When trying to add my webdav url (like this: https://diskstation.server.com:445/folder) the app throws this error: "URL doesn't exist on server" 

How can a webdav url like mentioned above be added?

Thank you!

**Comment by mtotschnig** [comment]
Could you tell me which webdav server you are using? My Expenses tries to establish if a resource exists by sending a HTTP HEAD request.

**Comment by stratmaster** [comment]
I'm using a Synology Diskstation (DS214) with its inbuilt webdav server.

**Comment by mtotschnig** [comment]
On the server does the folder that you reference in the URL exist, eg. a folder named "folder" for  https://diskstation.server.com:445/folder ?

**Comment by stratmaster** [comment]
Yes, of course. Even without "/folder" it doesn't work.

**Comment by mtotschnig** [comment]
I found the following report about Synology returning 404 for an empty folder: https://davdroid.bitfire.at/configuration/synology/ . Could you try create any random file in the folder before accessing it from My Expenses?

**Comment by stratmaster** [comment]
That doesn't work neither. And other folders I've tried already had some content before. Could it be because of the port number?

**Comment by mtotschnig** [comment]
I would not think so. Accessing Apache's DAV module with a port other than 80 works fine. Unfortunately I do not have access to a Synology device to debug this further.

**Comment by stratmaster** [comment]
Mh, what else could I try, do you have any other hints? Debbuging via [cadaver](http://www.webdav.org/cadaver/)?

**Comment by mtotschnig** [comment]
Are you able to monitor which requests your server receives, and what response it sends? If yes, it would be interesting to know what exactly is replies to the HEAD request, My Expenses tries in order to test if the folder exists.

**Comment by stratmaster** [comment]
Ok, I've send an email to Synology and waiting for response. In the meanwhile I've tried listening to events via chrome://net-internals/: This is the log for calling the WebDAV-Server via Browser. But I don't know, if this could be relevant for solving the issue (Do you know a tool for android to monitor these kind of traffic/ports?):

> 68338: URL_REQUEST
https://diskstation.example.com:5006/folder/
Start Time: 2017-08-30 09:04:42.515

> t=103180 [st=  0] +REQUEST_ALIVE  [dt=387]
                   --> priority = "HIGHEST"
                   --> url = "https://diskstation.example.com:5006/folder/"
> t=103180 [st=  0]    DELEGATE_INFO  [dt=18]
                     --> delegate_blocked_by = "NavigationResourceThrottle"
> t=103198 [st= 18]   +URL_REQUEST_DELEGATE  [dt=1]
> t=103198 [st= 18]      DELEGATE_INFO  [dt=1]
                       --> delegate_blocked_by = "uBlock Origin-Erweiterung"
> t=103199 [st= 19]   -URL_REQUEST_DELEGATE
> t=103199 [st= 19]    URL_REQUEST_START_JOB  [dt=1]
                     --> load_flags = 37120 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                     --> method = "GET"
                     --> url = "https://diskstation.example.com:5006/folder/"
t=103200 [st= 20]   +URL_REQUEST_START_JOB  [dt=365]
                     --> load_flags = 37120 (MAIN_FRAME_DEPRECATED | MAYBE_USER_GESTURE | VERIFY_EV_CERT)
                     --> method = "GET"
                     --> url = "https://diskstation.example.com:5006/folder/"
t=103200 [st= 20]      URL_REQUEST_DELEGATE  [dt=0]
t=103200 [st= 20]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=103200 [st= 20]      HTTP_CACHE_OPEN_ENTRY  [dt=0]
t=103200 [st= 20]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=103200 [st= 20]      HTTP_CACHE_READ_INFO  [dt=1]
t=103201 [st= 21]     +HTTP_STREAM_REQUEST  [dt=10]
t=103201 [st= 21]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                         --> source_dependency = 68340 (HTTP_STREAM_JOB_CONTROLLER)
t=103211 [st= 31]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                         --> source_dependency = 68341 (HTTP_STREAM_JOB)
t=103211 [st= 31]     -HTTP_STREAM_REQUEST
t=103211 [st= 31]      AUTH_SERVER  [dt=0]
t=103211 [st= 31]     +HTTP_TRANSACTION_SEND_REQUEST  [dt=0]
t=103211 [st= 31]        HTTP_TRANSACTION_SEND_REQUEST_HEADERS
                         --> GET /home/ HTTP/1.1
                             Host: diskstation.example.com:5006
                             Connection: keep-alive
                             Authorization: Basic [24 bytes were stripped]
                             Upgrade-Insecure-Requests: 1
                             User-Agent: [...]
                             Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
                             Accept-Encoding: gzip, deflate, br
                             Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
                             Cookie: [176 bytes were stripped]
t=103211 [st= 31]     -HTTP_TRANSACTION_SEND_REQUEST
t=103211 [st= 31]     +HTTP_TRANSACTION_READ_HEADERS  [dt=352]
t=103211 [st= 31]        HTTP_STREAM_PARSER_READ_HEADERS  [dt=352]
t=103563 [st=383]        HTTP_TRANSACTION_READ_RESPONSE_HEADERS
                         --> HTTP/1.1 403 Forbidden
                             Date: Wed, 30 Aug 2017 07:04:41 GMT
                             Server: Apache
                             Content-Length: 207
                             Keep-Alive: timeout=5, max=100
                             Connection: Keep-Alive
                             Content-Type: text/html; charset=iso-8859-1
t=103563 [st=383]     -HTTP_TRANSACTION_READ_HEADERS
t=103563 [st=383]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=103563 [st=383]      HTTP_CACHE_WRITE_DATA  [dt=0]
t=103563 [st=383]      HTTP_CACHE_WRITE_INFO  [dt=0]
t=103564 [st=384]     +URL_REQUEST_DELEGATE  [dt=1]
t=103564 [st=384]        DELEGATE_INFO  [dt=1]
                         --> delegate_blocked_by = "uBlock Origin-Erweiterung"
t=103565 [st=385]     -URL_REQUEST_DELEGATE
t=103565 [st=385]   -URL_REQUEST_START_JOB
t=103565 [st=385]   +URL_REQUEST_DELEGATE  [dt=1]
t=103565 [st=385]      DELEGATE_INFO  [dt=1]
                       --> delegate_blocked_by = "NavigationResourceThrottle"
t=103566 [st=386]   -URL_REQUEST_DELEGATE
t=103566 [st=386]    HTTP_TRANSACTION_READ_BODY  [dt=0]
t=103566 [st=386]    HTTP_CACHE_WRITE_DATA  [dt=0]
t=103567 [st=387]    URL_REQUEST_JOB_FILTERED_BYTES_READ
                     --> byte_count = 207
t=103567 [st=387]    HTTP_TRANSACTION_READ_BODY  [dt=0]
t=103567 [st=387]    HTTP_CACHE_WRITE_DATA  [dt=0]
t=103567 [st=387] -REQUEST_ALIVE

**Comment by mtotschnig** [comment]
I was thinking about logging on your Synology device. I had a quick look into Synology's online demo and there seems to be an option to log Webdav requests in the Webdav settings. You could switch that one, and observe what is records when MyExpenses talks to it. I can also send you a version that adds more logging to MyExpenses.

**Comment by stratmaster** [comment]
The Log-Option is already activated. But my "Login activities" via MyExpenses are not shown there. Could you please send me the MyExpenses-Version for debugging? I'll give it a try.

**Comment by mtotschnig** [comment]
Please contact me via the app's feedback settings, so that I can send it to you.

**Comment by mtotschnig** [comment]
Synology does not respond to HEAD request in the same way Apache mod_dav or OwnCloud/NextCloud do. 2.9.1 (1d8a02ab3376d13f699f03b2b61bf71b0c10886d ) implements a workaround that seems to work.
