### ISSUE TITLE
Export produces invalid CSVs

### ISSUE THREAD

**Issue by IBPX** [mtotschnig/MyExpenses#399]
CSV exporting uses semicolon ";" delimiters, which is [non-standard](https://tools.ietf.org/html/rfc4180) and should not be used. CSVs (_comma_ separated value files) should always use comma "," delimiters.

Seems to be handled in [`myExpenses/src/main/java/org/totschnig/myexpenses/export/Exporter.java`](https://github.com/mtotschnig/MyExpenses/blob/master/myExpenses/src/main/java/org/totschnig/myexpenses/export/Exporter.java#L136-L303).

How it currently exports:

```
"Something";"A Column";"Untitled"
"100";"John Doe";"Gas money, I think."
```

How it should export:

```
"Something","A Column","Untitled"
"100","John Doe","Gas money, I think."
```

**Comment by mtotschnig** [comment]
As RF4180 says, "there is no formal specification in existence", and comma is only the most widely used. Thus I strongly disagree with the statement, that the date produced is "invalid" . It might make sense though to make the delimiter configurable.
The advantage of semicolon as a delimiter is that if comma is used as decimal separator, numbers do not need to be quoted, and I suspect that some programs might treat quoted numbers differently, e.g. importing them as text instead of number.

**Comment by IBPX** [comment]
The RFC exists _because_ there was no formal specification. It has become the de facto standard, and should always be followed by default, to aid compatibility and interchange between programs. CSVs are a mess, because so many programs make non-standard CSVs. The RFC was made solely because the situation was such a mess.

Most programs follow that RFC, and it would serve well to follow it as well, at least by default. CSVs use commas as delimiters by default in almost every program, with the exception of certain versions of Excel. Everywhere else, the comma is standard.

I think the produced data is invalid, because you call the file a CSV, which is clearly false; it is not a **comma** separated value file if it isn't comma separated.

> The advantage of semicolon as a delimiter is that if comma is used as decimal separator, numbers do not need to be quoted, and I suspect that some programs might treat quoted numbers differently, e.g. importing them as text instead of number.

A semicolon is being used, and numbers are already being quoted anyway, so that argument holds no bearing. I have not come across a single program which treats a quoted number as text, as most just detect upon opening the file. I have, on the other hand, come across programs which do not work because of the use of a non-standard delimiter instead of a comma.

**Comment by mtotschnig** [comment]
Numbers (transaction amounts) are not quoted in My Expenses CSV output.

**Comment by IBPX** [comment]
I misread the file, and have edited my post. Sorry about that.

The rest still stands. I haven't come across a program which treats quoted numbers as text.

**Comment by klawdhfzasjhaa** [comment]
As @mtotschnig said, it might be a good idea to add more options to the export function like field separator, decimal separator and time period. I was very happy with the export function of [Financisto](https://play.google.com/store/apps/details?id=ru.orangesoftware.financisto). 

Maybe it would be even better to support exporting in more advanced and flexible standards like JSON and XML.

**Comment by metal450** [comment]
+1 vote for this. The CSVs it exports can't be easily/directly opened in Excel - you have to launch the software and then explicitly import the data, explaining to it to use the nonstandard delimiter.  Makes it much, much more cumbersome than opening CSVs exported by other apps, in which you just double-click & Excel knows what to do.

(Also, for what it's worth, if you prefer to use a nonstandard delimiter in the interim - as I know that making it configurable would take a bit more work - Excel seems to know how to handle tabs out-of-the-box. Semicolons, however, it does not. aka you can double-click a csv separated by tabs, and it will figure out how to parse it).
