### ISSUE TITLE
Ads in F-droid version

### ISSUE THREAD

**Issue by Bubu** [mtotschnig/MyExpenses#403]
Some user reported that they are seeing ads in the newly released version in f-droid. While that in itself is fine (if done with FOSS software) it should be labeled as such in the repository.

I could not reproduce the ads myself, but I also saw this commit (https://github.com/mtotschnig/MyExpenses/commit/7131497ba52cb0016ff4f912e0c886086ff2f111), so now I'm, not sure what's the status of this. Can you clarify?

**Comment by mtotschnig** [comment]
My Expenses uses https://github.com/pubnative/pubnative-android-sdk (licensed under MIT licence). Ads are only shown five days after installation. Could you tell me how to labe? I will then create a pull request with updated metadata for https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.totschnig.myexpenses.txt

**Comment by Bubu** [comment]
@mtotschnig Thanks for your response. It's just adding `AntiFeatures:Ads` at the top of the file.

Here is the documentation on these: https://f-droid.org/docs/Build_Metadata_Reference/#AntiFeatures

It's probably a good idea to explain in the description that purchasing the contrib/extended version disables the ads. (I assume that's the case anyway.)

**Comment by mtotschnig** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2542

**Comment by Bubu** [comment]
Thanks, can be closed then.
