### ISSUE TITLE
Adding shortcuts to non-default launchers in recent Android

### ISSUE THREAD

**Issue by Nadrieril** [mtotschnig/MyExpenses#409]
I recently updated my phone to Oreo, and My Expenses now tells me to "long-tap the app icon on the home screen" to add a shortcut. The problem I have that I don't use the default android launcher (I actually use a non-default ROM) and this option is not supported by my launcher (Trebuchet).
It used to work quite well with this launcher in previous versions.

Would it be possible to add back a way to add home screen shortcuts via the app in recent Android versions ?

**Comment by mtotschnig** [comment]
Coincidentally I have just added #408 today. The question is though if Trebuchet will handle pinned shortcuts. We will need to find out.

**Comment by Nadrieril** [comment]
I don't know what those are but I'd be happy to test that

**Comment by mtotschnig** [comment]
Those can be created by the app, compared to conventional shortcuts that are created by the user. I plan to make use of this feature in one of the next versions.

**Comment by danielb7390** [comment]
Having same issue with MiUi (redmi note 5)

**Comment by Nadrieril** [comment]
Trebuchet now supports those shortcuts, so I have no problem anymore. Should I close the issue or leave it open if it affects other people ?

**Comment by mtotschnig** [comment]
@danielb7390 Is this still a problem for you? Can you identify the launcher used on your device?

**Comment by Nadrieril** [comment]
I'll close this now, anyone feel free to open a new issue if this affects you.
