### ISSUE TITLE
Compatiblity with HomeBank Destop App

### ISSUE THREAD

**Issue by damascene** [mtotschnig/MyExpenses#412]
I've tested some accounting software that are available as free software, I've found that HomeBank is closer to the way MyExpenses works. I think those two apps could be so useful for desktop and mobile telephone users if they could enhance support for each other.

I've opened a bug report on the HomeBank for this: https://bugs.launchpad.net/homebank/+bug/1725119

**Comment by mtotschnig** [comment]
My Expenses has QIF and CSV export, Homebank has QIF and CSV import. Could you explain what type of enhanced interoperability you have in mind?

**Comment by nr458h** [comment]
A possibility could be to make the sync-backend compatible.

I started already several times with im- and export but it is not that handy for everyday useage.

**Comment by mtotschnig** [comment]
Since on Homebank's side, interest has been declined, I am closing this here as well.
