### ISSUE TITLE
Split entry to multiple categories

### ISSUE THREAD

**Issue by woj-tek** [mtotschnig/MyExpenses#416]
So quite often I go to some supermarket, buy items from mixed categories and pay with a card. Thus I always add single item to MyExpenses with the amount from the bill (and it matches my bank statement so it's easier to organise).

However, the other day it just struck me, that it doesn't play well with categories, because on that bill I could have included groceries, cosmetics and even some house bills.
Thus - it would be a great addition to allow something like "sub entry" where one could specify partial sums and assign them to different categories.

**Comment by mtotschnig** [comment]
My Expenses has split transactions since #38. When you create a new transaction, you need to switch to "New split transaction" through the dropdown in the action bar. I plan to improve discoverability of this feature.

**Comment by woj-tek** [comment]
mea culpa - you are right.

If I may add - it would be nice to add something like "convert to split transaction" for older items where it would populate the fields accordingly (and create default entry for the split category with 100% of the amount of the original category for example).

**Comment by mtotschnig** [comment]
This is also implemented ;-) since #190 . Available through long press on a transaction.

**Comment by woj-tek** [comment]
OK, at this point I capitulate and give a huge 👍 to improving discoverability of the features ;-)

One final note (this time I searched more diligently) - converting transaction to split is a one way operation? And the "payee" seems to be missing (but that may be a candidate for a different issue)

**Comment by mtotschnig** [comment]
Sorry for the late reply. Yes, converting transaction to split is currently one way. Unsplit has been brought up: #323 . 
The payee should not be missing. Depending on the screen size, you might have to scroll the upper half of the screen in order to reveal it. This should be improved, as stated in #391 .
