### ISSUE TITLE
A problem with distribution graphs for subcategories

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#438]
Distribution graphs for subcategories seems to be wrong all the way. If you have some transactions which belong to main categories instead of their subcategories, they are displayed wrongly in distribution screen (not included, whereas they should be displayed as "unclassified"). Please see the attached images.
![scr_20171212_130947](https://user-images.githubusercontent.com/19515542/33869897-df59418e-df3d-11e7-8337-621aac0fe4f9.png)

**Comment by mtotschnig** [comment]
Thank you for the report. This is a known limitation, reported in #246 .
