### ISSUE TITLE
consider making the app compatible with upcoming Librem 5 privacy & security focused linux phone

### ISSUE THREAD

**Issue by takiainen** [mtotschnig/MyExpenses#442]
https://puri.sm/shop/librem-5/

**Comment by mtotschnig** [comment]
A quick research on the phone, did not reveal any information about an Android compatibility layer as part of the phone's OS. So I am not sure what you mean by "making the app compatible"?

**Comment by mtotschnig** [comment]
If the Librem-5 in the future supports running Android applications, My Expenses should run without any issue.
If it does not, writing a native Librem-5 app that behaves like My Expenses would be a new project.
