### ISSUE TITLE
checkbox shared expense?

### ISSUE THREAD

**Issue by ilf** [mtotschnig/MyExpenses#444]
I have a habit to take pictures of receipts. I share expenses with other people though (like a meal in a restaurant), so the sum I enter is a different value than the one in the picture. Would it be overkill to add a checkbox "shared expense", so I can remember (and filter) this? Best

**Comment by mtotschnig** [comment]
I think this use case would be covered nicely with #142 , wouldn't it?

**Comment by ilf** [comment]
That would be very cool indeed!
