### ISSUE TITLE
Execute recurring transactions in advance

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#445]
Currently recurring transactions are added to the database at the day of charge. User might wish to have them appear in advance.
This could either be implemented by an option that would apply to all plans or on a per-plan basis.

**Comment by FlorianSteenbuck** [comment]
Jep it is anoying for planing the next month. I think a time frame setting would be the best choice to solve this. In best case as own timeline fragment that you can resize and move.

**Comment by mtotschnig** [comment]
@FlorianSteenbuck What exactly do you mean by timeline fragment? A slider control that allows to set how many days in advance the entry should be created?

**Comment by FlorianSteenbuck** [comment]
Something like this:
![ascii timeline](https://i.imgur.com/HaspGK1.png)
\+ for zoom in 
\- for zoom out
(simple unit change years, months, weeks, days, hours)
but a slider can also do the job

**Comment by mtotschnig** [comment]
I am afraid I do not get how  the control you suggest would work. What type of value does it allow to set, and how should this value be applied?
What I had in mind was that when creating the plan you would be able to set how many days in advance instances are created. This value would need to have a reasonable upper limit (e.g. 30 to 60 days), in order to prevent lookups in the calendar storage that are too costly. There would be no need for a fancy control, either a number text input, or a simple slider would work.

**Comment by augras** [comment]
I, to plan the month maybe just execute recurring transaction of the month around the 20 of the month before : for june by example, all the recurring transactions are execute on the 20 of may ?
Or maybe when a recurring transction is created complete a field to execute it x days in advance ?
Philippe
