### ISSUE TITLE
Sync doesn't work on MIUI

### ISSUE THREAD

**Issue by balek** [mtotschnig/MyExpenses#450]
I'm adding a new sync backend, choosing accounts to sync, than nothing happens. No new files on a server, no subitems in the new backend's list. I can see such requests in server's access log:
46.188.7.106 - s [18/Feb/2018:22:49:23 +0300] "OPTIONS /remote.php/webdav/accounting/ HTTP/2.0" 200 930 "-" "okhttp/3.9.1"
46.188.7.106 - s [18/Feb/2018:22:49:23 +0300] "PROPFIND /remote.php/webdav/accounting/ HTTP/2.0" 207 1052 "-" "okhttp/3.9.1"
Version 2.8.7 from F-Droid.

**Comment by mtotschnig** [comment]
Currently, once you have added the backend, My Expenses does not trigger the first sync right away, but it should start at the latest when you enter new data into one account, or after the configured sync frequency. You can also manually trigger the sync by long clicking on a backend and selecting "Sync now".
If it is still not working, could you switch on debug log from the settings, and inspect the contents of SyncAdapter-latest.log in Android/data/org.totschnig.myexpenses/files/logs ?

**Comment by balek** [comment]
I don't know why, but all logs are empty... I've prepared a screen record: https://cloud.balek.ru/s/2PMq4M8S7HDHwME

Debug is enabled, but all logs have 0B size.

**Comment by mtotschnig** [comment]
As I mentioned, after adding the backend, could you long press and select "Sync now". If you copy the logs to your computer, do they still have 0B size?

**Comment by balek** [comment]
> `As I mentioned, after adding the backend, could you long press and select "Sync now".`
Sorry, I have forget to do it on video. It does nothing. Logs are still empty, even on computer.

It prompts me, that problem could be not in NextCloud, but in MIUI firmware. I tried to sync with Dropbox. Everything is the same: account sublist, logs and dropbox are empty. Is there any other place, where I can look for logs?

Another possible reason is the trial version of syncing. Are you sure it's in a working state? Maybe some bug get into free version and was not observed before?

**Comment by mtotschnig** [comment]
Could you tell more about that prompt about MIUI? I have tested sync with trial version recently and did not find any issue.

**Comment by balek** [comment]
I have finally found a solution. It really was MIUI specific problem. I had to enable some "Autostart" option in system settings for My Expenses. Than sync started working. Thank you for your help.

**Comment by mtotschnig** [comment]
@balek Thanks for reporting this valuable information!

**Comment by mtotschnig** [comment]
@balek I am receiving reports from users on Xiaomi devices about sync not working, could you describe in detail the path how you navigate to that option, and eventually provide a screenshot?

**Comment by balek** [comment]
Hi! Path to application settings differs a little between MIUI versions. But the idea is the same: enable Autostart option for My Expenses.

Settings -> Installed apps -> My Expenses -> Autostart

![Settings](https://user-images.githubusercontent.com/1445794/45697811-46e55a00-bb6f-11e8-89a5-2ac24e07a646.png)
![Installed apps](https://user-images.githubusercontent.com/1445794/45697816-4a78e100-bb6f-11e8-9067-0fa6e5775c88.png)
![My Expenses](https://user-images.githubusercontent.com/1445794/45697824-4cdb3b00-bb6f-11e8-8e67-cf6bd2b5b5fe.png)

**Comment by mtotschnig** [comment]
@balek Thanks a lot!

**Comment by danielb7390** [comment]
This just fixed my problem. Didn't have logs, even connected via adb to see logcat and nothing.
You might want to consider to add a warning when enabling the sync for the first time to avoid more confused users!

**Comment by mtotschnig** [comment]
@danielb7390 Thank you for your excellent suggestion. I'd need to find out how to identify devices that are hit by this problem. Could you send me a feedback request from the app settings, or post some information about your device here?

**Comment by danielb7390** [comment]
I think this is what you asked?
Don't think there's much useful here other than the brand, i guess you could match by brand that would be enough. 
Or maybe more complicated this would help also: https://stackoverflow.com/questions/47610456/how-to-detect-miui-rom-programmatically-in-android

`APP_VERSION:3.0.5.1 (revision 384) 20190917-0925 PLAY com.android.vending
ANDROID_VERSION:9
BRAND:xiaomi
MODEL:Redmi Note 5
CONFIGURATION:{"colorMode":5,"densityDpi":440,"extraConfig":" themeChanged=0 themeChangedFlags=0","fontScale":1,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en","mcc":268,"mnc":1,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":714,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":392,"seq":174,"smallestScreenWidthDp":392,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":false,"windowConfiguration":"{ mBounds=Rect(0, 0 - 1080, 2030) mAppBounds=Rect(0, 0 - 1080, 2030) mWindowingMode=fullscreen mActivityType=standard}"}
LICENCE: EXTENDED (GPA.3398-2169-9898-06437)`

**Comment by raffaem** [comment]
Is this called "Pause app activity if unused" now, and must be __unchecked__ rather than checked?

**Comment by mtotschnig** [comment]
@raffaem Thanks for the question and sorry for the late reply. Since I do not own a recent Xiaomi device, I do not know. If you had any success by configuring the app via this option, would be great to learn about your experience.
