### ISSUE TITLE
Separate categories of income and expenses

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#451]
Is it a good idea? I'd love to have it implemented. The categories are not separated for income and expenses, which make it hard to effectively manage cash flow.

**Comment by DSIW** [comment]
The sign of amount can be used to recognize it. If the amount is positive, the transaction is income. If the amount is negative, the transaction is expense.

**Comment by mtotschnig** [comment]
@hieu-van I am closing this, since its is a duplicate of #212 . But would you mind explaining how it helps managing cash flow?
