### ISSUE TITLE
Sample categories are too complicated

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#454]
Some of them are even duplicate

**Comment by mtotschnig** [comment]
I agree that the sample categories as defined on Transifex are far from being optimal. Originally IIRC they were taken from Grisbi. But it also far from obvious how to arrive at a better set.
My Expenses itself does not rely on the same set for all languages, so it would be possible to define different categories for each language/country, that would make sense for the specific cultural context. For example, Vietnamese is defined in https://github.com/mtotschnig/MyExpenses/blob/master/myExpenses/src/main/res/raw/cat_vi.xml

**Comment by hieu-van** [comment]
Closed this since they are not as complicated as I initially thought. Basically they are good enough for everyday use, just some of them need to be modified to be suitable for each use case.
