### ISSUE TITLE
Download exchange rates

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#458]
After implementation of  #362 we should also provide downloading of exchange rates from online services.

**Comment by hieu-van** [comment]
Some suggestions: OpenExchangeRates, currencylayer and Fixer

**Comment by metal450** [comment]
+1 vote for this. I've spent the last few hours trying dozens of expense trackers, in search of one that can handle per-transaction currencies. This seems to be the only one :) However, needing to manually lookup the exchange rate & enter a value twice for each transaction (home currency & 'actual' currency) is a bit cumbersome. It would be great if we could enter just the 'original amount' (aka currency in which it was paid) and it would calculate/fill out the (equivalent) "Amount," based on exchange rate lookup :)
