### ISSUE TITLE
Empty data on tell a friend feature on Myexpenses 

### ISSUE THREAD

**Issue by onos1** [mtotschnig/MyExpenses#462]
#### Expected behavior
After seeing the app is of great help to me,  I decided to share it to my friends to download and install it by using the tell a friend feature, I expected after using any share option either whatsapp, text messages, click to copy will make me to be able to share a link to download it from play store, F-droid or maybe a desired site by the developer. 

#### Actual behavior
After using the tell a friend feature I found out that there is no data to share using the feature, tried to copy, but it was unable paste any data. 

#### How to reproduce
- download myexpenses [here](https://f-droid.org/repository/browse/?fdid=org.totschnig.myexpenses)

- you can explore the app If you wish 

- try using the tell a friend feature 

- try to copy and paste, share via whatsapp  or text messages 

* mobile : Infinix  note 4
* Operating system: android 7.0
* app version 2.8.8.1

#### Recording Of The Bug
A video to display the bug 
https://youtu.be/iBwPDp9lLew

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/empty-data-on-tell-a-friend-feature-on-myexpenses">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mtotschnig** [comment]
Many thanks for reporting. A fix will be included in next release.
