### ISSUE TITLE
incompatible API use in your app.

### ISSUE THREAD

**Issue by jay2013** [mtotschnig/MyExpenses#463]
API "<android.provider.DocumentsContract: java.lang.String getDocumentId(android.net.Uri)>" is added into SDK since level 19, However, it seems that you app could reach this api use when it run on mobile with level under 19.

<android.provider.DocumentsContract: java.lang.String getDocumentId(android.net.Uri)> called in <org.totschnig.myexpenses.util.io.FileUtils: java.lang.String getPath(android.content.Context,android.net.Uri)> on line 291 not in level [16, 17, 18, 15]
the reachable path is ::
<org.totschnig.myexpenses.activity.MyExpenses: boolean dispatchCommand(int,java.lang.Object)>
		--><org.totschnig.myexpenses.util.AppDirHelper: org.totschnig.myexpenses.util.Result checkAppDir(android.content.Context)>
		--><org.totschnig.myexpenses.util.io.FileUtils: java.lang.String getPath(android.content.Context,android.net.Uri)>
               --> <android.provider.DocumentsContract: java.lang.String getDocumentId(android.net.Uri)>

please help to check it. 

other similar bugs also list here:
BUG: <android.provider.DocumentsContract: boolean isDocumentUri(android.content.Context,android.net.Uri)> called in <org.totschnig.myexpenses.util.io.FileUtils: boolean isDocumentUri(android.content.Context,android.net.Uri)> on line 327 not in [16, 17, 18, 15]
all reachable paths:
	reachable path 1:
		--><dummyMainClass: void dummyMainMethod(java.lang.String[])>
		--><org.totschnig.myexpenses.activity.MyPreferenceActivity: boolean onOptionsItemSelected(android.view.MenuItem)>
		--><org.totschnig.myexpenses.activity.ProtectedFragmentActivity: boolean onOptionsItemSelected(android.view.MenuItem)>
		--><org.totschnig.myexpenses.activity.MyExpenses: boolean dispatchCommand(int,java.lang.Object)>
		--><org.totschnig.myexpenses.util.AppDirHelper: org.totschnig.myexpenses.util.Result checkAppDir(android.content.Context)>
		--><org.totschnig.myexpenses.util.io.FileUtils: java.lang.String getPath(android.content.Context,android.net.Uri)>
		--><org.totschnig.myexpenses.util.io.FileUtils: boolean isDocumentUri(android.content.Context,android.net.Uri)>

BUG: <android.provider.DocumentsContract: java.lang.String getDocumentId(android.net.Uri)> called in <org.totschnig.myexpenses.util.io.FileUtils: java.lang.String getPath(android.content.Context,android.net.Uri)> on line 258 not in [16, 17, 18, 15]
all reachable paths:
	reachable path 1:
		--><dummyMainClass: void dummyMainMethod(java.lang.String[])>
		--><org.totschnig.myexpenses.activity.MyPreferenceActivity: boolean onOptionsItemSelected(android.view.MenuItem)>
		--><org.totschnig.myexpenses.activity.ProtectedFragmentActivity: boolean onOptionsItemSelected(android.view.MenuItem)>
		--><org.totschnig.myexpenses.activity.MyExpenses: boolean dispatchCommand(int,java.lang.Object)>
		--><org.totschnig.myexpenses.util.AppDirHelper: org.totschnig.myexpenses.util.Result checkAppDir(android.content.Context)>
		--><org.totschnig.myexpenses.util.io.FileUtils: java.lang.String getPath(android.content.Context,android.net.Uri)>

DongjieHe

**Comment by mtotschnig** [comment]
both examples are safe because the following  expression makes sure that DocumentsContract.isDocumentUri is never called below kitkat:
`isKitKat && DocumentsContract.isDocumentUri(context, uri);`
 Since FileUtils#isDocumentUri returns false below Kitkat, also in Method getPath method getDocumentId will never be reached below Kitkat

**Comment by jay2013** [comment]
Thanks very much, and sorry for disturbing you.
