### ISSUE TITLE
another incompatible API use bug.

### ISSUE THREAD

**Issue by jay2013** [mtotschnig/MyExpenses#464]
Hi, this is also an incompatible API use bug: <android.app.KeyguardManager: android.content.Intent createConfirmDeviceCredentialIntent(java.lang.CharSequence,java.lang.CharSequence)> is added into 
SDK since level 21, but it is reachable on device with level 19 or 18.

BUG: <android.app.KeyguardManager: android.content.Intent createConfirmDeviceCredentialIntent(java.lang.CharSequence,java.lang.CharSequence)> called in <org.totschnig.myexpenses.activity.ProtectedFragmentActivity: void confirmCredentials(int,org.totschnig.myexpenses.dialog.DialogUtils$PasswordDialogUnlockedCallback,boolean)> on line 264 not in [16, 17, 18, 19, 15]

reachable path: 
--><org.totschnig.myexpenses.activity.MyExpenses: void onResume()>
		--><org.totschnig.myexpenses.activity.ProtectedFragmentActivity: void onResume()>
		--><org.totschnig.myexpenses.activity.ProtectedFragmentActivity: void confirmCredentials(int,org.totschnig.myexpenses.dialog.DialogUtils$PasswordDialogUnlockedCallback,boolean)>
                --><android.app.KeyguardManager: android.content.Intent createConfirmDeviceCredentialIntent(java.lang.CharSequence,java.lang.CharSequence)>

please help to check. Thanks very much.

Dongjie He

**Comment by mtotschnig** [comment]
There is the check `Utils.hasApiLevel(Build.VERSION_CODES.LOLLIPOP)` preventing this method being called on lower API levels

**Comment by jay2013** [comment]
Sorry for disturbing you.
Thanks anyway.
