### ISSUE TITLE
Template from New transaction

### ISSUE THREAD

**Issue by suemari** [mtotschnig/MyExpenses#465]
Only open templates from account screen? I can't find templates from new transaction screen.
I usually use New transaction shortcut from Home screen.
Sometimes I wanna use template but always have to open again account screen to find template icon.
Can you add templates icon on New transaction screen? It's more useful.
Thanks!

**Comment by mtotschnig** [comment]
I am wondering if adding a menu which opens a submenu with template names is even more useful?

**Comment by suemari** [comment]
Wow! Sounds great! Yes, more useful ^^
