### ISSUE TITLE
Restore (zip) function not working!!!

### ISSUE THREAD

**Issue by fabianmani** [mtotschnig/MyExpenses#470]
#### Expected behavior
I expected after exporting successfully my database and preferences, I'd be able l restore the data once I click on restore (zip) function. 

#### Actual behavior
When I clicked on the restore (zip) to restore my backed up database and preferences, it shows "please provide a file of type zip" even when the exported file is in the zip file. Instead of restoring the file it extracts the file. 

#### How to reproduce
* Download and open the app.
* create expenses and budget, go settings and back up your database and preferences
* Click on the 'restore (zip) and select the backed up file, and try restoring. 

* Device: Tecno K7
* Operating system: Android 7.0
* App Version: 2.8.9.1

#### Recording Of The Bug
https://youtu.be/sJqA-OS4IxY

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/restore-zip-function-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mtotschnig** [comment]
Actually this is a usability problem of the Android file selector, it has been reported in #423. When you click on the ZIP file, it shows you the content of the archive, but My Expenses needs the whole ZIP file. So what you need to do, is long press on the ZIP file and then click on "Open". As mentioned in #423 we should help the user by explaining how to select the ZIP file.
