### ISSUE TITLE
Templates don't fill in the category anymore

### ISSUE THREAD

**Issue by lukoGit** [mtotschnig/MyExpenses#474]
Since the last upgrade from f-droid, the templates always leave the category field empty. 
Possible workaround is to enter the same category again before saving a transaction.

**Comment by mtotschnig** [comment]
Thank you for the report. In the meantime, F-Droid has picked up version 2.9.0.1 where the bug should be fixed.

**Comment by lukoGit** [comment]
ah sorry, did not see that - thanks for the fast fix!
