### ISSUE TITLE
Ability to add user-defined currencies

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#475]
Hi Michael,
I know this feature is perhaps not so important but for example, in Asia, some countries use different measurement for precious metals (e.g. Tael). Would consider implementing it?

**Comment by mtotschnig** [comment]
Thanks you for the suggestion. This is definitely something on the roadmap, since it is essentially a more generalized, and hence more useful version of #390 .

**Comment by mtotschnig** [comment]
Duplicate of #264
