### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [mtotschnig/MyExpenses#477]
Hello, @mtotschnigI want to contribute in "MyExpenses" so i  want to designed a new logo for "MyExpenses" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by mtotschnig** [comment]
@abdulmalikkhan655  Thank you for your kind offer. In general, we are satisfied with the current one. Could you tell me, why you think a new one is needed, and what is the concept behind your new version?
