### ISSUE TITLE
Widget not automatically updated after scheduled transactions

### ISSUE THREAD

**Issue by fantasio31** [mtotschnig/MyExpenses#479]
While scheduled transactions are correctly processed in the app, widget is not automatically updated when the scheduled transaction has been taken into account.
I have to change the displayed account and to come back to the expected one to display the correct balance.
This issue does not appear with manual transactions.

May be it is linked to my android ROM, but if anyone has a solution, it is welcomed :).

My phone:
  Model: Xiaomi Redmi3
  ROM: MIUI 9 Global Beta

**Comment by mtotschnig** [comment]
Unfortunately I am not able to reproduce the behaviour on devices available to me.

**Comment by fantasio31** [comment]
I have changed my device and did not face thé issue again.

I close this bug.
