### ISSUE TITLE
Make transactions entered before 12:00 visible again

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#486]
With the possibility to hide the date field on the transaction form, the following problem was introduced: Transactions are created with the time set to 12:00. Since the current balance ignores transactions from the future, user does not see that the transaction he just added gets reflected.
Two solutions:
1) Transactions are create with current time.
2) Current balance included transactions until the end of the day.

1 is the easier, maybe more natural solution. But, the idea of the original design of creating all transactions at 12:00 was that transactions would more easily stay at the same day if the user switches timezones. But probably this is not that important.

**Comment by woj-tek** [comment]
Wouldn't using LocalDateTime solve the issue? In that case timezone is irrelevant so even if someone would switch timezone the entry would be pinned to the same date?

**Comment by mtotschnig** [comment]
@woj-tek My Expenses currently stores dates as timestamps, i.e. number of seconds since unix epoch (1.1.1970). You are right that switching to storing only local date time would solve that issue, but would have impact on many of the date calculations in the app, e.g. for grouping, and I am currently reluctant to open that box.
