### ISSUE TITLE
Error changing date one month back

### ISSUE THREAD

**Issue by claudiofus** [mtotschnig/MyExpenses#492]
Hi, I'm using the paid version of the app and I found a bug. 
Steps to reproduce:
1. On "Cash" type of wallet create an expense dated 02/07/2018 for example
2. After the save, change date to 02/06/2018

Now the input text with date doesn't refresh so nothing change if we save.

**Comment by mtotschnig** [comment]
Many thanks for the report. This will be fixed in next release. As a temporary workaround, change the date first to any other day of month 06. Then you will be able to set 02/06/2018.
