### ISSUE TITLE
A split transaction is counted twice in transaction list in history report

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#493]
i.e. App calculates not only amount of each split transactions but also their split parts, which in turn results in split tx being counted twice

**Comment by mtotschnig** [comment]
Could you please specify which report you are referring to?

**Comment by hieu-van** [comment]
Updated

**Comment by mtotschnig** [comment]
Unfortunately I am not able to confirm that bug. After a fresh install I created two split transactions of value 50 € each. History chart correctly reports 100 € total. Could you prepare data that shows the problem and send an export to support@myexpenses.mobi ?

**Comment by hieu-van** [comment]
@mtotschnig I've PM-ed you about the bug, please check!

**Comment by mtotschnig** [comment]
I was able to reproduce the problem. It appears not on the history screen itself, but in the transaction list dialogue that opens when you click on an entry.

**Comment by hieu-van** [comment]
Confirmed: fix works
