### ISSUE TITLE
Add a budgeting option for categories in each month/year

### ISSUE THREAD

**Issue by primeapple** [mtotschnig/MyExpenses#494]
Hey @mtotschnig ,
first of all, I really love this app. I think it's the most complete and yet simple expense tracker, that is also open source.

Nevertheless I have a little suggestion:
Mabye you know the Software YNAB (You Need A Budget). The big point in this expense tracker is, that you assign every expense to a budget. So they basically have budget categories (similar like the current categories in your app) and each of these categories have a limit. So at the start of the month you think about how much money you want to spend on clothes, set this as a limit and go with it. You are always able to see, how much you are over or before the limit. It's important, that you can change budgets on the fly, if something changes (for example your pc breaks and you need a new one right now). There are also yearly budgets (holiday, presents, ...). The last important thing is, that when you set your budgets, the sum of all of them should be the income of your last month (minus potential savings).

I know there is Issue #127 (which is important, too) but I think this one is different, because I describe a budget for each category of one account and not for the whole account.

Please tell me what you think!

**Comment by mtotschnig** [comment]
Thank you for your thoughts. Even though we did not have a dedicated ticket for budgets, besides #127 that you already mentioned and #139, budgets are on the roadmap and planned to be the corner stone of My Expenses 3.0.

**Comment by primeapple** [comment]
Hey, thanks a lot for your thoughts!

What is the timeline for the 3.0 release? Just an idea (End of 2018?) would be nice :)

**Comment by mtotschnig** [comment]
I will come back to full time work on My Expenses this autumn, and plan to take up the budget theme, after https://github.com/mtotschnig/MyExpenses/projects/9 is finished, so early 2019 would be a slightly ambitious timeline.

**Comment by mtotschnig** [comment]
A first shot at this feature is included in version 2.9.6. We hope to improve upon it based on user feedback until version 3.0 .
