### ISSUE TITLE
Allow to enter split transactions without manual entry of total

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#497]
User provided suggestion: User should not need to enter the total, she only creates the parts, total is calculated for her.
There are three possibilities to implement this feature:
1) Everything stays as it is, but if user clicks on Save button, instead of showing message "There is still some amount unsplit" a dialogue is presented asking to confirm update of total and save.
2) The Total amount field becomes uneditable and is automatically updated to correspond to sum of parts.
3) 1 and 2 are implemented and preference allows to select between them.

**Comment by hachulho** [comment]
Brand new to this site. Did not intend any imogi.   #3 is my choice to keep all options open. I am not a programmer. Just want to split transactions into items with different categories and split payments 'cause I'm always short of money. I also want to be able to transfer or pay from one account to another without doing 2 entry.   For example, I want to pay my credit card account from my checking account.

**Comment by mtotschnig** [comment]
c2defac69c733abf72d4adb44497c89b85ff80b1 referenced this issue by mistake

**Comment by mtotschnig** [comment]
I opted for the following implementation:
Amount will be automatically updated as long as user does not manually update it.
