### ISSUE TITLE
Narrow down extent of charts (Distribution, History)

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#502]
Currently it is not possible to generate the distribution screen, for subsets of the data, e.g for:

- custom periods of time
- a selection of accounts
- a specific payer/payee

This could be implemented by allowing to carry over the filter used on the transaction list to the distribution screen.

**Comment by alex9099** [comment]
This would be nice to also be applied to history, for example, so to mainly see the history of a certain payee/payer.

My idea would be to apply the filters on the main screen, as it is now and then be able to click on history and distribution to see those transactions on some nice graphs
