### ISSUE TITLE
No app can perform this action

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#505]
This occurs in Backup & Restore feature

![screenshot_android_system_20180902-075440](https://user-images.githubusercontent.com/19515542/44951121-ff2fb480-ae85-11e8-8b09-7dacd7014d56.png)

**Comment by mtotschnig** [comment]
This happens if you have the debug build installed in addition to the production build, which have different package ids. I was not bothered yet enough by this to investigate how to fix. Will give it a try now.
