### ISSUE TITLE
Archive accounts

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#508]
Isn't it nice to have an "archive account" feature... An example use case is when you close a bank account but you don't want to delete the corresponding account in ME because data of all transfers and transactions would be gone

**Comment by Akito13** [comment]
@hieu-van @mtotschnig Isn't this issue superseded by #303?

**Comment by mtotschnig** [comment]
@Akito13 Thank you for making me aware of this. You are right. Since both issues together would be on top of the Roadmap Vote at the moment, I will probably pick it up for version 3.0.1 and will keep both issues open until then.

**Comment by Akito13** [comment]
> 
> 
> @Akito13 Thank you for making me aware of this. You are right. Since both issues together would be on top of the Roadmap Vote at the moment, I will probably pick it up for version 3.0.1 and will keep both issues open until then.

I actually voted for #303 yesterday, because it was more elaborated and explained the expected behaviour more clearly. 😄
