### ISSUE TITLE
Allow to store new transaction as template

### ISSUE THREAD

**Issue by funnym0nk3y** [mtotschnig/MyExpenses#511]
Currently I am using a different app for tracking my expenses, which is unfortunately EOL. There was a very handy feature when dealing with recuring similar transactions: The first time a transaction titel is filled in, all the other values are saved. The next time I want to enter the same transaction again I just have to type in the name and everything else is remembered. I don't have to be aware whether it is a recuring transaction or not when I type it in the first time (and as a result making a template or type in the same information several times). It would be nice if this functionality is added to a future release.

**Comment by mtotschnig** [comment]
My Expenses has Auto-Fill based on Payer/Payee. My Expenses does not really have a title for a transaction. The app you are using, is it still available? If not could you provide a screenshot of this functionality?

**Comment by funnym0nk3y** [comment]
Yes, it is still available. It is called "Mein Haushaltsbuch" made by OneTwoApps. It is technically not EOL, but shifted it's focus more towards iOS. 

![screenshot_2018-09-21-15-11-51](https://user-images.githubusercontent.com/41870754/45883458-72578700-bdb1-11e8-8171-c5d4e833a031.png)
This is the default screen. You type in how you want to call your entry, in my case it is the shop i was in. The you select one of the shown templates.

![screenshot_2018-09-21-15-12-18](https://user-images.githubusercontent.com/41870754/45883549-aaf76080-bdb1-11e8-9911-18a1330c75e0.png)
It pastes the values you have used the last time into the form. It is like the autofill you mentioned, but by title.

I got a little confused with both templates and autofill, please excuse my premature ticket. What is the intention of templates compared to autofill? I haven't understood it yet.

**Comment by mtotschnig** [comment]
Autofill is dynamically fetching the last information for a payer/payee and automatically triggered by selecting the payer/payee. A template is static, and is manually selected from the template screen.

**Comment by mtotschnig** [comment]
@funnym0nk3y Thank you for the screenshots. I'll check out the app you referred to.

**Comment by mtotschnig** [comment]
I see two parts in this issue:
1) when creating a transaction it should be possible to immediately create a template from it.
2) it should be possible to refer to the template from the transaction edit form, compare #465

**Comment by mtotschnig** [comment]
I am focusing this ticket on the first of the two mentioned aspects, leaving #465 for the second aspect.
