### ISSUE TITLE
Improve account management and display

### ISSUE THREAD

**Issue by funnym0nk3y** [mtotschnig/MyExpenses#512]
Currently there are two views: Display the transactions of one account or display all transactions. In my use for example there are different accounts I want to keep track of. 
1. Accounts for daily use: Account, which the credit card is associated with; account with debit card; wallet.
To keep track and balance of each account my transactions are associated with the account I was paying with. 
2. Saving accounts: Those are accounts where I basically put money on an want to forget them. 

Now there is a problem: To keep track of my expenses, I would like to have a customizable view, where all my expenses form class 1 accounts are listed, but not those from class 2 accounts.

**Comment by mtotschnig** [comment]
@funnym0nk3y On the Account Edit screen in the menu there is the option to exclude the account from the totals. This should solve the problem. Am I mistaken?

**Comment by funnym0nk3y** [comment]
Yes, it does. Thanks for your help!
