### ISSUE TITLE
403 when using WebDAV despite good credentials on Kolabnow

### ISSUE THREAD

**Issue by tangodev** [mtotschnig/MyExpenses#517]
Hello,

MyExpenses is giving me a Forbidden error when trying to mount a Kolab "files" folder. 

- Android Oreo 8.1
- MyExpenses 2.9.1.4 (rev. 332)

I've managed to successfully mount my Files folder from bash on my Ubuntu box according to those instructions:

https://lists.kolab.org/pipermail/users/2015-December/020315.html

```
td@emerald:/aux$ mkdir davtest
td@emerald:/aux$ sudo mount -t davfs https://apps.kolabnow.com/files/Files davtest/
Please enter the username to authenticate with server
https://apps.kolabnow.com/files/Files or hit enter for none.
  Username: [my_username]
Please enter the password to authenticate user [my_username] with server
https://apps.kolabnow.com/files/Files or hit enter for none.
  Password:  
td@emerald:/aux$ cd davtest/
td@emerald:/aux/davtest$ ls
lost+found
td@emerald:/aux/davtest$ ls -la
razem 1
drwxr-xr-x 3 root root 72 wrz 27 20:33 .
drwx------ 2 root root  0 wrz 27 20:33 lost+found
```
I've double-checked my password, user name, web address and still I can't mount WebDAV for Kolab in MyExpenses.

Side note: perhaps you could provide an example in grey of the URL? I tried using the format webdavs:// instead of https:// at first and didn't understand why the application didn't like the URL.

First I had a 403 error, then I tested on Ubuntu and it was working fine, then I double tested MyExpenses and it gave me a 500 error. Today I tried again, without using Ubuntu to troubleshoot and MyExpenses went back to giving me a 403 error. I've enabled DEBUG mode, yet the files in the log folder of myexpenses are blank.

![myexpenses_dav_configure_screen](https://user-images.githubusercontent.com/12778629/46224926-f5e81980-c357-11e8-9520-aea1bf80d70e.png)

**Comment by mtotschnig** [comment]
Unfortunately I am not able to test this. I registered on KolabNow. But the trial account does not seem to be functional.

**Comment by mtotschnig** [comment]
KollabNow generously granted me test access which allowed me to solve the issue.
