### ISSUE TITLE
device limit exceeded

### ISSUE THREAD

**Issue by takiainen** [mtotschnig/MyExpenses#523]
After flashing a new ROM, I cannot validate my key anymore. The app complains that "device limit has been exceeded, please remove license from another device". 

I don't have any other device nor have I ever used myexpenses on other devices.  And thus cannot remove license. What to do?

**Comment by mtotschnig** [comment]
Ideally in the future before installing a new ROM, you'd unlink the licence in the app's settings. If not, you just contact support@myexpenses.mobi and we can void the devices from your licence for you.
