### ISSUE TITLE
"Theme" submenu lacks capitalization

### ISSUE THREAD

**Issue by edo0** [mtotschnig/MyExpenses#539]
As per the title, capitalization of "Light" and "Dark" options in the Theme menu among the Settings is currently missing.

**Comment by edo0** [comment]
My bad, I didn't upload a related screenshot.
This is what I meant
http://imgur.com/G2JihhM
Maybe I should move this issue to Transifex?

**Comment by mtotschnig** [comment]
@edo0 I understood that you were referring to that menu. Personally I am not disturbed by the two labels being lower case, but it is probably some UX rule that I am not aware of. Could you explain what makes you consider lower case being inconvenient in this context?

**Comment by edo0** [comment]
It's really just a minor things, but to make it consistent with all the other submenus, where the first word is always capitalized
