### ISSUE TITLE
Sync now button in main menu

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#541]
Triggering synchronization is currently possible from the context menu of the backend on the Manage synchronization backends screen. User suggests to make this functionality directly available from the main screen.

**Comment by sivaraam** [comment]
When I see your sentence (emphasis mine)

> **Triggering synchronization** is currently possible from the context menu of the backend on the Manage synchronization backends screen.

I expect that triggering it by tapping on the sync icon would initiate the synchronization immediately. But it's not what's happening to me. Tapping on the sync icon near each account does not have an immediate effect (i.e. I do not see the synchronization progress notification). It appears to me that it is not working. Is this a bug? Or am I missing something?

**Comment by mtotschnig** [comment]
The icon currently is not representing an action, but supposed to indicate the link between local and remote: If there is no icon, the account only exists on the remote side, the sync icon indicates that the account exists on both sides and is configured to be synced, the crossed out sync icon indicates, that the account exists on both sides but is not configured to by synced. The action of triggering synchronization currently is only available by long tapping on the backend (not on the account) and then from the context menu select "Sync now".
It is interesting to learn that the icon raises the expectation of being linked to an action.

**Comment by sivaraam** [comment]
> It is interesting to learn that the icon raises the expectation of being linked to an action.

I thought the icon represented an action as I've generally only used apps in which the Sync icon was used as an action (e.g. K-9 mail) rather than just as an indicator.

> ... sync icon indicates that the account exists on both sides and is configured to be synced ...

Maybe the Sync icon with tick mark would be more suitable to represent that and as an advantage would help avoid being misinterpreted as an action?
