### ISSUE TITLE
Missing notification for scheduled transactions

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#560]
For the context, I have 3 scheduled transactions which I've scheduled for every week day and set to 'Manual' mode. I usually receive the notification for those scheduled transactions using which I manually add transactions when I want to.

For some time now, (possibly since the last update), I'm not getting the notification for scheduled transactions. I'm not sure why this is the case. I even tried removing and re-adding those transactions. I'm still not getting the notifications. 

I'm using the app from F-droid.

**Comment by mtotschnig** [comment]
Sorry for the late reply. This has been fixed with c64449d62a384fa8e8c614de2fac7280e9501ea6 and should be available on F-Droid soon.
