### ISSUE TITLE
Helper transaction for correcting current balance

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#561]
If the balance in the app differs from the actual balance in your pocket, it would be practical to simply enter the new balance and have the app calculate the needed helper transaction. Currently all that the app offer is the possibility to copy the current balance to the clipboard by clicking on it, thus allowing to paste it into the calculator.

**Comment by alex9099** [comment]
I would like to see this implemented :) wansnt this one on the road map vote?

Either a special transaction to correct the current balance or a button on the calculator to make maths with the current balance would be nice

**Comment by mtotschnig** [comment]
The functionality can be invoked by clicking on the title region in the action bar (account label or current balance).
