### ISSUE TITLE
Remove old devices?

### ISSUE THREAD

**Issue by TobiasDev** [mtotschnig/MyExpenses#569]
Hello! 

I re-installed my phone today and wanted to enter my license key to Expense Manager, however, it can´t add it since I have exceeded my limit. How do I remove old ones? Since I no longer have my old phone and data.
Thanks

**Comment by mtotschnig** [comment]
Ideally, on the old device, you'd open the licence entry in the settings, and there you can unlink the device from the licence. If you no longer have the old device and run into the limit, simply contact support@myexpenses.mobi and we will clear the devices from your licence. I have done this in your case already.

**Comment by TobiasDev** [comment]
Thanks! :)
