### ISSUE TITLE
Bug: Show transactions no longer works

### ISSUE THREAD

**Issue by TobiasDev** [mtotschnig/MyExpenses#573]
I used to be able to hold on a category when I was in the category summary view per month to see all transactions in the category, but in the latest version holding and pressing the "Show transactions" only takes me back to all transactions, not showing anything category specific.

**Comment by mtotschnig** [comment]
Thank you for the report. This has been fixed (04a9590b68f800330f3e9ebfa0c5487821620ec7). I am planning for a release towards the end of next week.
