### ISSUE TITLE
Sync now button in main menu should allow to sync all accounts 

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#575]
Follow up to #541: The current implementation only syncs the currently displayed account. As suggested by user, it should be possible to sync several accounts at once, at least all accounts that sync with the same backend.
Following solutions seem possible:
1) The button always syncs all accounts for the backend.
2) The menu entry opens a sub menu with the two options: Sync account, Sync all accounts on backend X
3) A preference in the Settings lets user decide which of the two behaviours the button should adhere to.

**Comment by adrianinsaval** [comment]
This would be a handy feature to have, is it planned any time soon?

**Comment by mtotschnig** [comment]
@adrianinsaval Thanks for your interest, and sorry for the late reaction. I will take this up for version 3.7.4.
