### ISSUE TITLE
Mimic how budgeting works in My Budget Book app

### ISSUE THREAD

**Issue by dalaeance** [mtotschnig/MyExpenses#578]
My Budget Book is another independent money management app available through Google Play Store.

I tested My Expenses and MBB at the same time and, though I ultimately chose My Expenses, I find its budgeting feature very inflexible (which is a shame because it's a paid feature). Your accessibility as a developer, however, factored into my decision to support you.

### Downfalls
- Each budget seems to be tied to a single account. I can create a budget through a currency total page, but I can't exclude accounts as a result.
- Budgets can't be deleted or reset? At least not in any obvious way.
- Every transaction counts against the budget, because there is no filtering.

### How It Can Improve
MBB handles budgets way differently and more flexibly. Budgets have their own section. When you create one, you choose:
1. A name
2. Comment (description)
3. Amount
4. Categories
5. Persons (payer/payee)
6. Groups (for organizing similar transactions; tags, essentially)
7. Accounts
8. Time frame
9. Period (one-time or repeating)

I think a great way to improve My Expense's budgeting is to simply do it the way My Budget Book does. I've included screenshots below.

#### Various sections within MBB
![img_eggsif_6898984410492312656](https://user-images.githubusercontent.com/30301418/60773199-15268b00-a0d0-11e9-98d1-63289b639b7d.png)

#### List of all budgets.
![img_eggsif_9054356249942837490](https://user-images.githubusercontent.com/30301418/60773201-15268b00-a0d0-11e9-9f94-0f5b52c8c986.png)

#### Settings for one of my budgets (details below image).
![img_eggsif_3206577659295792054](https://user-images.githubusercontent.com/30301418/60773198-15268b00-a0d0-11e9-93ad-3fb9bf3afb34.png)

A one-off budget for planning a trip to Montreal. I created a group (works just like a tag), so that only transactions added to this group will be counted against this budget. If I hadn't created the "MTL Trip" group, there were still the time frame filtering and account filtering to work with. I could also have created a category specifically for this trip, but then I would have had to make separate subcategories for food, accommodation, transportation, etc., which is what I had to do in My Expenses under a currency total.

**Comment by mtotschnig** [comment]
@dalaeance Thanks for the suggestion. I am taking substantial inspiration from it for the improvements I am implementing for 3.0.6. 
For the record, MBB does not allow to create one budget, where you assign different amounts to different categories, as ME does.

**Comment by dalaeance** [comment]
@mtotschnig, you are most welcome! It was a pleasant surprise waking up to this news! Especially since I was thinking about it this past week. I still use My Expenses on a daily basis.
I'm happy to provide more feedback in the future if you'd like.

PS: I suppose this may require a separate issue, but I noticed I'm a few versions behind because I use F-Droid as my app store for FOSS apps.

**Comment by mtotschnig** [comment]
@dalaeance 3.0.5.1 has been built on F-Droid two days ago.

**Comment by dalaeance** [comment]
Hahaha! Thanks. I refreshed F-Droid but, for some reason, it didn't pull the updates. There's a whole slew of apps that need updating.

That said, it's set to check daily, so I'm not sure why it missed them.

**Comment by dalaeance** [comment]
>For the record, MBB does not allow to create one budget, where you assign different amounts to different categories, as ME does.

I just remembered that you made this point and figured I should respond to it.

I do like being able to assign specific amounts to categories within budgets; especially when there's an option to rollover or re-allocate unused amounts. I think YNAB does something like this.

**Comment by mtotschnig** [comment]
If I am not mistaken, the implementation just merged and to be released as 3.0.6 fulfils the requirements with one exception: Accounts can be selected only based on what the current account concept provides, i.e. single accounts, currency aggregates, and the total home account. It is currently not possible to select a subset of accounts. This suggestion has also be made in #594 and can be tracked there.
