### ISSUE TITLE
Debt management

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#587]
Replacement for the defunct #386 which has been deleted by Github, probably due to a request by the OP

**Comment by mtotschnig** [comment]
Contributed by user:
![screen1](https://user-images.githubusercontent.com/1485456/68542400-7c20bd00-03ac-11ea-8cd7-5ad1e8371caa.png)
![screen2](https://user-images.githubusercontent.com/1485456/68542399-7b882680-03ac-11ea-9af8-3e3ba17bbad1.png)
![screen3](https://user-images.githubusercontent.com/1485456/68542401-7c20bd00-03ac-11ea-940b-4a4ae1bc5fb3.png)

**Comment by mtotschnig** [comment]
User contributed how debt management can be achieved currently:

# HOWTO trace IOU in MyExpenses

## When I sell something (or lend money) to you
In the fly-out bar touch "New Account"

as an example I'm selling my truck, and this is how I open my new account

```
Label: Ford F150
Description: Anthony
Opening balance: (+) $10'000
Currency: USD
Type: Asset account
Color: any
Synchronization: any
Goal/Limit: empty  

in the top right vertical ellipsis 
please mark "Exclude from totals" check box

and click save
```
On another scenario, if I just give $100 to someone and want to have it back, then the account will be opened with zero amount and I will make a transfer from wallet account to the IOU account.

When Anthony (the guy who got my truck) pay some of it, I make a transfer from IOU account in to the Wallet account (if it is in cash) and that will decrease the IOU amount and will increase **accounted** cash amount.  
and when account hit zero - you can close the account and then hide or delete it afterwards.

## When I borrow money from you

Create new account:

```
Label: NewLaptop
Description: Mom_and_Dad
Opening balance: (-) $9'000
Currency: USD
Type: Liabilities account
Color: any
Synchronization: any
Goal/Limit: empty  

in the top right vertical ellipsis 
please mark "Exclude from totals" check box

and click save
```

Now every time you return some money for the laptop, 
you will create transaction 
Wallet -> NewLaptop (if it is in cash) for that amount 
and when account hit zero - you can close the account and then hide or delete it afterwards.

**Comment by niranjanpr** [comment]
when this feature is introducing, iam excited to see this feature

**Comment by sivaraam** [comment]
I happened to become aware of a use case for debt management recently. As an extension to linking the contact info to the debt, the app could also notify the corresponding contact (possibly through SMS, etc.) about the debt amount and transactions made in the debt. This would be helpful to keep the other person in sync with transactions related to the debt. This could also be an optional feature which could be controlled by the user of the app. Let me know if anything isn't clear.

**Comment by mtotschnig** [comment]
@sivaraam I am publishing an MVP for this feature with version 3.3.4 without the feature you suggested, but plan to take it up for 3.3.5.
