### ISSUE TITLE
Change selection of currency

### ISSUE THREAD

**Issue by claudiofus** [mtotschnig/MyExpenses#591]
Hello, considering the quantity of currencies it's a bit difficult to find one. 
I think it could be great an HTML select with a text input filter extending your `Currency` class with an appropriate method.

Thank you

**Comment by sabi0** [comment]
Alternatively, currencies already used in the book could be shown at the top of the list:
EUR
USD
---
AFN
ALL
...

Or maybe "Customize currencies" could allow selecting the currencies that should be available in the Currency drop-down.

**Comment by mtotschnig** [comment]
I'll go with @sabi0 's suggestion.
