### ISSUE TITLE
App is not using translated versions of strings

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#592]
Regardless of the 'App language' set, the app always shows content only in English.

This seems to be happening since the latest update (v3.0.5.1).

**Screenshot**
![Screenshot_2019-09-29-21-33-38](https://user-images.githubusercontent.com/12448084/65835734-48e10d80-e2d9-11e9-9fc1-188796808ce7.png)

**Comment by mtotschnig** [comment]
@sivaraam Thank you for the report. I was able to reproduce the problem on a Lolipop device, but not on Pie. Could you tell on which Android version you observed the problem?

**Comment by sivaraam** [comment]
I use an Android 5.1.1 device (Lollipop). Sorry forgot to mention that 🙁

**Comment by mtotschnig** [comment]
After investigation, it seems to be caused by Androidx Appcompat 1.1.0 https://stackoverflow.com/a/58004553/1199911 . The problem appears on API 21 to 25 .
