### ISSUE TITLE
Export as csv not working correctly

### ISSUE THREAD

**Issue by matthiasroos** [mtotschnig/MyExpenses#593]
Since I use the app since 2015, my database has grown and grown. To analyse my data, I always export all items as csv and I do not delete items after exporting. Therefore, it is way over 2000 entrys.

But today I realised that the resulting csv is not correct, it is truncated in the middle of an entry dating back half a year and newer items are missing completely. Additionally, the first 356 lines appear twice in the file.

I also looked into old files I exported a while back. This error also occurs in a csv from August, a copy from March is still correct.

App Version: 3.0.5.1
Model: Nokia 8.1
Android Version: 9 + 10

**Comment by mtotschnig** [comment]
Thank you for the report. I tested CSV export on an account with 2500 entries and did not see any problem. Do you have the same broken result, each time you export? Could it be the case, that there is some problem with the device where the export is stored?

**Comment by matthiasroos** [comment]
The exported files are different, the newer files are a little longer. But if I export twice in a row, I get the same files. Interessentingly, the filenames also always end in ".csv.csv".
I did not yet test another device, but will do as soon as I have the time. With my old smartphone in March, the export still worked, so let's see!

**Comment by matthiasroos** [comment]
I could narrow down the source of the erroneous files (also the backup ZIP files were corrupted, unfortunately leading to some data loss) and it's not in your app. In some way it must have to do with the app I use for transferring the files to my computer.
Thank you for your time and effort!
