### ISSUE TITLE
Information of split transaction lost after trying to discard it

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#604]
When I try to discard a split transaction and then dismiss the action via the confirmation prompt the splits that I've already added are lost. Also, I'm not able to add splits after that.

### Steps to reproduce
1. Start a split transaction
2. Enter the amount and payee information
3. Add one or two splits to the transaction
4. Hit back to discard the split transaction
5. Tap 'No' in the "Discard new transaction?" prompt

### Expected results
The splits that were already added are still there and I am able to add more splits.

### Actual results
The splits that were already added are gone and I get the "Error while saving transaction" message when trying to add a new split.

**Comment by mtotschnig** [comment]
Thank you for the report. Will be fixed in next version.
