### ISSUE TITLE
Cosmetic: Sub-categories are not indented

### ISSUE THREAD

**Issue by sabi0** [mtotschnig/MyExpenses#609]
When expanding a category (e.g. Food) all the sub-categories (Canteen, Bar, etc.) are displayed with the same indentation level.

The bold vs regular font difference is not quite enough to reliably tell that "Fines" is a sub-category in "Car" while "Gifts" right after it is a separate category.

**Comment by mtotschnig** [comment]
Thank you for bringing this up. I will try to solve the issue by adding an "empty group indicator".
