### ISSUE TITLE
WebDAV via Nextcloud throws 401 if configured as synchronization backend

### ISSUE THREAD

**Issue by 1989gironimo** [mtotschnig/MyExpenses#628]
Tried to configure my Nextcloud instance (which isn't supported anymore, but 18.0.1 is still not released for the Yunohost base) as a Webdav backend, but it just says 401 at the end of the line for configuring the server URL, if I try to connect.
Every other app (Davx5, Nextcloud Client, etc.) is working as intended, so it must be the combination of MyExpenses and Nextcloud in this particular version.

What can I provide to check what's going on? Is there some kind of clientside logging active?

EDIT: Checked it with another instance, running 16.0.8 - it's working there.

**Comment by mtotschnig** [comment]
Which versions of NextCloud are working, which are not? Is the instance publicly accessible, can you provide me with a test account?

**Comment by 1989gironimo** [comment]
16.0.8 seems to be working, I can provide a testing account if you want to, for both instances
Nextcloud 15.0.14 doesn't seem to be working. I can provide a test account here as well.

Should I contact you for this via michael@totschnig.org ?

**Comment by mtotschnig** [comment]
Better support@myexpenses.mobi.

**Comment by 1989gironimo** [comment]
Ok, updated my instance to 18.0.1 and it still doesn't work.
But I cannot interpret the 401 error, is there some way to debug this?

**Comment by mtotschnig** [comment]
I tested to access your server with the provided test account. What I found out, is that the 401 is returned in response to the OPTIONS command, that MyExpenses sends, to establish if the server supports WebDAV. Could you check if you need to enable the OPTIONS config in your web server settings? If I try to bypass the OPTIONS check while debugging, I am unfortunately getting TimeOutExceptions while talking to your servers.

**Comment by 1989gironimo** [comment]
You said "servers" but the next-cloud.org instance is working pretty well?

I'm running nginx as the webserver on my own instance, I'll give your suggestion a try and will report back in a few days.

**Comment by 1989gironimo** [comment]
OK getting it now, you meant both servers aren't responding anymore if you just omit the OPTIONS check - but the next-cloud.org intance is otherwise working.
It really seems like a misconfiguration of my webserver, so this bugreport is a littlebit misplaced.

I'm asking for help now on the yunohost forums to fix this in my nginx config (because I don't really know where to put those), thanks anyway :)
