### ISSUE TITLE
Trouble with webdav sync on MIUI (Xiaomi)

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#637]
Hey, 

I'm trying to sync my local database with a nextcloud instance, but it looks like i'm having some trouble, this is are the logs on my webdav/nextcloud server:

```IP - alexandre [17/Apr/2020:23:35:40 +0100] "HEAD /remote.php/dav/files/alexandre/ENCRYPTION_TOKEN HTTP/1.1" 404 -

IP - alexandre [17/Apr/2020:23:35:41 +0100] "PROPFIND /remote.php/dav/files/alexandre/ HTTP/1.1" 207 17904

IP - alexandre [17/Apr/2020:23:35:41 +0100] "HEAD /remote.php/dav/files/alexandre/somefolder/metadata.json HTTP/1.1" 404 -

IP - alexandre [17/Apr/2020:23:35:41 +0100] "HEAD /remote.php/dav/files/alexandre/someotherfolder/metadata.json HTTP/1.1" 404 -
```
But the problem seems to be that nothing is found, either i'm using the wrong link or... idk

The SyncAdapter file doesn't seem to be populated, i have activated debug

I would like to buy myexpenses (well, or do a direct donation :) ), i have used it quite a lot in the past, and now i will start using it again, though it would be nice to have syncing working

**Comment by alex9099** [comment]
Just tested with another public instance of nextcloud and it doesn't seem to be working

**Comment by mtotschnig** [comment]
The problem might be that the web server does not allow HEAD requests. Could you send me a feedback request from the app's settings to let me understand which app version you are using.

**Comment by alex9099** [comment]
```
APP_VERSION:3.0.9.1 (revision 398) 20200324-1802 GITHUB com.google.android.packageinstaller
ANDROID_VERSION:10
BRAND:Xiaomi
MODEL:Mi 9T
CONFIGURATION:{"assetsSeq":0,"colorMode":10,"densityDpi":440,"fontScale":1,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_GB","mcc":268,"mnc":1,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":768,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":392,"seq":1,"smallestScreenWidthDp":392,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_YES","userSetLocale":false,"windowConfiguration":"{ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 0 - 1080, 2210) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0}"}

```

The version doesn't seem to be the most recent, it's the one on fdroid

**Comment by mtotschnig** [comment]
I tested wölkli, and it works here. For a folder created at the root level called MeineAusgaben, the URL I use is https://cloud.woelkli.com/remote.php/dav/files/michael@totschnig.org/MeineAusgaben/

**Comment by alex9099** [comment]
Strange, it registers fine on the app, but no files seem to be created, how would I debug this?

On 21 April 2020 15:56:32 WEST, Michael Totschnig <notifications@github.com> wrote:
>I tested wölkli, and it works here. For a folder created at the root
>level called MeineAusgaben, the URL I use is
>https://cloud.woelkli.com/remote.php/dav/files/michael@totschnig.org/MeineAusgaben/>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/mtotschnig/MyExpenses/issues/637#issuecomment-617232424

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mtotschnig** [comment]
Since you are using a Xiaomi device, please verify, that you are not hit by the problem described in #450 .

**Comment by alex9099** [comment]
![Screenshot_2020-04-22-10-14-03-809_org thoughtcrime securesms](https://user-images.githubusercontent.com/7517045/79964902-4287ce00-8483-11ea-879e-c555d2d4d4ef.jpg)
Yeah, that was it, damn miui firmware... Always breaking stuff, hoping to get official lineageos soon :)

Anyway, perhaps you can put a warning for miui users to enable autostart?
