### ISSUE TITLE
Synchronization of categories

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#639]
Currently synchronization is based on transactions and categories are only synced as soon as they appear as part of a transaction.
User might want to have identical set of transactions on multiple devices independent of transactions.

**Comment by honnel** [comment]
Additionally, the current synchronization does not contain the category icon

**Comment by zeekoe** [comment]
+1
Can this be achieved / worked around by creating a backup of app data on one device, and restoring that on a second? Or does this give problems (eg each device having a unique identifier)

**Comment by mtotschnig** [comment]
Outsourced the icon problem to separate ticket: https://github.com/mtotschnig/MyExpenses/issues/1119, because it is easier solvable in the constraints of the current synchronization architecture.

**Comment by mtotschnig** [comment]
Automatic and full synchronization of all categories still seems out of scope to me for two reasons:

1. It would require a different approach from the current synchronization architecture, which is based on changes happening in the context of accounts.
2. Keeping the whole tree in sync taking move operations into account is very difficult to achieve taking into account conflicts like the same category being moved to different targets on both devices.

I plan to introduce the following improvements that will operate on how category information is written to the existing synchronization

- Categories will be assigned a UUID, so that changes of a label can be tracked instead of creating a new category. If move operations can also be reproduced via synchronization remains to be investigated.
- Icon names will be written to the synchronization (#1119) 

In addition, I plan to provide the means for manual synchronization of categories: The"Manage categories" screen will provide a new Export functionality, that includes icons. This functionality might allow to write the file to a synchronization backend, in which case it would also be possible to import from the synchronization backend on the same screen.

**Comment by mtotschnig** [comment]
Note to self, Todos:

- Add index on uuid
- Database migration
- Add color to information that is synced
- Export / Import
