### ISSUE TITLE
Add "previous day" and "next day" buttons to navigate between dates in "New booking"

### ISSUE THREAD

**Issue by primeapple** [mtotschnig/MyExpenses#667]
I want to propose a very little feature, that would make the app more intuitive and useable (imho).

When adding a new booking, I have to provide a date. The default date is the one of today. But most of the time I was lazy and have a bunch of receipts from the last days in my pocket, that I have to add. So I have to change the date to yesterday or 2-5 days ago. To do this I have to click the date, look for the correct date and tap on the tiny number in the calendar.  
Since we all like smashing buttons more than scanning a calendar to find the correct date, wouldn't it be great to just have the option to navigate to a date from today by pressing a button like "Previous day" or "Next day"?  So pressing "Previous day" 5 times will go to the date 5 days before the current date.  
The function to select a specific date in the date picker when clicking on the date should stay, of course.

The buttons should be selfexplaining. Maybe use something like "+1" and "-1"? Or "Prev." and "Next"? "Earlier" and "Later"? "+" and "-"?

Currently it is like this:
`Date: <button>15.07.20<\button>`
Make it something like this:
`Date: <button>-</button> <button>15.07.20<\button> <button>+</button>`

Of course, the distances should be adjusted.

What are your thoughts?

**Comment by primeapple** [comment]
Hey, @mtotschnig , this is fairly straightforward, what are your thoughts?

**Comment by mtotschnig** [comment]
@primeapple Thank you very much for the suggestion, which makes sense. I consider including it into one of the upcoming releases.

**Comment by mtotschnig** [comment]
For the moment, it seems difficult to me to fit the additional buttons into the current design on phone portrait. It might be possible to only offer these buttons on landscape or tablet. Alternatively on portrait, date and time buttons could be split on 2 lines, or the buttons are only shown when the time button is hidden via preference.

**Comment by primeapple** [comment]
Ahh, yeah, I agree with this. I didn't think of it, because I have the time button always hidden. If it is not hidden, you could only show it in landscape. That would be a compromise.

**Comment by mtotschnig** [comment]
I think, I found a solution, by incorporating the navigation controls into the buttons:
![image](https://user-images.githubusercontent.com/1485456/106132506-53791480-6164-11eb-8eac-f7bd3e34cbea.png)
