### ISSUE TITLE
Crash on an extended version

### ISSUE THREAD

**Issue by konst5r** [mtotschnig/MyExpenses#670]
I have constantly crash of the App after updated from basic version to extended  
It reproduced by touching header in the total account

**Comment by mtotschnig** [comment]
Could you please contact me from the app's settings, or post here which version of the app on which Android version you are using.

**Comment by konst5r** [comment]
> Could you please contact me from the app's settings, or post here which version of the app on which Android version you are using.

App version is 3.1.2.2, Android 10

I've solved it by made a backup and restored base from it (before restoring I've completely clean file BACKUP_PREF in zip archive). App works now, but obviously has problem when touching header in the total account without sorting - App freezes for 5-10 seconds and sometimes Android suggest to kill process
