### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [mtotschnig/MyExpenses#672]
`ERROR: Found unknown maven repo 'https://dl.bintray.com/mockito/maven/' at myExpenses/build.gradle`

Also not
```
Could not find org.mockito:mockito-core:3.3.10.
      Required by:
          project :myExpenses
```
...in any of the [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L137)

Can we add this as a git [submodule](0https://f-droid.org/en/docs/Build_Metadata_Reference/#Builds) or [srclib](https://f-droid.org/en/docs/Build_Metadata_Reference/#Builds) and build beforehand?

/LE: FYI https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7203

**Comment by mtotschnig** [comment]
I think, I do not need 'https://dl.bintray.com/mockito/maven/' any more. I am in the process of preparing the next release, and will remove it before pushing the tag, and hope that this will build again on F-Droid.

**Comment by licaon-kter** [comment]
Do ping me if you want to test before tagging

**Comment by mtotschnig** [comment]
@licaon-kter Thank you for the offer. I removed the reference to Bintray. Could you test, if this now works for F-Droid?
