### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#674]
This request comes up regularly. Technically I could think of 2 different approaches:

1. The Web UI is connected to a synchronisation backend, and writes new entries there. This would probably be limited to creating new entries, unless the whole sync history is interpreted.

2. A server embedded into the app, that a user could connect to via the phone's IP address.

**Comment by keunes** [comment]
I can export files from my bank, but only on their website, not in the app. I could synchronise that file to my phone and then import it, but some web interface would indeed be helpful.

Option 2 (web server on the phone accessed via an IP address) sounds technically complex for the end user - I guess using a synchronisation service would be more convenient. Would be awesome for example to have such web service as a Nextcloud app :)

**Comment by mtotschnig** [comment]
3.2.4 introduces implementation of the second option, mainly chosen for reason of feasibility. The first option could still be implemented at a later stage, but probably would require a refactoring of the synchronization architecture.

**Comment by mtotschnig** [comment]
The current implementation is limited to entering new transactions, transfers and split transactions are not yet supported. I will create new tickets for improvements depending on demand.
