### ISSUE TITLE
Date and time for cloned transactions

### ISSUE THREAD

**Issue by CaptainFrosty** [mtotschnig/MyExpenses#679]
I would like to request an option to preserve the date and time when cloning a transaction, since most the time I am using it to add a similar transaction that occurred at the same time. Thanks

**Comment by CaptainFrosty** [comment]
Closed since it's been added. Much thanks

**Comment by CaptainFrosty** [comment]
@mtotschnig still shows in roadmap, not sure if that's automatic or needs to be removed manually

**Comment by mtotschnig** [comment]
I somehow missed that this was a duplicate of #598 . Thanks for the cleanup. I needed to run a script in order to update the roadmap database.

**Comment by CaptainFrosty** [comment]
I should have searched the open issues before I posted. My apologies
