### ISSUE TITLE
WebDav modal cannot be closed by tapping 'back' button

### ISSUE THREAD

**Issue by keunes** [mtotschnig/MyExpenses#684]
1. go to settings > synchronisation backend > add
2. select WebDav
3. Tap Android's 'back' button once the modal has opened

Expected: modal closes (if any data is entered: either maintains filled in data, or asks for confirmation)
Current: nothing happens

**Comment by mtotschnig** [comment]
The dialogue is currently set a not cancelable. I suppose that the idea was to prevent user from losing entered data accidentally. Since there is a "Cancel" button, is this really a problem?
