### ISSUE TITLE
Preference for date handling of cloned transactions is misleading

### ISSUE THREAD

**Issue by Anmibe** [mtotschnig/MyExpenses#700]
When cloning a transaction the date is always preserved once the correspoding pref setting was switched on and later switched off (even after restart).

Version: 3.1.6.2

**Comment by mtotschnig** [comment]
The pref setting you mention, is it the one that allows to toggle between "Cloned transactions keeps original date"  and "Cloned transactions have current date"? If yes, I am not able to reproduce any problem. Your observation is that you always get the original date?

**Comment by Anmibe** [comment]
Yes.

Sorry is was my fault. I missinterpreted the describing text of the item (screenshot): "Preserve the original date" = switched off, means the current date will be used. But when swiching it on, the description is changing.

![Screenshot_20201113_111132](https://user-images.githubusercontent.com/56979681/99061289-9e41b200-25a1-11eb-8429-601b95434083.png)

**Comment by mtotschnig** [comment]
It is not your fault. The absence of a title makes it misleading.
