### ISSUE TITLE
Transaction date set to unix epoch

### ISSUE THREAD

**Issue by Anmibe** [mtotschnig/MyExpenses#702]
**Do:**
Distribution → show transactions →  change from a multiline transactions (for example) the remark  → save.
**Result:**
The transaction seems to be vanished from the list. Scrolling to the end of the list you´ll find it. Its date is set to epoch  unix (1.1.1970)!
**Solution:**
Search the original transaction in the transaction list of the account, open it and just save it,the date is set again.

**Remark**:
Anyhow, it’s not possible to go from the transaction in the distribution section to the original transaction. Not a bug, but odd. 

Verson 3.1.6.2

**Comment by mtotschnig** [comment]
Thank you for the report. Could you more precisely describe what you mean by "change from a multiline transactions (for example) the remark"?
I am also not getting what the remark means. What does "the transaction in the distribution section" refer to?

**Comment by Anmibe** [comment]
I hope the screenshot will help. See the date last line, it has chnged to epoch

![Screenshot_20201113_114015](https://user-images.githubusercontent.com/56979681/99063745-45741880-25a5-11eb-9f12-64271470b1c1.png)

**Comment by mtotschnig** [comment]
I do not yet understand what leads to the result of the corrupted date. I was not able to reproduce it by Distribution -> Show transactions -> Click on entry in the list -> Edit -> Change Notes -> Click on floating action button.
Is this the scenario you are executing? If yes there must be some additional condition triggering the problem.
You could also contact me at support@myexpenses.mobi to discuss the problem in German.

**Comment by Anmibe** [comment]
Did you try it on a **split** transaction? It’s reproducible.

I’ve send you a more detailed e-mail.
