### ISSUE TITLE
Payment method is shown for a cash account transaction in some cases

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#711]
I'm not very sure of the case but the "Payment method" is shown for some cash account transactions. They appear like this:

![Screenshot_2020-11-14-11-11-15](https://user-images.githubusercontent.com/12448084/101993151-6338b880-3cde-11eb-8476-db73032c4de5.png)

I think this has something to do with auto-filling transaction information using the Payee but I'm not very sure.

I observe this using v3.2.0 of the app on a Samsung SM-J111F running Android 5.1.1.

**Comment by mtotschnig** [comment]
Thank you for the report. One possible reason for that situation might be that a transaction what first created in the context of a bank account, and then it has been mapped to a cash account, or that the account is is mapped to has had its type changed. Can you exclude that one of these has happened in your case?

**Comment by sivaraam** [comment]
> One possible reason for that situation might be that a transaction was first created in the context of a bank account, and then it has been mapped to a cash account,

By this if you mean mapping the transaction to a cash account _after_ it has been created in the context of a bank account, the no. That can't the case at least for all the transactions in which I observe this.

> or that the account is is mapped to has had its type changed.

I don't remember changing the type of the account. I believe its been a cash account ever since I've created it. Anyway, if it's an account type change shouldn't I be observing this for all transactions in that account?

**Comment by mtotschnig** [comment]
You were right, the most probable explanation is auto-fill. I was able to reproduce it, and will fix it for next release. Probably  won't touch existing transactions, but prevent the problem from appearing with new transactions created from auto-fill.

**Comment by mtotschnig** [comment]
Coming back to this issue: Actually some users define payment methods for cash accounts, so the fix for this issue introduced a bug for them, where payment methods were no longer stored in cash account. So need to rework the solution for this problem ...
