### ISSUE TITLE
A display issues

### ISSUE THREAD

**Issue by franklinbill** [mtotschnig/MyExpenses#715]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I suggest that you can set the width and height of the component to adaptive text.
App version is 3.2.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="440" alt="bug-myexpenses_444-2" src="https://user-images.githubusercontent.com/18572115/103153725-92b2ef00-47cd-11eb-9420-a69d0ec19e8e.png">

**Comment by mtotschnig** [comment]
Thank you for the report. I forwarded it upstream, to the library which is used for generating this dialogue.
