### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mtotschnig/MyExpenses#722]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by mtotschnig** [comment]
@mondlicht-und-sterne  I added some screenshots in 2ea1ed5893358b9b53e845091ff4fec10f518312, hoping that F-Droid will pick them up.

**Comment by mondlicht-und-sterne** [comment]
Yes it is, thank you
