### ISSUE TITLE
Trouble importing a backup

### ISSUE THREAD

**Issue by ChibiYuzu** [mtotschnig/MyExpenses#745]
I'm trying to restore a backup of my data from one phone to the other and it keeps telling me that the import failed, because the restore file seems to be encrypted with another secret passphrase. I'm not sure what to do. I don't know either how to export it as CSV or QIF. Could you help me there? I'm sorry if my questions seem stupid, but I'm not yet very skilled with this kind of application.

Thank you so much in advance!

P.S.: I have a premium version.

**Comment by mtotschnig** [comment]
Please contact support@myexpenses.mobi for support request or better still, use "Send feedback" from the app's settings.
If you want the backup to be encrypted, you need to make sure that on both the device where you create the backup and the device where you restore it, the "Passphrase for backups" is identical.
