### ISSUE TITLE
clearing fields (category and notes) then taking a photo resets them to the latest transaction details

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#797]
This issue happens as soon as I select some payee where the fields get auto filled from last transaction. 

If I click to take a photo it and apply it as soon as I get back to the add transaction display it resets the category and notes fields.

I can't reproduce this everytime, not sure what exactly triggers it

**Comment by mtotschnig** [comment]
Thank you for the report. Could you provide information on app version and Android version?

**Comment by alex9099** [comment]
Totally forgot about that :)

I'm on android 10 (pixel experience on xiaomi mi 9T codename davinci) application version is 3.2.5

**Comment by alex9099** [comment]
Notes also seem to be reset (to the previous transaction from the same payee) if i clear that field and the change/choose a category. Not sure if related

**Comment by mtotschnig** [comment]
Sorry for not taking this up earlier, and thank you for all the information. Yes the two scenarios you describe seem related with respect to the bug. I try to solve it for version 3.3.3
