### ISSUE TITLE
Editing automatic Plan: no app found to edit calendar event

### ISSUE THREAD

**Issue by SAMUD** [mtotschnig/MyExpenses#798]
Hi,

My automatic plans are not working anymore. When I want to edit the plan and click on the "Date-Picker" I am getting a message that there is no compatible calendar app installed. (Keine App für die Bearbeitung des Kalenderereignisses gefunden)
However - as always - I am using the Google Calendar app and also have an email app with calendar-support installed.

When I make a new plan it shows up in my selected calendar in the calendar app. However I can not edit it a second time afterwards in My Expenses. Just getting the above error message.

Android 11
Custom Rom on Xiaomi Mi9
Google Calendar
My Expenses 3.2.7

**Comment by mtotschnig** [comment]
Many thanks for the report. Will be fixed in version 3.2.8.
