### ISSUE TITLE
Feature request: Click on the history graph to go to the date of a point

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#820]
When double clicking the history graph i think it would make sense to go to the date shown of a point on the transaction list

(btw, somewhat related question, on the month option, the values shown are at the end of a month or n months from today [so day 30 april vs day 15 of april]?)

**Comment by mtotschnig** [comment]
Could you explain what you mean by "go to the date" ?
Your second question refers to the values of the blue balance line, right? It shows the balance including all transactions of the period, i.e. for monthly grouping until the end of the month).

**Comment by alex9099** [comment]
so only now i noticed that you can click on the green or red bar of the history to be shown the respective positive or negative transactions. I was expecting to be able to click the blue dot (the current balance at that time) and be directed to the list with a filter relative to the time the bars are referring.

Hope i was not too confusing :/

**Comment by mtotschnig** [comment]
With the ability to see transactions by clicking on the bar, can we close this ticket, or could you explain what additional value you expect from being able to click on the blue line? Since this is trickier to achieve, I would like to understand your problem better.

**Comment by alex9099** [comment]
Yeah, that almost does what i want, i don't think it's worth the effort to implement what i'm saying :)

Perhaps at some later date when other more important features are implemented.

Thanks a lot for this awesome app ;)
