### ISSUE TITLE
Budgeting and Distribution suggestions

### ISSUE THREAD

**Issue by Dave025** [mtotschnig/MyExpenses#821]
Hi, I love the interface of the app and its features as well, but there's something in the Budgeting and Distribution tabs that can be improved. 

You can add an option to show the itemized related transactions of the expense selected in the pie chart within the time/duration selected. 
![Screenshot_20210515_215134](https://user-images.githubusercontent.com/84235339/118363944-2d6b6900-b5c9-11eb-9a32-c08b46691e41.jpg)
![Screenshot_20210515_215150](https://user-images.githubusercontent.com/84235339/118363945-2e03ff80-b5c9-11eb-9eb0-c9897f1548b3.jpg)
![Screenshot_20210515_215154](https://user-images.githubusercontent.com/84235339/118363947-30665980-b5c9-11eb-9ae9-a5f23d0c25fe.jpg)
These are taken from another app, Bluecoins, and that is its feature that I liked the most. 
![Screenshot_20210515_215044](https://user-images.githubusercontent.com/84235339/118364305-8982bd00-b5ca-11eb-9a12-8531529a4a3a.jpg)

![Screenshot_20210515_215049](https://user-images.githubusercontent.com/84235339/118364059-80ddb700-b5c9-11eb-9162-efb8f1b996b9.jpg)
![Screenshot_20210515_215114](https://user-images.githubusercontent.com/84235339/118364061-83401100-b5c9-11eb-9222-03e27950f15f.jpg)

I suggested these because I think it will be useful for us to see what's inside our expenses and know which are we going to make adjustments. Btw, I like that we can split transactions into multiple expense and accounts plus the percentage of the savings account balance to the goal set. So I hope this helps. Thanks!

**Comment by mtotschnig** [comment]
Thank you for your suggestion. Do I understand you correctly that you would like to see a link between the distribution and the budget screens? It would be easier to grasp if you could provide only that part of the screenshot relevant to your suggestion.

**Comment by mtotschnig** [comment]
If however you mean navigating from a category to the corresponding list of transactions, this is already possible by long-tapping on a category and selecting "Show transactions" from the context menu.
Please reopen if you had something different in mind.
