### ISSUE TITLE
Using a template resets account information of current transaction

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#823]
When I have a saved template and I apply it in the current transaction in Account B, the account gets reset to Account A. The Account A seems to be the first account I created. To be more clear, this happens when I create a transaction using the '+' FAB icon when I'm in Account B and apply the template using the template menu shown in the "New Transaction" screen.

I expect that the account information is not reset as my intention was to use the template for the current account.

I'm observing this on My Expenses v3.3.0.1 running on a OnePlus Nord with Android 11.

_Side-question_: Is the account information stored in a template?

**Comment by mtotschnig** [comment]
Yes, at the moment, the information contained in a template includes the account. I understand your use case, where you want to instantiate the template without changing the account already present in the form.
One solution might be to allow to define templates with the account left unspecified. But you might still want to have a "default" account for the template when you instantiate it from the "Templates and plans" screen.

**Comment by sivaraam** [comment]
> One solution might be to allow to define templates with the account left unspecified. But you might still want to have a "default" account for the template when you instantiate it from the "Templates and plans" screen.

This makes sense.

> I understand your use case, where you want to instantiate the template without changing the account already present in the form.

It's actually trickier than that. When I use the method I describe in the description to use a template, neither the account information in the form is used nor the account associated with the template is used. The account gets reset to the first account I created regardless of the account contained in the template. Is this intentional?

**Comment by mtotschnig** [comment]
I am sorry, I misunderstood the problem. I was able to verify the problem you describe. This is clearly a bug.

**Comment by mtotschnig** [comment]
@sivaraam The bug of falling back to the first account should be solved in version 3.3.1.1.  I have created #838 for your suggestion concerning templates that are not tied to one account. Please upvote this issue both here on Github and on the Roadmap Vote to keep it on my radar.

**Comment by mtotschnig** [comment]
On a sidenote, Roadmap Vote is broken (#833) from 3.3.0 and will be fixed in 3.3.1.1
