### ISSUE TITLE
Incorrect account balance in few accounts

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#831]
In the past few days, I've been observing a weird thing. In two of the several accounts (let's say A and B) that I use, the total of the account and the final total shown for "Today" don't match. In one the total is less by amount X and in the other it is more by X. So, it seems like something happened during a transfer but I'm not able to figure which one or what. Just to be clear, I indeed do often make transfer transactions between A and B.

Any help to figure out what's going would be very helpful.

I'm using My Expenses 3.3.0.1 on a OnePlus Nord running Android 11.

**Comment by mtotschnig** [comment]
The usual case where the two amounts differ, is when there are transactions in the future, because, the amount in the action bar is supposed to show the current balance, whereas the one in the group header shows the total including also future transactions. Might it be your case, that the transfer you mention has a future date?

**Comment by sivaraam** [comment]
It doesn't look like it. I couldn't see any future transactions in either account. Also, I don't remember adding any future transaction for that particular amount either.

**Comment by mtotschnig** [comment]
Future could also be a transaction on the same day with the time in the future. In the list, the line is rendered with a darker background.

**Comment by sivaraam** [comment]
There's none of that kind either. So, you could rule that out too. The inconsistency has been there for quite sometime now.

**Comment by mtotschnig** [comment]
Are there any split transactions in these two accounts? If it might be possible for you to share a dump of your data which only contains the transactions with dates and amounts, could you contact support@myexpenses.mobi ?

**Comment by sivaraam** [comment]
> Are there any split transactions in these two accounts?

Yes. There are. But split transactions linking both these accounts should be very minimal, if any.

**Comment by sivaraam** [comment]
I went on digging for the issue myself today. I narrowed down the issue to weird split transaction. That split was in account X but all the splits were mapped to account Y for some reason. I'm not very sure how that happened but fixing the split corrected the balance for both the accounts. Thanks for the help!

**Comment by mtotschnig** [comment]
The inconsistent split transactions were probably caused by #987 which is now resolved.
