### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [mtotschnig/MyExpenses#845]
https://hosted.weblate.org/projects/my-expenses/categories/#information
Says LGPLv3+
whereas
https://github.com/mtotschnig/MyExpenses/blob/master/LICENSE
says GPLv3+

If one of the libraries is AGPLv3+, I think that makes the whole thing AGPLv3+, but that is another matter.

**Comment by mtotschnig** [comment]
Thanks for the report. I had accidentally selected the wrong licence when setting up the resource on Weblate. This is now corrected.
As for AGPL, my understanding is, that its compatible with GPL, the only difference relating to use on web services, which is not applicable to MyExpenses.

**Comment by comradekingu** [comment]
@mtotschnig While the effect may be irrelevant to this project specifically (now), it doesn't mean the specifics of the license don't apply. Don't think it is compatible the other way around, because then it would be somewhat void.
