### ISSUE TITLE
Cant restore on Android 11

### ISSUE THREAD

**Issue by ashjas** [mtotschnig/MyExpenses#846]
Created backup on a device running android 10.
When restoring on Android 11, after the backup file is selected, on clicking ok, there is a dialog saying, No file BACKUP found in archive ".../../../..myexpenses/cache"
But the backup file path i browsed was something else than whats mentioned in this prompt..

![Screenshot_20210620-192710_1](https://user-images.githubusercontent.com/788766/122676937-be9fb200-d1fd-11eb-9d26-4c90c016ab38.png)

**Comment by mtotschnig** [comment]
The error is misleading. It is shown, when after unpacking the archive into a working directory, which is the one mentioned in the message, the backup file is not found. Could you show the restore dialogue just after selecting the file, here or by contacting support@myexpenses.mobi?

**Comment by ashjas** [comment]
Here you go..
https://user-images.githubusercontent.com/788766/122681351-6ffc1300-d211-11eb-8aaf-ce027db9eb37.mp4

**Comment by mtotschnig** [comment]
Thanks for the video, which does shed a light on the problem. You are selecting a .bin file. I am not sure what this represents. My Expenses does create a file with extension .enc for an encrypted archive. Could you try to make sure that you transfer the file exactly how it is created on the first device to the second device.

**Comment by ashjas** [comment]
Thats strange. These files were auto created through auto backup feature of my expenses app daily at 7AM.
![Screenshot_20210621-084711_Nova_Launcher](https://user-images.githubusercontent.com/788766/122702899-0b22d600-d26e-11eb-9bd6-fa9f01fc132a.png)

But strangely, when i modified the default export folder to a different path yesterday, today at 7AM, the export file gets created with .enc extention, and manual backup also creates in .enc extention. Before this path change, both options created only .enc.bin extention.

If you need something else to debug, let me know.

**Comment by mtotschnig** [comment]
Can you confirm that restoration works correctly with the file with enc extension?
Could you document on which Android 10 device the backups with bin extension were created?
And eventually share such a file that you created from an installation with minimal data?

**Comment by ashjas** [comment]
Yes, with the .enc version i was able to restore the db correctly.
It was mi A1 with carbon ROM android 10.
I am afraid, i wont be able to share some sample file for debugging, since that device has some h/w issues and wont boot.
Ill try my best to share if i ever see the .bin extention backup file.

Thanks.

**Comment by mtotschnig** [comment]
In 3.2.5. MyExpenses will handle encrypted backups independent of the file extension
