### ISSUE TITLE
api.ratesapi.io doesn't work anymore

### ISSUE THREAD

**Issue by Teofil-Buhosu** [mtotschnig/MyExpenses#847]
api.ratesapi.io does not work anymore, ratesapi.io redirects to exchangeratesapi.io.

![Screenshot_20210623-115811_My_Expenses](https://user-images.githubusercontent.com/65247071/123075240-b96e7d00-d420-11eb-9c0e-3d82cdcff943.png)

This has a free subscription so maybe changing the endpoint of the api requests to https://api.exchangeratesapi.io/v1/ and allowing the user to input the free subscription API key they receive can be a solution.

**Comment by mtotschnig** [comment]
Thank you for the report! As suggested on https://github.com/apilayer/ratesapi/issues/22 , I will migrate to https://exchangerate.host/ , which does not require a user provided key.

**Comment by mtotschnig** [comment]
This will shortly be published with version 3.3.3. If you make heavy use of it, please consider donating to: https://exchangerate.host/#/donate
