### ISSUE TITLE
Category icons improvements

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#888]
1. Provide more icons
2. Allow search

**Comment by ydrolet** [comment]
I use the app [Swipetimes](https://play.google.com/store/apps/details?id=lc.st.free) and it has a huge icons database, with categories :

<img src="https://user-images.githubusercontent.com/5557729/182244854-ef21dcf5-2440-4265-bcad-6ed86f643323.png" width="300">

I find their icons collection pretty useful and complete. The credits in the app mention these sources for the icons :
 * https://fontawesome.com/
 * https://www.flaticon.com/authors/itim2101
 * https://www.flaticon.com/authors/freepik
 * https://www.flaticon.com/authors/roundicons

I didn't check if these sources are royalty-free.

For the icon search, it could be nice to have it. Each icon would need to have a descriptive short name. Not sure the repos above give that. Fuzzy search would be a great addition.

**Comment by mtotschnig** [comment]
@ydrolet Thank you very much for the pointer. The categorization used by Swipetimes seems to be based partially on how icons are categorized in Fontawesome (https://fontawesome.com/icons/categories), and I already had the same idea, since there information is available on Github (https://github.com/FortAwesome/Font-Awesome/blob/6.x/metadata/categories.yml).
