### ISSUE TITLE
Tags for split parts

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#889]
Tags can at the moment only be defined for the split parents, not for split parts.

**Comment by amarradi** [comment]
For example, is it the comma to separate the keywords? Good Idea!

**Comment by mtotschnig** [comment]
@amarradi I do not understand what you mean by your question. Could you explain?

**Comment by amarradi** [comment]
If, for example, I want to assign three keywords and simply enter them comma-separated, then these are not 3 keywords but one
Car, insurance, alliance. However, it would be desirable if these were three individual keywords.

**Comment by mtotschnig** [comment]
Do you mean, that at the moment, you enter these Keywords into the Notes field?

**Comment by amarradi** [comment]
Yes, very easy enter the three wird's in the textfield

**Comment by mtotschnig** [comment]
This ticket refers to the tag feature. Users can maintain a list of tags and associate these with transactions.
This ticket also refers to split transactions. Currently you can only use tags for the parent transaction, and not for the parts.
