### ISSUE TITLE
Encrypted backup not recognized

### ISSUE THREAD

**Issue by mtotschnig** [mtotschnig/MyExpenses#891]
On some devices, encrypted backup is created with a .bin extension. User can select this file for restore, but then it is not recognized as encrypted, leading to a misleading error message:
"No file BACKUP found in archive ".../cache".

**Comment by Popkornium18** [comment]
You will probably hate this question, but is there an ETA for 3.3.5? I'm running into this bug while restoring a backup after destroying my phone.

**Comment by mtotschnig** [comment]
@Popkornium18 If you just rename the file, removing the .bin extension, so that its extension is .enc, before you try to restore it, I think it should work.

**Comment by Popkornium18** [comment]
I have done that, but it still says: 

```
Restore ...
No file BACKUP found in archive "/storage/emulated/0/Android/data/org.totschnig.myexpenses/cache"
```

If I try to restore from WebDAV it only says:

```
The backup file is encrypted. In order to decrypt it, you need to specify its passphrase.
```
I don't see an option to specify the passphrase.

**Comment by mtotschnig** [comment]
> I have done that, but it still says:
> 
> ```
> Restore ...
> No file BACKUP found in archive "/storage/emulated/0/Android/data/org.totschnig.myexpenses/cache"
> ```

This is strange. On my side, with version 3.3.4.2, when I restore from the Settings screen and select a file with extension .enc, it is recognized as encrypted, and I get a dialogue informing me that I need to set the password in the Settings, if it is not set.

> If I try to restore from WebDAV it only says:
> 
> ```
> The backup file is encrypted. In order to decrypt it, you need to specify its passphrase.
> ```
> 
> I don't see an option to specify the passphrase.

I understand, that you restore from the Onboarding Screen, by choosing the option "Restore from Cloud Sync"? It is true, that the prompt for the password is missing from that flow (#897). So we are back to the need to restore it from a local file.

In order to assess if there is some corruption with your file, you could send it to support@myexpenses.mobi, but of course, I understand if this is not an option for you.
In order to test if the changes in upcoming 3.3.5. solve your problem, I could push a pre-release to the beta channel on Play Store tomorrow, if you were willing to join the group (https://groups.google.com/g/my-expenses-testing/c/RGiWUEWz154)

**Comment by Popkornium18** [comment]
I don't think the file is compromised, because I managed to revive my phone and created a new local backup. I have the same issue with that file.

**Comment by Popkornium18** [comment]
Testing a pre release version would be nice, however I installed MyExpenses from F-Droid and don't have access to the play store.

**Comment by mtotschnig** [comment]
Unfortunately, F-Droid does not allow publication of pre-releases. On Play-Store, 3.3.5 is now published to the Beta channel (https://groups.google.com/g/my-expenses-testing/c/RGiWUEWz154).
So you can compile it yourself, but you would not be able to update from your self-compiled version to the version from F-Droid. But with backups, you should be able to migrate data from one to the other.

**Comment by Popkornium18** [comment]
I compiled MyExpenses but adding the WebDAV share just crashes the app. Importing a local file shows a prompt that it is encrypted but there is no way to input a password. The `No file BACKUP found in archive ...` message is gone though.

**Comment by mtotschnig** [comment]
@Popkornium18 Could you share the stacktrace of the crash?

If you restore a backup from local storage:

- during app installation, from the Onboarding screen, there should be a prompt for the password.
- from the Settings screen, you need to enter the password via the "Passphrase from backups" setting.

Does neither of these work for you?

**Comment by Popkornium18** [comment]
I sent a stacktrace via mail.
I was able to restore the data from the settings screen. However I did not see an option te set a password in the Onboardings screen.

**Comment by mtotschnig** [comment]
I am glad that you succeeded in restoring the data. I am still curious why you do not get the password prompt from the Onboarding restore option. If it were possible for you to create a screen recording of how you proceed, that might allow me to understand what is different in your context from mine.

**Comment by Popkornium18** [comment]
Sure. I'll send you a link.
