### ISSUE TITLE
Status after cloning is unchangeable

### ISSUE THREAD

**Issue by Anmibe** [mtotschnig/MyExpenses#892]
After cloning a reconciled transaction one can’t change its status. Best solution would be to set the status after cloning  to unreconciled.

 ![Bildschirmfoto_20211102_105021](https://user-images.githubusercontent.com/56979681/139825082-178ae02d-3d7c-4f95-bd93-f262df0b4fec.png)

**Comment by mtotschnig** [comment]
Thanks for bringing it up. This seems to be a regression: #188 .

**Comment by mtotschnig** [comment]
I tried to reproduce this, but on my side, cloning a reconciled transaction correctly initializes the clone to status unreconciled. Maybe there is a misunderstanding with respect to how you achieve the cloning. Could you describe in detail?

**Comment by mtotschnig** [comment]
There is one scenario, which is related to cloning where the problem can reproduced: If you edit a transaction, activate "Save and New", the new transaction which is essentially a clone has the described defect.
