### ISSUE TITLE
Update website with Weblate translations

### ISSUE THREAD

**Issue by milotype** [mtotschnig/MyExpenses#896]
Croatian website https://www.myexpenses.mobi/hr/ does not use the current translations.

For instance, strings like `Easy to use`, `Rich functionality` and `Open Source` do not show the current translations.

**Comment by mtotschnig** [comment]
Many thanks for making me aware of the problem, and sorry for not taking up your valuable contribution for a long time. The Website resource on Weblate was setup differently from the other resources and I forgot to incorporate them correctly. This is now done.
