### ISSUE TITLE
Unable to select payee by taping on the name

### ISSUE THREAD

**Issue by sivaraam** [mtotschnig/MyExpenses#900]
When I try to search for a particular Payee/Payer, I'm not able to select the party by taping on the name. I explicitly have to tap on the checkbox to select the party. It would be nice if the selection occurred when tapping on the name too. As a matter of fact, I think it was possible in previous versions.

I'm using v3.3.4.2 of the app on a OnePlus Nord with Android 11.

**Comment by mtotschnig** [comment]
Recently, the party list was refactored to no longer use the contextual action bar for multi selection, and in that context, I tried to unify single and multi selection with the checkbox. But I understand that selecting one party by simply clicking on it, is still useful, so I will reintroduce it.

**Comment by sivaraam** [comment]
> But I understand that selecting one party by simply clicking on it, is still useful, so I will reintroduce it.

Wouldn't it be useful for multi-party selection by clicking on the payee name too ? Actually, I was hoping clicking on the name would just select the payee. I find it surprising that it does a search on the specific party instead.

**Comment by mtotschnig** [comment]
@sivaraam You are right, I misunderstood your original suggestion. I'll correct this in next version.
