### ISSUE TITLE
What is the approach for a multi-currency account? 

### ISSUE THREAD

**Issue by orleanski** [mtotschnig/MyExpenses#902]
Hello,

What is a common practice to handle multi-currency accounts.
Let's say I have Euro and USD on my PayPal, how should it be reflected in My expenses? Should it be two separate accounts like PayPal-€ and PayPal-$ or there is any other solutions?

Thank you in advance.

**Comment by mtotschnig** [comment]
My Expenses does not allow multiple currencies for one account, so I think two separate accounts like you suggest is the most practical solution.
