### ISSUE TITLE
Budget - Sum leftover/negative budget balance with all previous months

### ISSUE THREAD

**Issue by cmdPereira** [mtotschnig/MyExpenses#915]
If from the €200 budget of an month, €50 is left over, those €50 are added to the budget for the following month, leaving me with €250 for the current month. The same happens if I spend €50 over the budget, in the following month, that amount will be withdrawn, in this case I would only have €150 that month.

**Comment by sigttou** [comment]
>Should the rollover of a positive/negative balance for a budget be automatic or manual? 

I'd like to have an option to set it to automatic, but also do it manually,
Also it would be nice to have a rollover time frame, like I have a monthly food budget but want to check if I can stay within limits over a year.

>Should there be an option for the budget, that allows to decide if the roll over should happen automatically, on demand or never?

I'd like such an option.

**Comment by mtotschnig** [comment]
@sigttou 
> I'd like to have an option to set it to automatic, but also do it manually, Also it would be nice to have a rollover time frame, like I have a monthly food budget but want to check if I can stay within limits over a year.

This is an interesting idea, but probably out of scope of this ticket. I do not really see how this could be achieved UI wise. And it might be more straightforward to create an additional yearly budget for this.

**Comment by mtotschnig** [comment]
The challenge with automatic rollover is that calculating them always on the fly is probably too expensive, so it must be calculated and stored at a certain time. Then if there are changes to past periods, the calculated amount would need to be recalculated.
