### ISSUE TITLE
Budget - If i change the allocated amount of a budget, it should only change from that month forward and not all previous months

### ISSUE THREAD

**Issue by cmdPereira** [mtotschnig/MyExpenses#917]
Example: You have a budget for your 'wants', you get a raise and you decide to change the budget of your 'wants'. It shouldn't change all months, just the one you change and forward. 

If this feature is implemented, it should take consideration with issue #915

**Comment by sigttou** [comment]
I like the proposed pop-up idea, as from the email:
```
When a user edits an existing budget (either the total allocated amount,
or the amount allocated to a category, a popup will ask him to confirm
if the amount should be changed for
a) for the currently displayed period only.
b) for the current and future periods.
c) for the all periods.```

**Comment by allista** [comment]
First, I don't see the point to change past budgets, as they are history and probably should only be consulted to plan ahead.

As for the pop-up, I think one of the remaining options should be _default_; maybe configurable; maybe even per budget instance/period:

- When I first create a budget, there's a somewhat long stage of fine-tuning it with constant edits of sub/categories. It would be annoying if on any change a pop-up showed up.
- Then at some point the desired default behavior should change to, say, "apply to current period only".
- This also asks for a way to manually propagate the changes to the future budgets - when the changes to the current budget are considered to be long-term.

To wrap this up:
- change only the current and future budgets
- by default (configurable?) change only the current one
- have an menu option/button to propagate current budget to the future

**Comment by mtotschnig** [comment]
@allista Thank you for your ideas. Based on them, I came up with the following plan:
Database: Budgets in the database always reference a certain period. They are valid starting from this period, unless a one-time flag is set, in which case, they are valid only for the referenced period. This means for every period where no budget is set, the nearest budget from the past will be used. If user navigates into the past to a period for which there is not budget further in the past, the nearest budget after the period will be used.
UI: By default, when user edits budgets, these are stored without the one-time flag, i.e. they will be valid starting from the current period. A checkbox in the menu allows to activate the one-time flag.

**Comment by allista** [comment]
@mtotschnig I tried to read through the commit above, but expectedly understood too little. So I'll ask instead:

1. What happens when the period referenced by a one-time budget ends?

E.g., I want to change the budget for the current period only; I set the one-time flag and edit some allocations to categories. Then the period ends (or I simply switch to the next period). When I return to the _Budgeting_ view, what would I see? Is the budget still there? If it is, what would show it's categories? 

2. If I update the budget without the one-time flag, then switch to the previous period, will the previous allocations be affected?

**Comment by allista** [comment]
Oh, and what if I remove the one-time flag from a past budget?

**Comment by mtotschnig** [comment]
For example. You create a budget with allocations in May. In September, you define some one-time values, so in October you will see the same allocations as in the months you see from May to August.
If you modify the allocations in September and remove one-time flag, they will then be valid starting from September, i.e. you will also see the in October, but August will still have the original values from May. This is true for past budgets as well: If we are already in December, and you set values for September that are not one-time, they will affect any month after September as long as the allocation is not set to a new value.
I hope this makes sense.

**Comment by allista** [comment]
Perfectly, thank you for the explanation.
Indeed, this implementation should satisfy all the use cases I described.
