### ISSUE TITLE
Database upgrade failed

### ISSUE THREAD

**Issue by orleanski** [mtotschnig/MyExpenses#924]
Hi, after upgrade to very 3.3.6 on 2022-02-04
I was greeted with the message that database upgrade failed and I have to contact by email.

So After fingerprint, then the message, then the app closes.

Any help would be appreciated.

Please let me know if you need any additional info. 

Thank you in advance.

**Comment by mtotschnig** [comment]
Thank you for the report and sorry for the inconvenience. I am publishing a fix (3a7ff6f9bbc13264a2b52ffbb6a8f3671af5b2bc) to Play Store today.

**Comment by orleanski** [comment]
New update solved the error, no data loss noted. Thank you. Please close the issue.
