### ISSUE TITLE
Not receiving premium features after puchasing?

### ISSUE THREAD

**Issue by mattfj10** [mtotschnig/MyExpenses#928]
I bought the budgeting purchase, the extended key, and receipt scanning. I immediately received access to budgeting, however even though my purchase went through on paypal for the others I did not receive functionality for the other two after purchase. Although I don't feel this is github worthy, I didn't see a support email or anything on the site or the app so I figured i'd post here.

**Comment by mtotschnig** [comment]
There might be an issue with multiple purchases done in a row. I will investigate. If you navigate to Settings -> Enter Key and tap on the Validate button, I suppose, all your purchases should be activated.

**Comment by mtotschnig** [comment]
There is a "Send feedback" item in the Settings, but you are right, support address (support@myexpenses.mobi) should be mentioned on the website. I'll add it.

**Comment by mtotschnig** [comment]
@mattfj10 Out of interest, could you provide a pointer to the source of that recommendation?

**Comment by mattfj10** [comment]
> @mattfj10 Out of interest, could you provide a pointer to the source of that recommendation?

https://www.reddit.com/r/fossdroid/comments/smvd6h/what_is_the_best_budgetingexpenses_foss_app_for/

This is the Reddit post, actually posted the same day as I started searching conveniently.
