### ISSUE TITLE
Guidelines for import from Fast Budget app?

### ISSUE THREAD

**Issue by azsdaja** [mtotschnig/MyExpenses#937]
Hello!
I'm considering switching to MyExpenses from Fast Budget (https://fastbudget.app/). However, I have there a few years of history of my expenses and I wouldn't like to loose them. I want to preserve expense dates, descriptions, amounts and categories. I don't care about receipt photos. Would an export to CSV and import in MyExpenses be the way to go? Are there any blockers or additional steps I'd need to take?
Thank you.

**Comment by mtotschnig** [comment]
I am unaware of the exact way that Fast Budget formats its CSV export, but I suppose that the flexibility of My Expenses CSV import should allow to deal with it. If you encounter issues, please report detailed description.
