### ISSUE TITLE
Question: Importing CSV from Bank accounts

### ISSUE THREAD

**Issue by anishmittal2020** [mtotschnig/MyExpenses#955]
I have 3 bank accounts and there are several bank transfers from one to another (among these 3 bank accounts). When I import CSV of bank statements of all these bank accounts all transfers become transactions and are added to the `Total` income and expenses. 

Is it possible to convert all these inter-account transactions as Transfers? If not do you think (and recommend) if its possible to programmatically edit the exported QIF files of these accounts and to re-import them? 

As of now MyExpenses  does not allow even individual conversion of transaction to transfer, one needs to delete the transactions on both accounts and create a new transfer entry!

**Comment by mtotschnig** [comment]
Actually, there is support for exactly this use case in the app since #792 . You need to open the aggregate account, where both transactions are visible, you can then select and link them.
