### ISSUE TITLE
Distribution & History combining several or all accounts

### ISSUE THREAD

**Issue by tbdal** [mtotschnig/MyExpenses#956]

**Comment by mtotschnig** [comment]
This is possible simply by calling the function from an aggregate account, i.e. from the account that sums up all accounts with the same currency, and the Grand Total account if you use multiple currencies.

**Comment by mtotschnig** [comment]
Since version 3.7.8, it is possible to use the Account filter, to select a subset of all accounts, and this selection will be applied also on Distribution and History screens.
