### ISSUE TITLE
Nested list in a single transaction

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mtotschnig/MyExpenses#958]
### Summary
Single transaction containing multiple separate items

### Details
* Many times, i have many items that i purchase from a single place, 
* so, all other details (timestamp, payee, category, tags) stay same, only the item name and amount differs
* but i either have to:
    * create multiple transactions for each item, or 
    * enter all items in single transaction, and add details in the notes
    * but even that is not pleasant owing to #957

∴ So, the proposal is to have ability to add multiple separate items (with their individual amount) in a single transaction

### Versions
* myexpenses : 3.3.7 (515)
* Android: 11

**Comment by mtotschnig** [comment]
We have split transactions since 2013 #38 . Create a split transaction by changing the type from the drop-down on the edit screen. Or long press the floating action button on the main screen.

**Comment by yashpalgoyal1304** [comment]
Can u share a screenshot of an illustrative example of split transaction??

Michael Totschnig wrote:

> split transactions since 2013
>

**Comment by mtotschnig** [comment]
@yashpalgoyal1304 I have added an entry to the FAQ, and linked to a tutorial video:
https://mastodon.social/web/@myexpenses/108157424062320322
