### ISSUE TITLE
Feature Request: Check balance in the future

### ISSUE THREAD

**Issue by alex9099** [mtotschnig/MyExpenses#982]
So it's possible to make transactions apply in the future, it would be nice to see the predicted balance at a specific date in the future (or... In the past)

**Comment by mtotschnig** [comment]
My Expenses already shows the Total balance  which includes all future transactions. With daily grouping you should also be able to see the balance for a specific date.
Balance for every transaction is discussed in context of #239 .
Am I missing some other aspect of your suggestion?

**Comment by alex9099** [comment]
I didn't see the grouping feature, that does the trick, looks a bit clustered though, maybe that could see some customisation (for example, only show total balance if there's just one transaction, though that would yeld a similar result to the issue you linked)

I'm closing this as i think that solves my use case
