### ISSUE TITLE
Afficher le solde restant sur chaque ligne d'opération

### ISSUE THREAD

**Issue by jmc80** [mtotschnig/MyExpenses#99]
> Bonjour
> Votre application à beaucoup progressé.
> Bravo pour le travail réalisé
> La seule chose qui manque encore pour moi est l'affichage du solde restant 
> sur chaque ligne d'opération plutôt que le solde mensuel hebdomadaire ou journalier avec le regroupement
> Pensez vous pouvoir réaliser cela ?
> Merci beaucoup

**Comment by mtotschnig** [comment]
Duplicate of #239
